export type AdSlot={id:string;name:string;position:string;size:string;mediaType:'image'|'video';mediaUrl:string;title:string;description:string;pricePerDay:number;durationDays:number;enabled:boolean;fixed:boolean;dismissible:boolean;autoCloseMinutes:number;};
export type DiscountConfig={enabled:boolean;imageUrl:string;videoUrl:string;mediaType:'image'|'video';nameByLang:Record<string,string>;priceText:string;buttonTextByLang:Record<string,string>;repeatAfterMinutes:number;displayDurationMinutes:number;dismissible:boolean;fixed:boolean;};
export const DEFAULT_DISCOUNT:DiscountConfig={enabled:true,imageUrl:'/jamal-james.jpg',videoUrl:'',mediaType:'image',nameByLang:{ar:'دكتور جمال نادي',ru:'ДОКТОР ДЖЕЙМС',en:'Dr. James',de:'Dr. James',uk:'Доктор Джеймс',uz:'Doktor Jeyms',hy:'Դոկտոր Ջեյմս',tg:'Доктор Ҷеймс',az:'Doktor Ceyms',am:'ዶክተር ጄምስ',ka:'დოქტორი ჯეიმსი'},priceText:'25 USD',buttonTextByLang:{ar:'احجز الآن',en:'Book now',ru:'Записаться',de:'Jetzt buchen'},repeatAfterMinutes:30,displayDurationMinutes:10,dismissible:true,fixed:true};
export const DEFAULT_AD_SLOTS:AdSlot[]=[
{id:'home-top',name:'إعلان أعلى الصفحة',position:'أعلى الصفحة',size:'728x90',mediaType:'image',mediaUrl:'',title:'مساحة إعلان — صورة / بانر',description:'مكان مخصص لإعلان صورة أو بانر يضاف من مركز الإعلانات.',pricePerDay:50,durationDays:1,enabled:false,fixed:false,dismissible:true,autoCloseMinutes:0},
{id:'home-side',name:'إعلان جانبي',position:'الشريط الجانبي',size:'300x250',mediaType:'image',mediaUrl:'',title:'مساحة إعلان — نص / صورة',description:'مكان مخصص لإعلان نصي أو صورة.',pricePerDay:35,durationDays:1,enabled:false,fixed:false,dismissible:true,autoCloseMinutes:0},
{id:'content-bottom',name:'إعلان أسفل المحتوى',position:'أسفل المحتوى',size:'728x180',mediaType:'video',mediaUrl:'',title:'مساحة إعلان — فيديو',description:'مكان مخصص لفيديو إعلاني يضاف من مركز الإعلانات.',pricePerDay:40,durationDays:1,enabled:false,fixed:false,dismissible:true,autoCloseMinutes:0}
];
const DISCOUNT_KEY='sb1_discount_config_v3',SLOTS_KEY='sb1_ad_slots_v3';
export function getDiscountConfig():DiscountConfig{try{return {...DEFAULT_DISCOUNT,...JSON.parse(localStorage.getItem(DISCOUNT_KEY)||'{}')}}catch{return DEFAULT_DISCOUNT}}
export function saveDiscountConfig(v:DiscountConfig){localStorage.setItem(DISCOUNT_KEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-ad-config-change'))}
export function getAdSlots():AdSlot[]{try{const v=JSON.parse(localStorage.getItem(SLOTS_KEY)||'null');const slots=Array.isArray(v)&&v.length?v:DEFAULT_AD_SLOTS;return slots.map((s:AdSlot)=>s.id==='home-top'?{...s,enabled:false}:s)}catch{return DEFAULT_AD_SLOTS}}
export function saveAdSlots(v:AdSlot[]){localStorage.setItem(SLOTS_KEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-ad-config-change'))}
export function adPrice(slot:AdSlot,durationDays:number){return Math.max(0,slot.pricePerDay)*Math.max(1,durationDays)}
