export type AppointmentStatus='pending'|'accepted'|'rejected'|'cancelled'|'completed';
export type Appointment={id:string;doctorId:string;doctorName:string;doctorPhoto?:string;specialty:string;specialtySlug:string;patientName:string;patientId:string;requestedAt:string;scheduledAt:string|null;requestedTimeText:string;durationMinutes:number;status:AppointmentStatus;mode:'video';createdAt:string;acceptedAt?:string;rejectionReason?:string;};
export type AppointmentNotification={id:string;appointmentId:string;recipient:'patient'|'doctor';kind:'accepted'|'one_day'|'six_hours'|'one_hour'|'ten_minutes'|'now';text:string;createdAt:string;read:boolean;};
const KEY='sb1_video_appointments';const NKEY='sb1_appointment_notifications';
export function getAppointments():Appointment[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
export function saveAppointments(v:Appointment[]){localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-appointments-change'))}
export function getNotifications():AppointmentNotification[]{try{return JSON.parse(localStorage.getItem(NKEY)||'[]')}catch{return[]}}
export function saveNotifications(v:AppointmentNotification[]){localStorage.setItem(NKEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-appointments-change'))}
export function requestAppointment(a:Omit<Appointment,'id'|'createdAt'|'status'>){const x:Appointment={...a,id:'apt-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),status:'pending'};saveAppointments([x,...getAppointments()]);return x}
export function acceptAppointment(id:string,scheduledAt:string){const all=getAppointments();const x=all.find(a=>a.id===id);if(!x)return null;const next={...x,status:'accepted' as const,scheduledAt,acceptedAt:new Date().toISOString()};saveAppointments(all.map(a=>a.id===id?next:a));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'تم قبول جلسة الفيديو مع '+x.doctorName+' في '+new Date(scheduledAt).toLocaleString()});return next}
export function rejectAppointment(id:string,reason:string){const all=getAppointments();const x=all.find(a=>a.id===id);if(!x)return null;const next={...x,status:'rejected' as const,rejectionReason:reason};saveAppointments(all.map(a=>a.id===id?next:a));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'لم يتم قبول طلب الجلسة مع '+x.doctorName+'. '+reason});return next}
export function addNotification(x:Omit<AppointmentNotification,'id'|'createdAt'|'read'>){const n={...x,id:'an-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),createdAt:new Date().toISOString(),read:false};saveNotifications([n,...getNotifications()].slice(0,100));try{if('Notification' in window&&Notification.permission==='granted')new Notification('SB1',{body:n.text})}catch{}}
export function requestBrowserNotifications(){try{if('Notification' in window&&Notification.permission==='default')Notification.requestPermission()}catch{}}
export function reminderKind(ms:number){if(ms<=0)return'now' as const;if(ms<=10*60*1000)return'ten_minutes' as const;if(ms<=60*60*1000)return'one_hour' as const;if(ms<=6*60*60*1000)return'six_hours' as const;if(ms<=24*60*60*1000)return'one_day' as const;return null}
export function runAppointmentReminders(lang='ar'){const all=getAppointments();const now=Date.now();const notes=getNotifications();const created=new Set(notes.map(n=>n.appointmentId+'|'+n.kind));for(const a of all){if(a.status!=='accepted'||!a.scheduledAt)continue;const ms=new Date(a.scheduledAt).getTime()-now;const kind=reminderKind(ms);if(!kind||created.has(a.id+'|'+kind))continue;const labels:any={ar:{one_day:'تبقى يوم واحد',six_hours:'تبقى 6 ساعات',one_hour:'تبقى ساعة واحدة',ten_minutes:'تبقى 10 دقائق',now:'حان موعد جلسة الفيديو'},en:{one_day:'1 day remaining',six_hours:'6 hours remaining',one_hour:'1 hour remaining',ten_minutes:'10 minutes remaining',now:'Your video session is starting now'},ru:{one_day:'Остался 1 день',six_hours:'Осталось 6 часов',one_hour:'Остался 1 час',ten_minutes:'Осталось 10 минут',now:'Видеосессия начинается сейчас'}};const l=labels[lang]||labels.en;const text='SB1 — '+l[kind]+': '+a.doctorName+' · '+a.specialty;addNotification({appointmentId:a.id,recipient:'patient',kind,text});addNotification({appointmentId:a.id,recipient:'doctor',kind,text});}}
export function nextAcceptedAppointment(){return getAppointments().filter(a=>a.status==='accepted'&&a.scheduledAt&&new Date(a.scheduledAt).getTime()>Date.now()).sort((a,b)=>new Date(a.scheduledAt!).getTime()-new Date(b.scheduledAt!).getTime())[0]||null}
export function formatRemaining(ms:number,lang='ar'){if(ms<=0)return lang==='ar'?'الآن':'Now';const s=Math.floor(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;if(lang==='ar')return [d?d+' يوم':'',h?h+' س':'',m?m+' د':'',sec+' ث'].filter(Boolean).join(' ');return [d?d+'d':'',h?h+'h':'',m?m+'m':'',sec+'s'].filter(Boolean).join(' ')}