export type AppointmentStatus='pending'|'accepted'|'rejected'|'cancelled'|'completed';
export type Appointment={id:string;doctorId:string;doctorName:string;doctorPhoto?:string;specialty:string;specialtySlug:string;patientName:string;patientId:string;requestedAt:string;scheduledAt:string|null;requestedTimeText:string;durationMinutes:number;price:number;currency:string;paymentStatus:'paid'|'pending'|'refunded';status:AppointmentStatus;mode:'video';createdAt:string;acceptedAt?:string;rejectionReason?:string;rescheduleCount:number;doctorChangeCount:number;originalScheduledAt:string|null;previousScheduledAt?:string;meetingUrl?:string;}
export type AppointmentNotification={id:string;appointmentId:string;recipient:'patient'|'doctor';kind:'accepted'|'one_day'|'six_hours'|'one_hour'|'ten_minutes'|'now';text:string;createdAt:string;read:boolean;};
const KEY='sb1_video_appointments';const NKEY='sb1_appointment_notifications';
export function getAppointments():Appointment[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
export function saveAppointments(v:Appointment[]){localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-appointments-change'))}
export function getNotifications():AppointmentNotification[]{try{return JSON.parse(localStorage.getItem(NKEY)||'[]')}catch{return[]}}
export function saveNotifications(v:AppointmentNotification[]){localStorage.setItem(NKEY,JSON.stringify(v));window.dispatchEvent(new Event('sb1-appointments-change'))}
export function requestAppointment(a:Omit<Appointment,'id'|'createdAt'|'status'|'rescheduleCount'|'doctorChangeCount'>){const x:Appointment={...a,id:'apt-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),createdAt:new Date().toISOString(),status:'pending',rescheduleCount:0,doctorChangeCount:0,originalScheduledAt:a.scheduledAt,meetingUrl:'https://meet.jit.si/SB1-'+Date.now()};saveAppointments([x,...getAppointments()]);return x}
export function acceptAppointment(id:string,scheduledAt:string){const all=getAppointments();const x=all.find(a=>a.id===id);if(!x)return null;const next={...x,status:'accepted' as const,scheduledAt,acceptedAt:new Date().toISOString()};saveAppointments(all.map(a=>a.id===id?next:a));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'تم قبول جلسة الفيديو مع '+x.doctorName+' في '+new Date(scheduledAt).toLocaleString()});return next}
export function rejectAppointment(id:string,reason:string){const all=getAppointments();const x=all.find(a=>a.id===id);if(!x)return null;const next={...x,status:'rejected' as const,rejectionReason:reason};saveAppointments(all.map(a=>a.id===id?next:a));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'لم يتم قبول طلب الجلسة مع '+x.doctorName+'. '+reason});return next}
export function addNotification(x:Omit<AppointmentNotification,'id'|'createdAt'|'read'>){const n={...x,id:'an-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),createdAt:new Date().toISOString(),read:false};saveNotifications([n,...getNotifications()].slice(0,100));try{if('Notification' in window&&Notification.permission==='granted')new Notification('SB1',{body:n.text})}catch{}}
export function requestBrowserNotifications(){try{if('Notification' in window&&Notification.permission==='default')Notification.requestPermission()}catch{}}
export function reminderKind(ms:number){if(ms<=0)return'now' as const;if(ms<=10*60*1000)return'ten_minutes' as const;if(ms<=60*60*1000)return'one_hour' as const;if(ms<=6*60*60*1000)return'six_hours' as const;if(ms<=24*60*60*1000)return'one_day' as const;return null}
export function runAppointmentReminders(lang='ar'){const all=getAppointments();const now=Date.now();const notes=getNotifications();const created=new Set(notes.map(n=>n.appointmentId+'|'+n.kind));for(const a of all){if(a.status!=='accepted'||!a.scheduledAt)continue;const ms=new Date(a.scheduledAt).getTime()-now;const kind=reminderKind(ms);if(!kind||created.has(a.id+'|'+kind))continue;const labels:any={ar:{one_day:'تبقى يوم واحد',six_hours:'تبقى 6 ساعات',one_hour:'تبقى ساعة واحدة',ten_minutes:'تبقى 10 دقائق',now:'حان موعد جلسة الفيديو'},en:{one_day:'1 day remaining',six_hours:'6 hours remaining',one_hour:'1 hour remaining',ten_minutes:'10 minutes remaining',now:'Your video session is starting now'},ru:{one_day:'Остался 1 день',six_hours:'Осталось 6 часов',one_hour:'Остался 1 час',ten_minutes:'Осталось 10 минут',now:'Видеосессия начинается сейчас'}};const l=labels[lang]||labels.en;const text='SB1 — '+l[kind]+': '+a.doctorName+' · '+a.specialty;addNotification({appointmentId:a.id,recipient:'patient',kind,text});addNotification({appointmentId:a.id,recipient:'doctor',kind,text});}}
export function nextAcceptedAppointment(){return getAppointments().filter(a=>a.status==='accepted'&&a.scheduledAt&&new Date(a.scheduledAt).getTime()>Date.now()).sort((a,b)=>new Date(a.scheduledAt!).getTime()-new Date(b.scheduledAt!).getTime())[0]||null}
export function formatRemaining(ms:number,lang='ar'){if(ms<=0)return lang==='ar'?'الآن':'Now';const s=Math.floor(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;if(lang==='ar')return [d?d+' يوم':'',h?h+' س':'',m?m+' د':'',sec+' ث'].filter(Boolean).join(' ');return [d?d+'d':'',h?h+'h':'',m?m+'m':'',sec+'s'].filter(Boolean).join(' ')}
export function updateAppointment(id:string,patch:Partial<Appointment>){const all=getAppointments();const x=all.find(a=>a.id===id);if(!x)return null;const next={...x,...patch};saveAppointments(all.map(a=>a.id===id?next:a));return next;}
export function canReschedule(a:Appointment,actor:'patient'|'doctor'){if(a.status!=='accepted'||!a.scheduledAt)return {ok:false,reason:'الجلسة ليست مقبولة'};const hours=(new Date(a.scheduledAt).getTime()-Date.now())/3600000;if(hours<3)return {ok:false,reason:'لا يمكن تغيير الموعد قبل أقل من 3 ساعات'};if(a.rescheduleCount===0)return {ok:true,fee:0};if(a.rescheduleCount===1)return hours>=12?{ok:true,fee:0}:{ok:false,reason:'التغيير الثاني يجب أن يكون قبل 12 ساعة على الأقل'};if(a.rescheduleCount===2)return {ok:true,fee:a.price*0.5};return {ok:false,reason:'تم استنفاد مرات تغيير الموعد'};}
export function rescheduleAppointment(id:string,newScheduledAt:string,actor:'patient'|'doctor',paidFee=0){const all=getAppointments();const a=all.find(x=>x.id===id);if(!a)return null;const rule=canReschedule(a,actor);if(!rule.ok||!newScheduledAt)return null;if(rule.fee>paidFee)return null;const next={...a,scheduledAt:newScheduledAt,rescheduleCount:a.rescheduleCount+1,previousScheduledAt:a.scheduledAt};saveAppointments(all.map(x=>x.id===id?next:x));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'تم تغيير موعد الجلسة إلى '+new Date(newScheduledAt).toLocaleString()});addNotification({appointmentId:id,recipient:'doctor',kind:'accepted',text:'تم تغيير موعد الجلسة إلى '+new Date(newScheduledAt).toLocaleString()});return next;}
export function canChangeDoctor(a:Appointment){if(a.status!=='accepted'||!a.scheduledAt)return {ok:false,reason:'الجلسة ليست مقبولة'};const hours=(new Date(a.scheduledAt).getTime()-Date.now())/3600000;if(hours<24)return {ok:false,reason:'تغيير الطبيب متاح فقط قبل 24 ساعة على الأقل'};if(a.doctorChangeCount===0)return {ok:true,fee:0};if(a.doctorChangeCount===1)return {ok:true,fee:a.price*0.5};return {ok:false,reason:'تم استنفاد مرات تغيير الطبيب'};}
export function changeDoctor(id:string,doctorId:string,doctorName:string,doctorPhoto:string|undefined,paidFee=0){const all=getAppointments();const a=all.find(x=>x.id===id);if(!a)return null;const rule=canChangeDoctor(a);if(!rule.ok||rule.fee>paidFee)return null;const next={...a,doctorId,doctorName,doctorPhoto,doctorChangeCount:a.doctorChangeCount+1};saveAppointments(all.map(x=>x.id===id?next:x));addNotification({appointmentId:id,recipient:'patient',kind:'accepted',text:'تم تغيير الطبيب إلى '+doctorName});addNotification({appointmentId:id,recipient:'doctor',kind:'accepted',text:'تم تحويل الجلسة إلى '+doctorName});return next;}
export function scheduleAppointmentReminders(a:Appointment){if(a.status!=='accepted'||!a.scheduledAt)return()=>{};const target=new Date(a.scheduledAt).getTime();const schedule=[{ms:86400000,kind:'one_day' as const},{ms:21600000,kind:'six_hours' as const},{ms:7200000,kind:'two_hours' as any},{ms:3600000,kind:'one_hour' as const},{ms:600000,kind:'ten_minutes' as const},{ms:0,kind:'now' as const}];const timers=schedule.map(x=>window.setTimeout(()=>{const left=target-Date.now();if(left<=x.ms+60000&&left>=-60000){addNotification({appointmentId:a.id,recipient:'patient',kind:x.kind,text:'SB1: تذكير بجلسة '+a.doctorName+' — '+(x.ms===0?'الآن':x.ms/3600000>=1?x.ms/3600000+' ساعات':x.ms/60000+' دقائق')});addNotification({appointmentId:a.id,recipient:'doctor',kind:x.kind,text:'SB1: تذكير بجلسة '+a.patientName+' — '+(x.ms===0?'الآن':x.ms/3600000>=1?x.ms/3600000+' ساعات':x.ms/60000+' دقائق')});}},Math.max(0,target-Date.now()-x.ms)));return()=>timers.forEach(clearTimeout);}
