import { supabase } from '@/lib/supabase';
export type Sanction={userKey:string;strike:number;reason:string;startedAt:string;until:string|null;level:string;permanent:boolean};
const STRIKES='sb1_safety_strikes_';const ALERTS='sb1_owner_moderator_alerts';
const durations=[60*60*1000,24*60*60*1000,7*24*60*60*1000];
export function safetyKey(userKey?:string){return userKey||localStorage.getItem('sb1_account_user_id')||localStorage.getItem('sb1_account_email')||localStorage.getItem('chat_email')||'guest'}
export function getSanction(userKey?:string):Sanction|null{try{const x=JSON.parse(localStorage.getItem(STRIKES+safetyKey(userKey))||'null');if(!x)return null;if(x.permanent||!x.until||Date.now()<Date.parse(x.until))return x;return null}catch{return null}}
export function registerViolation(userKey:string,reason:string,evidenceImage?:string){const key=safetyKey(userKey);let old:any={strike:0};try{old=JSON.parse(localStorage.getItem(STRIKES+key)||'{}')}catch{}const strike=Number(old.strike||0)+1;const permanent=strike>=4;const duration=durations[Math.min(strike-1,durations.length-1)];const until=permanent?null:new Date(Date.now()+duration).toISOString();const level=permanent?'permanent':strike===1?'1 hour':strike===2?'24 hours':'7 days';const sanction={userKey:key,strike,reason,startedAt:new Date().toISOString(),until,level,permanent};localStorage.setItem(STRIKES+key,JSON.stringify(sanction));
try{void supabase.from('sb1_safety_sanctions').insert({user_key:key,strike,reason,started_at:sanction.startedAt,until_at:until,level,permanent})}catch{}let alerts:any[]=[];try{alerts=JSON.parse(localStorage.getItem(ALERTS)||'[]')}catch{};alerts.unshift({id:'alert-'+Date.now(),type:'safety_violation',userKey:key,strike,reason,level,evidenceImage:evidenceImage||null,createdAt:new Date().toISOString(),recipients:['owner','moderators'],read:false});localStorage.setItem(ALERTS,JSON.stringify(alerts.slice(0,200)));
try{void supabase.from('sb1_owner_alerts').insert({alert_type:'safety_violation',user_key:key,strike,reason,level,evidence_image:evidenceImage||null,recipients:['owner','moderators'],created_at:new Date().toISOString()})}catch{}try{if('Notification'in window&&Notification.permission==='granted')new Notification('SB1 — تنبيه أمني',{body:`مخالفة رقم ${strike}: ${reason}. العقوبة: ${level}`,icon:'/jamal-james.jpg'});else if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}catch{};return sanction}
export function clearExpiredSanction(userKey?:string){const x=getSanction(userKey);return x}
export function ownerAlerts(){try{return JSON.parse(localStorage.getItem(ALERTS)||'[]')}catch{return[]}}
export function markAlertRead(id:string){const xs=ownerAlerts().map((x:any)=>x.id===id?{...x,read:true}:x);localStorage.setItem(ALERTS,JSON.stringify(xs))}
