export type VaultKind='article'|'reel'|'post'|'image'|'session'|'book'|'game'|'facility'|'question'|'doctor'|'course'|'video'|'recording';
export type VaultItem={id:string;kind:VaultKind;title:string;body?:string;author?:string;url?:string;image_url?:string;created_at:string};
const key=(name:string)=>'sb1_social_'+name;
const read=<T,>(name:string, fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key(name))||JSON.stringify(fallback))}catch{return fallback}};
const write=(name:string,value:any)=>{localStorage.setItem(key(name),JSON.stringify(value));window.dispatchEvent(new Event('sb1-social-change'))};
export const getSaved=()=>read<VaultItem[]>('saved',[]);
export const toggleSaved=(item:VaultItem)=>{const a=getSaved();const i=a.findIndex(x=>x.id===item.id);if(i>=0)a.splice(i,1);else a.unshift(item);write('saved',a);return a};
export const isSaved=(id:string)=>getSaved().some(x=>x.id===id);
export const getLiked=()=>read<VaultItem[]>('liked',[]);
export const toggleLiked=(item:VaultItem)=>{const a=getLiked();const i=a.findIndex(x=>x.id===item.id);if(i>=0)a.splice(i,1);else a.unshift(item);write('liked',a);return a};
export const isLiked=(id:string)=>getLiked().some(x=>x.id===id);
export const getArchived=()=>read<VaultItem[]>('archived',[]);
export const archiveItem=(item:VaultItem)=>{const a=getArchived();if(!a.some(x=>x.id===item.id))a.unshift(item);write('archived',a);write('saved',getSaved().filter(x=>x.id!==item.id));return a};
export const restoreItem=(id:string)=>{const a=getArchived();const item=a.find(x=>x.id===id);write('archived',a.filter(x=>x.id!==id));if(item)write('saved',[item,...getSaved().filter(x=>x.id!==id)]);return item};
export const getComments=()=>read<Record<string,string[]>>('comments',{});
export const addComment=(id:string,text:string)=>{const c=getComments();c[id]=[...(c[id]||[]),text];write('comments',c);return c[id]};
export const getFollowing=()=>read<string[]>('following',[]);
export const toggleFollowing=(id:string)=>{const a=getFollowing();const i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.unshift(id);write('following',a);return a};
export const setProfilePrivacy=(mode:'followers'|'private')=>write('privacy',mode);
export const getProfilePrivacy=()=>read<'followers'|'private'>('privacy','followers');
export const isFollowing=(id:string)=>getFollowing().includes(id);
