export type StoreAudience='all'|'specialist';
export type StoreProductType='question_package'|'course'|'book'|'subscription'|'consultation'|'test'|'app'|'specialist_service'|'other';
export type StoreProduct={id:string;name:string;description:string;image_url:string;price:number;currency:string;product_type:StoreProductType;audience:StoreAudience;language:string;active:boolean;stock:number|null;sort_order:number;created_at:string;updated_at:string};
const now=new Date().toISOString();
export const defaultStoreProducts:StoreProduct[]=[
{id:'store-q-10',name:'باقة 10 أسئلة',description:'شراء باقة أسئلة مدفوعة على SB1.',image_url:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80',price:9,currency:'USD',product_type:'question_package',audience:'all',language:'all',active:true,stock:null,sort_order:1,created_at:now,updated_at:now},
{id:'store-q-30',name:'باقة 30 سؤالاً',description:'باقة أكبر للاستخدام المتكرر.',image_url:'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=900&q=80',price:19,currency:'USD',product_type:'question_package',audience:'all',language:'all',active:true,stock:null,sort_order:2,created_at:now,updated_at:now},
{id:'store-courses',name:'باقة الدورات التدريبية',description:'الوصول إلى مجموعة دورات تدريبية رقمية.',image_url:'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=900&q=80',price:29,currency:'USD',product_type:'course',audience:'all',language:'all',active:true,stock:null,sort_order:3,created_at:now,updated_at:now},
{id:'store-books',name:'باقة الكتب الطبية',description:'مجموعة كتب ومراجع رقمية.',image_url:'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80',price:15,currency:'USD',product_type:'book',audience:'all',language:'all',active:true,stock:null,sort_order:4,created_at:now,updated_at:now},
{id:'store-consult',name:'جلسة استشارة خاصة',description:'رصيد لخدمة استشارة خاصة على المنصة.',image_url:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80',price:25,currency:'USD',product_type:'consultation',audience:'all',language:'all',active:true,stock:null,sort_order:5,created_at:now,updated_at:now},
{id:'store-tests',name:'حزمة الاختبارات الطبية والنفسية',description:'الوصول إلى مجموعة اختبارات وفحوصات تعليمية.',image_url:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=900&q=80',price:12,currency:'USD',product_type:'test',audience:'all',language:'all',active:true,stock:null,sort_order:6,created_at:now,updated_at:now},
{id:'store-specialist-promo',name:'ترويج ملف الأخصائي',description:'زيادة ظهور ملف الأخصائي داخل المنصة.',image_url:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80',price:20,currency:'USD',product_type:'specialist_service',audience:'specialist',language:'all',active:true,stock:null,sort_order:20,created_at:now,updated_at:now},
{id:'store-specialist-media',name:'حزمة ترويج المنشورات والريلز',description:'حزمة ترويجية مخصصة للأخصائيين.',image_url:'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80',price:18,currency:'USD',product_type:'specialist_service',audience:'specialist',language:'all',active:true,stock:null,sort_order:21,created_at:now,updated_at:now},
];
export const getStoredRole=()=>{if(typeof window==='undefined')return'client';return localStorage.getItem('sb1_account_role')||'client'};
export const getCart=():Array<{product:StoreProduct;quantity:number}>=>(typeof window==='undefined'?[]:JSON.parse(localStorage.getItem('sb1_cart')||'[]'));
export const saveCart=(cart:Array<{product:StoreProduct;quantity:number}>)=>{if(typeof window!=='undefined')localStorage.setItem('sb1_cart',JSON.stringify(cart));};
