type Provider='telegram'|'whatsapp'|'facebook'|'instagram';
type Payload={title:string;body:string;media_url?:string;providers?:Provider[]};
const json=(res:any,b:any,s=200)=>{res.statusCode=s;res.setHeader('content-type','application/json');res.end(JSON.stringify(b));};

async function rewriteForMarketing(p:Payload){const prompt=`أعد صياغة هذا المحتوى كمنشور تسويقي طبي قصير ومحايد لمنصة SB1. لا تضف حقائق طبية جديدة ولا تشخيصاً ولا وعوداً. العنوان: ${p.title}\nالمحتوى: ${p.body}`;if(process.env.GEMINI_API_KEY){const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})});if(r.ok){const d=await r.json();const t=d?.candidates?.[0]?.content?.parts?.[0]?.text;if(t)return {...p,title:p.title,body:t}}}if(process.env.OPENROUTER_API_KEY){const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||'openrouter/free',messages:[{role:'user',content:prompt}]})});if(r.ok){const d=await r.json();const t=d?.choices?.[0]?.message?.content;if(t)return {...p,body:t}}}return p}
async function telegram(p:Payload){const token=process.env.TELEGRAM_BOT_TOKEN,chat=process.env.TELEGRAM_CHAT_ID;if(!token||!chat)throw new Error('Telegram credentials missing');const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chat,text:`<b>${p.title}</b>\n\n${p.body}`,parse_mode:'HTML'})});if(!r.ok)throw new Error('Telegram publish failed');}
async function whatsapp(p:Payload){const token=process.env.WHATSAPP_ACCESS_TOKEN,phone=process.env.WHATSAPP_PHONE_NUMBER_ID,to=process.env.WHATSAPP_BROADCAST_TO;if(!token||!phone||!to)throw new Error('WhatsApp credentials missing');const r=await fetch(`https://graph.facebook.com/v23.0/${phone}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:`${p.title}\n\n${p.body}`}})});if(!r.ok)throw new Error('WhatsApp publish failed');}
async function facebook(p:Payload){const token=process.env.FACEBOOK_PAGE_ACCESS_TOKEN,page=process.env.FACEBOOK_PAGE_ID;if(!token||!page)throw new Error('Facebook credentials missing');const r=await fetch(`https://graph.facebook.com/v23.0/${page}/feed`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({message:`${p.title}\n\n${p.body}`,access_token:token})});if(!r.ok)throw new Error('Facebook publish failed');}
async function instagram(p:Payload){const token=process.env.INSTAGRAM_ACCESS_TOKEN,user=process.env.INSTAGRAM_BUSINESS_ACCOUNT_ID;if(!token||!user||!p.media_url)throw new Error('Instagram requires business account, token and media_url');const c=await fetch(`https://graph.facebook.com/v23.0/${user}/media`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({image_url:p.media_url,caption:`${p.title}\n\n${p.body}`,access_token:token})});const cj=await c.json();if(!c.ok||!cj.id)throw new Error('Instagram media creation failed');const r=await fetch(`https://graph.facebook.com/v23.0/${user}/media_publish`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({creation_id:cj.id,access_token:token})});if(!r.ok)throw new Error('Instagram publish failed');}
export default async function handler(req:any,res:any){if(req.method!=='POST')return json(res,{error:'Method not allowed'},405);const secret=process.env.MARKETING_AUTOMATION_SECRET;if(secret&&req.headers.authorization!==`Bearer ${secret}`)return json(res,{error:'Unauthorized'},401);try{const b=(typeof req.body==='string'?JSON.parse(req.body):req.body||{}) as Payload;if(!b.title||!b.body)return json(res,{error:'title and body required'},400);const rewritten=await rewriteForMarketing(b);const providers=b.providers||['telegram','whatsapp','facebook','instagram'];const results:any[]=[];for(const p of providers){try{if(p==='telegram')await telegram(rewritten);if(p==='whatsapp')await whatsapp(rewritten);if(p==='facebook')await facebook(rewritten);if(p==='instagram')await instagram(rewritten);results.push({provider:p,status:'sent'})}catch(e){results.push({provider:p,status:'error',error:e instanceof Error?e.message:'failed'})}}return json(res,{ok:true,results});}catch(e){return json(res,{error:e instanceof Error?e.message:'failed'},500)}}
