import { BookOpen, Clock3, GraduationCap, MessageCircle, PlayCircle, Search, Star, Users, Video, Layers3 } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useRouter } from '@/lib/router';
import { lt } from '@/lib/featureText';

const tracks = [
  { title: {ar:'تحليل السلوك التطبيقي (ABA)',ru:'Прикладной анализ поведения (ABA)',en:'Applied Behavior Analysis (ABA)',de:'Angewandte Verhaltensanalyse (ABA)'}, weeks: 12, color: 'from-teal-500 to-cyan-600', icon: Layers3 },
  { title: {ar:'العلاج السلوكي المعرفي (CBT)',ru:'Когнитивно-поведенческая терапия (КПТ)',en:'Cognitive Behavioral Therapy (CBT)',de:'Kognitive Verhaltenstherapie (CBT)'}, weeks: 16, color: 'from-violet-500 to-indigo-600', icon: GraduationCap },
  { title: {ar:'علم النفس العصبي',ru:'Нейропсихология',en:'Neuropsychology',de:'Neuropsychologie'}, weeks: 24, color: 'from-amber-500 to-orange-600', icon: BrainIcon },
  { title: {ar:'منهج شامل للتوحد',ru:'Комплексная программа по аутизму',en:'Comprehensive Autism Program',de:'Komplettprogramm Autismus'}, weeks: 48, color: 'from-emerald-500 to-green-600', icon: Users },
  { title: {ar:'العلاج بالفن والدراما',ru:'Арт- и драматерапия',en:'Art & Drama Therapy',de:'Kunst- und Dramatherapie'}, weeks: 10, color: 'from-rose-500 to-pink-600', icon: PlayCircle },
  { title: {ar:'الجشتالت والعلاج النفسي',ru:'Гештальт и психотерапия',en:'Gestalt & Psychotherapy',de:'Gestalt & Psychotherapie'}, weeks: 20, color: 'from-sky-500 to-blue-600', icon: MessageCircle },
];
function BrainIcon({className}:{className?:string}){ return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9.5 5.5A3.5 3.5 0 0 1 16 4a3 3 0 0 1 3 3.1 3.2 3.2 0 0 1 1 6.2 3.4 3.4 0 0 1-2.8 5.2H9.5A4.5 4.5 0 0 1 8 9.1 3.5 3.5 0 0 1 9.5 5.5Z"/><path d="M12 7v10M8.5 11H12M12 14h3.5"/></svg>;}

export default function AcademyPage() {
  const { lang } = useI18n();
  const { navigate } = useRouter();
  return <div className="min-h-screen pt-24 pb-16 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div className="rounded-3xl bg-gradient-to-br from-slate-900 to-teal-900 p-8 md:p-10 text-white shadow-xl"><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6"><div><span className="inline-flex gap-2 items-center rounded-full bg-white/10 px-3 py-1 text-sm"><GraduationCap className="w-4 h-4"/>{lt(lang,{ar:'أكاديمية SB1',ru:'Академия SB1',en:'SB1 Academy',de:'SB1 Akademie'})}</span><h1 className="mt-4 text-3xl md:text-4xl font-extrabold">{lt(lang,{ar:'التعليم المهني المتدرج',ru:'Профессиональное обучение по уровням',en:'Structured professional learning',de:'Strukturiertes professionelles Lernen'})}</h1><p className="mt-2 max-w-2xl text-slate-300">{lt(lang,{ar:'برامج من أسبوعين حتى سنتين مع فيديوهات وكتب واختبارات وخطة دراسة قابلة للتعديل.',ru:'Программы от 2 недель до 2 лет с видео, книгами, тестами и гибким учебным планом.',en:'Programs from 2 weeks to 2 years with videos, books, tests and flexible study plans.',de:'Programme von 2 Wochen bis 2 Jahren mit Videos, Büchern, Tests und flexiblem Lernplan.'})}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => navigate('/courses')} className="rounded-xl bg-white px-5 py-3 font-bold text-slate-900 hover:bg-teal-50">{lt(lang,{ar:'عرض الكورسات',ru:'Курсы',en:'Browse courses',de:'Kurse ansehen'})}</button><button onClick={() => navigate('/consult')} className="rounded-xl bg-teal-500/20 border border-white/20 px-5 py-3 font-bold text-white hover:bg-teal-500/30">{lt(lang,{ar:'الانتقال إلى الاستشارات الطبية',ru:'Перейти к медицинским консультациям',en:'Go to Medical Consultations',de:'Zu medizinischen Beratungen'})}</button></div></div></div>
    <div className="mt-7 flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-[260px]"><Search className="absolute right-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/><input className="w-full rounded-2xl border border-gray-200 bg-white py-3.5 pr-11 pl-4 outline-none focus:border-teal-400" placeholder={lt(lang,{ar:'ابحث عن تخصص أو كورس...',ru:'Поиск направления или курса...',en:'Search a specialty or course...',de:'Fachgebiet oder Kurs suchen...'})}/></div><button onClick={() => navigate('/community')} className="btn-secondary"><MessageCircle className="w-4 h-4"/>{lt(lang,{ar:'مجتمع المتعلمين',ru:'Сообщество',en:'Learner community',de:'Lerner-Community'})}</button></div>
    <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{tracks.map((track) => <article key={track.weeks + track.title.ru} className="overflow-hidden rounded-3xl bg-white border border-gray-100 shadow-sm hover:shadow-lg transition"><div className={`h-28 bg-gradient-to-br ${track.color} p-5 text-white flex items-start justify-between`}><track.icon className="w-8 h-8"/><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-semibold">{Math.round(track.weeks/4.345)} {lt(lang,{ar:'أشهر',ru:'мес.',en:'mo.',de:'Monate'})}</span></div><div className="p-5"><h2 className="font-bold text-gray-800 text-lg leading-snug">{lt(lang,track.title)}</h2><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-gray-500"><span><Clock3 className="inline w-4 h-4 ml-1 text-teal-500"/>{track.weeks} {lt(lang,{ar:'أسبوع',ru:'недель',en:'weeks',de:'Wochen'})}</span><span><Video className="inline w-4 h-4 ml-1 text-teal-500"/>{lt(lang,{ar:'دروس فيديو',ru:'Видеоуроки',en:'Video lessons',de:'Videokurse'})}</span><span><BookOpen className="inline w-4 h-4 ml-1 text-teal-500"/>{lt(lang,{ar:'مكتبة',ru:'Библиотека',en:'Library',de:'Bibliothek'})}</span><span><Star className="inline w-4 h-4 ml-1 text-amber-400 fill-amber-400"/>4.9</span></div><button onClick={() => navigate('/courses')} className="mt-5 w-full rounded-xl bg-teal-600 py-3 font-semibold text-white hover:bg-teal-700">{lt(lang,{ar:'فتح المنهج',ru:'Открыть программу',en:'Open curriculum',de:'Curriculum öffnen'})}</button></div></article>)}</div>
  </div></div>;
}
