import {useEffect,useMemo,useState} from 'react';
import {Calendar,Clock,Video,CheckCircle2,UserRound,CreditCard,ShieldCheck} from 'lucide-react';
import {useRouter,parseQuery} from '@/lib/router';
import {useI18n} from '@/lib/i18n';
import {supabase} from '@/lib/supabase';
import {specialtyCatalog,virtualDoctorsForSpecialty} from '@/lib/catalog';
import {getAppointments,requestAppointment,requestBrowserNotifications} from '@/lib/appointments';
import {getSessionOptions,formatDuration,sessionPrice} from '@/lib/appointmentConfig';

export default function AppointmentBookingPage(){
 const {path,navigate}=useRouter();const q=parseQuery(path);const {lang,dir}=useI18n();const specs=useMemo(()=>specialtyCatalog(lang),[lang]);
 const [doctor,setDoctor]=useState<any>(null);const [patient,setPatient]=useState('');const [selectedSlot,setSelectedSlot]=useState('');const [custom,setCustom]=useState('');const [duration,setDuration]=useState(60);const [paid,setPaid]=useState(false);const [done,setDone]=useState(false);
 useEffect(()=>{requestBrowserNotifications();const load=async()=>{let d:any=null;if(q.doctor){try{const r=await supabase.from('doctors').select('*, specialty(*)').eq('id',q.doctor).single();d=r.data}catch{}}if(!d&&q.specialty)d=virtualDoctorsForSpecialty(q.specialty,lang,1)[0];if(!d)d=virtualDoctorsForSpecialty(specs[0]?.slug||'',lang,1)[0];setDoctor(d)},[]);load()},[q.doctor,q.specialty,lang,specs]);
 useEffect(()=>{if(q.paid!=='1'||!q.ref)return;const draft=localStorage.getItem('sb1_pending_appointment_'+q.ref);if(!draft)return;try{const d=JSON.parse(draft);const existing=getAppointments().find(a=>a.paymentReference===q.ref);if(!existing){requestAppointment({...d,paymentStatus:'paid',paymentReference:q.ref});}localStorage.removeItem('sb1_pending_appointment_'+q.ref);setPaid(true);setDone(true);}catch{}},[q.paid,q.ref]);
 const options=useMemo(()=>doctor?getSessionOptions(doctor.id):[],[doctor]);
 const slots=useMemo(()=>{const out:string[]=[];for(let day=1;day<=10;day++){for(const h of [10,12,14,16,18,20]){const d=new Date();d.setDate(d.getDate()+day);d.setHours(h,0,0,0);out.push(d.toISOString())}}return out},[]);
 const price=doctor?sessionPrice(doctor.id,duration):0;const existing=getAppointments().filter(a=>a.doctorId===doctor?.id&&a.status==='accepted').map(a=>a.scheduledAt);
 const startPayment=()=>{const at=custom||selectedSlot;if(!doctor||!patient.trim()||!at||!price)return;const ref='aptpay-'+Date.now();const draft={doctorId:doctor.id,doctorName:doctor.name,doctorPhoto:doctor.photo_url,specialty:doctor.specialty?.name||specs.find(s=>s.slug===q.specialty)?.name||'',specialtySlug:q.specialty||doctor.specialty?.slug||'',patientName:patient.trim(),patientId:'demo-patient',requestedAt:new Date().toISOString(),scheduledAt:at,requestedTimeText:custom?'موعد اقترحه المريض':new Date(at).toLocaleString(),durationMinutes:duration,price,currency:'USD',mode:'video'};localStorage.setItem('sb1_pending_appointment_'+ref,JSON.stringify(draft));navigate('/payments?type=appointment&reference='+encodeURIComponent(ref)+'&amount='+price+'&currency=usd');};
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-24"><div className="mx-auto max-w-5xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-700 p-7 text-white"><p className="text-sm opacity-80">SB1 · حجز جلسة فيديو</p><h1 className="mt-1 text-3xl font-extrabold">حجز جلسة مع {doctor?.name||'الأخصائي'}</h1><p className="mt-2 opacity-90">يتم الدفع أولاً، ثم يرسل طلب الحجز إلى الأخصائي.</p></div>
 {doctor&&<div className="mt-5 rounded-2xl border bg-white p-5"><div className="flex items-center gap-4"><img src={doctor.photo_url} className="h-20 w-20 rounded-2xl object-cover"/><div><h2 className="text-xl font-extrabold">{doctor.name}</h2><p className="text-teal-700">{doctor.specialty?.name||''}</p><p className="text-sm text-gray-500">{doctor.city||''}</p></div></div></div>}
 {done?<div className="mt-5 rounded-2xl border bg-white p-10 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-green-500"/><h2 className="mt-4 text-2xl font-extrabold">تم الدفع وإرسال حجز الجلسة</h2><p className="mt-2 text-gray-500">يمكنك متابعة الموعد وتغييره حسب قواعد SB1.</p><a href="/appointments" className="mt-6 inline-block rounded-xl bg-teal-600 px-6 py-3 font-bold text-white">متابعة الجلسات</a></div>:
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-extrabold">المواعيد المتاحة</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{slots.map(s=><button key={s} disabled={existing.includes(s)} onClick={()=>{setSelectedSlot(s);setCustom('')}} className={'rounded-xl border p-3 text-start '+(selectedSlot===s?'border-teal-500 bg-teal-50':'hover:bg-gray-50')+(existing.includes(s)?' opacity-40':'')}><Calendar className="inline h-4 w-4 text-teal-600"/> {new Date(s).toLocaleString()}</button>)}</div><div className="mt-6 border-t pt-5"><label className="font-bold">أو اكتب الموعد المناسب</label><input type="datetime-local" value={custom} onChange={e=>{setCustom(e.target.value);setSelectedSlot('')}} className="mt-2 w-full rounded-xl border p-3"/></div></div>
 <div className="rounded-2xl border bg-white p-6"><h2 className="font-extrabold">مدة وسعر الجلسة</h2><div className="mt-4 grid gap-2">{options.map(o=><button key={o.durationMinutes} onClick={()=>setDuration(o.durationMinutes)} className={'rounded-xl border p-3 text-start '+(duration===o.durationMinutes?'border-teal-500 bg-teal-50':'')}>{formatDuration(o.durationMinutes,lang)} <b className="float-end">{o.price} USD</b></button>)}</div><label className="mt-5 block text-sm font-bold">اسم العميل<input value={patient} onChange={e=>setPatient(e.target.value)} className="mt-2 w-full rounded-xl border p-3" placeholder="اكتب الاسم"/></label><div className="mt-4 rounded-2xl bg-gray-50 p-4 text-sm"><UserRound className="inline h-4 w-4"/> {doctor?.name}<br/><Clock className="inline h-4 w-4 mt-2"/> {custom?new Date(custom).toLocaleString():selectedSlot?new Date(selectedSlot).toLocaleString():'لم تختَر موعداً'}<br/><Video className="inline h-4 w-4 mt-2"/> {formatDuration(duration,lang)} — {price} USD</div><div className="mt-4 rounded-xl bg-blue-50 p-3 text-xs text-blue-800"><ShieldCheck className="inline h-4 w-4"/> الدفع مطلوب قبل إرسال الطلب. في وضع الاختبار لا يتم خصم أموال حقيقية.</div><button onClick={startPayment} disabled={!patient.trim()||(!custom&&!selectedSlot)||!price} className="mt-5 w-full rounded-xl bg-teal-600 py-3 font-bold text-white disabled:opacity-40"><CreditCard className="inline h-4 w-4"/> الدفع ثم إرسال الطلب — {price} USD</button></div></div>}
 </div></div>
}