import { useMemo,useState } from 'react';
import { Gamepad2,Smartphone,Brain,Calculator,Download,Search,ExternalLink } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
const realResources=[
 {name:'MedikQuantis — 49 clinical calculators',url:'https://github.com/laurapiro17/medikquantis',kind:'calculators'},
 {name:'Simple — free hypertension & diabetes app',url:'https://www.simple.org/',kind:'apps'},
 {name:'Ygeia — free open-source health tracker',url:'https://github.com/falakiwastaken/ygeia',kind:'apps'},
 {name:'Rianell — open-source health tracker',url:'https://rianell.com/features/',kind:'apps'},
 {name:'MindWell — open-source mental health tools',url:'https://github.com/rudra496/mindwell',kind:'mental'}
];
const kinds:any={ar:{calculators:'حاسبات طبية',tests:'اختبارات',games:'ألعاب ذاكرة',apps:'تطبيقات صحية',education:'تعليم طبي'},en:{calculators:'Medical calculators',tests:'Screening tests',games:'Memory games',apps:'Health apps',education:'Medical education'}};
export default function AppsPage(){const {lang,dir}=useI18n();const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const l=kinds[lang]||kinds.en;
 const items=useMemo(()=>{const groups=[['calculators',l.calculators,Calculator,35],['tests',l.tests,Brain,30],['games',l.games,Gamepad2,20],['apps',l.apps,Smartphone,20],['education',l.education,Brain,15]] as any[];return groups.flatMap(([kind,label,Icon,n])=>Array.from({length:n},(_,i)=>({id:kind+'-'+(i+1),kind,label,Icon,title:(lang==='ar'?label:label)+' '+(i+1),description:lang==='ar'?'أداة مجانية تجريبية داخل SB1 للاستخدام والتعلم.':'Free SB1 demo tool for learning and practice.'})));},[lang,l.calculators,l.tests,l.games,l.apps,l.education]);
 const shown=items.filter(x=>(filter==='all'||x.kind===filter)&&x.title.toLowerCase().includes(search.toLowerCase()));
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir={dir}><div className="mx-auto max-w-7xl px-4"><div className="rounded-3xl bg-gradient-to-br from-purple-700 to-indigo-600 p-8 text-white"><h1 className="text-3xl font-extrabold">{lang==='ar'?'الألعاب والتطبيقات والأدوات':'Games, Apps & Tools'}</h1><p className="mt-2">{lang==='ar'?'أكثر من 100 أداة مجانية مع روابط لمشاريع مفتوحة المصدر حقيقية.':'120 free SB1 tools plus links to real open-source projects.'}</p></div>
 <div className="mt-6 rounded-2xl bg-white border p-5"><div className="flex gap-3 flex-wrap"><div className="relative flex-1 min-w-[220px]"><Search className="absolute start-3 top-3 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={lang==='ar'?'ابحث عن أداة...':'Search a tool...'} className="input-field ps-10"/></div>{[['all',lang==='ar'?'الكل':'All'],['calculators',l.calculators],['tests',l.tests],['games',l.games],['apps',l.apps],['education',l.education]].map(x=><button key={x[0]} onClick={()=>setFilter(x[0])} className={'rounded-xl px-4 py-2 font-bold '+(filter===x[0]?'bg-indigo-600 text-white':'bg-gray-100 text-gray-700')}>{x[1]}</button>)}</div></div>
 <section className="mt-6"><h2 className="text-xl font-extrabold mb-4">{lang==='ar'?'مشاريع وتطبيقات حقيقية مجانية':'Real free open-source resources'}</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{realResources.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer" className="rounded-2xl bg-white border p-5 hover:border-indigo-300"><ExternalLink className="h-6 w-6 text-indigo-600"/><h3 className="font-bold mt-3">{x.name}</h3><p className="text-xs text-gray-500 mt-2">{lang==='ar'?'مصدر خارجي مجاني/مفتوح المصدر':'Free/open-source external resource'}</p></a>)}</div></section>
 <section className="mt-8"><div className="flex items-center justify-between mb-4"><h2 className="text-xl font-extrabold">{lang==='ar'?'أدوات SB1 المجانية':'SB1 free tools'}</h2><span className="badge bg-indigo-50 text-indigo-700">{shown.length} / 120</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{shown.map(x=>{const Icon=x.Icon;return <div key={x.id} className="bg-white border rounded-2xl p-5"><Icon className="h-8 w-8 text-indigo-600"/><h3 className="font-bold mt-3">{x.title}</h3><p className="text-xs text-gray-500 mt-2">{x.description}</p><button onClick={()=>{localStorage.setItem('sb1_tool_opened',x.id)}} className="mt-4 rounded-xl bg-indigo-50 text-indigo-700 px-4 py-2 font-bold flex items-center gap-2"><Download className="h-4 w-4"/>{lang==='ar'?'فتح الأداة':'Open tool'}</button></div>})}</div></section>
 </div></div>;
}