import { Bot, ClipboardList, GraduationCap, ShieldCheck, Sparkles, Send } from 'lucide-react';
import { useState } from 'react';
import { useI18n } from '@/lib/i18n';
import { lt } from '@/lib/featureText';

const modes = [
  { key:'student', icon:GraduationCap, title:{ar:'مساعد الطالب',ru:'Помощник студента',en:'Student Assistant',de:'Studenten-Assistent'}, desc:{ar:'تلخيص الدروس، خطة الدراسة، التحضير للاختبارات والبحث داخل المكتبة.',ru:'Конспекты, учебный план, подготовка к тестам и поиск в библиотеке.',en:'Summaries, study plans, exam prep and library search.',de:'Zusammenfassungen, Lernplan, Prüfungsvorbereitung und Bibliothekssuche.'}},
  { key:'teacher', icon:Sparkles, title:{ar:'مساعد المدرّس',ru:'Помощник преподавателя',en:'Teacher Assistant',de:'Dozenten-Assistent'}, desc:{ar:'إنشاء دروس، أسئلة، واجبات، تقييمات وأفكار لأنشطة الفصل.',ru:'Создание уроков, вопросов, заданий и идей для занятий.',en:'Create lessons, questions, assignments and class activities.',de:'Lektionen, Fragen, Aufgaben und Unterrichtsaktivitäten erstellen.'}},
  { key:'admin', icon:ShieldCheck, title:{ar:'مساعد الإدارة',ru:'Помощник администратора',en:'Admin Assistant',de:'Admin-Assistent'}, desc:{ar:'متابعة المنصة، التقارير، المحتوى، المستخدمين والتنبيهات.',ru:'Мониторинг платформы, отчёты, контент, пользователи и уведомления.',en:'Platform monitoring, reports, content, users and alerts.',de:'Plattformüberwachung, Berichte, Inhalte, Nutzer und Warnungen.'}},
];

export default function AssistantsPage(){ const {lang}=useI18n(); const [mode,setMode]=useState('student'); const [messages,setMessages]=useState<string[]>([]); const [input,setInput]=useState(''); const current=modes.find(x=>x.key===mode)!;
 const send=()=>{if(!input.trim())return;setMessages(m=>[...m,input.trim()]);setInput('');};
 return <div className="min-h-screen pt-24 pb-16 bg-gray-50"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center"><Bot className="mx-auto w-12 h-12 text-teal-600"/><h1 className="mt-4 text-3xl font-extrabold text-gray-800">{lt(lang,{ar:'مساعدو SB1 الذكيون',ru:'Умные помощники SB1',en:'SB1 Smart Assistants',de:'SB1 Smart Assistants'})}</h1><p className="mt-2 text-gray-500">{lt(lang,{ar:'ثلاثة أوضاع منفصلة حسب دور المستخدم.',ru:'Три режима для разных ролей пользователей.',en:'Three modes for different user roles.',de:'Drei Modi für unterschiedliche Nutzerrollen.'})}</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{modes.map(m=><button key={m.key} onClick={()=>{setMode(m.key);setMessages([])}} className={`card p-5 text-right transition ${mode===m.key?'ring-2 ring-teal-500 bg-teal-50/40':''}`}><m.icon className="w-7 h-7 text-teal-600"/><h2 className="mt-3 font-bold text-gray-800">{lt(lang,m.title)}</h2><p className="mt-1 text-sm text-gray-500">{lt(lang,m.desc)}</p></button>)}</div><div className="mt-7 overflow-hidden rounded-3xl bg-white border"><div className="bg-gradient-to-r from-teal-700 to-cyan-700 p-6 text-white"><div className="flex items-center gap-3"><current.icon className="w-8 h-8"/><div><h2 className="text-xl font-bold">{lt(lang,current.title)}</h2><p className="text-sm text-teal-100">{lt(lang,current.desc)}</p></div></div></div><div className="min-h-[300px] p-6 bg-gray-50">{messages.length===0?<div className="h-[240px] flex flex-col items-center justify-center text-center text-gray-400"><ClipboardList className="w-10 h-10 mb-3"/><p>{lt(lang,{ar:'اكتب سؤالك أو المهمة التي تريد من المساعد تنفيذها.',ru:'Напишите вопрос или задачу для помощника.',en:'Write a question or task for the assistant.',de:'Schreiben Sie eine Frage oder Aufgabe.'})}</p></div>:<div className="space-y-3">{messages.map((m,i)=><div key={i} className="rounded-2xl bg-white p-4 shadow-sm"><div className="text-xs text-teal-600 font-semibold mb-1">{lt(lang,current.title)}</div>{m}</div>)}</div>}</div><div className="border-t p-4 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} className="input-field flex-1" placeholder={lt(lang,{ar:'اكتب المهمة...',ru:'Введите задачу...',en:'Enter a task...',de:'Aufgabe eingeben...'})}/><button onClick={send} className="btn-primary"><Send className="w-4 h-4"/>{lt(lang,{ar:'إرسال',ru:'Отправить',en:'Send',de:'Senden'})}</button></div></div></div></div>;
}
