import {useEffect,useMemo,useState} from 'react';
import {BellRing,MapPin,Users,Clock3,MousePointerClick,ShoppingBag,Send} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {useApp} from '@/i18n/AppContext';
import {citiesForCountry} from '@/lib/catalog';
import {getCityAudienceStats,launchCityCampaign,campaignQuote} from '@/lib/cityNotificationAds';
export default function CityNotificationAdsPage(){
 const {lang,dir}=useI18n();const {country}=useApp();const [city,setCity]=useState('');const [duration,setDuration]=useState(1);const [count,setCount]=useState(0);const [title,setTitle]=useState('');const [body,setBody]=useState('');const [stats,setStats]=useState({total:0,active:0,inactive:0});const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);
 const cities=useMemo(()=>citiesForCountry(country.code,lang),[country.code,lang]);
 useEffect(()=>{if(cities[0])setCity(cities[0].key)},[cities.map(x=>x.key).join('|')]);
 useEffect(()=>{if(!city)return;getCityAudienceStats(country.code,city).then(s=>{setStats(s);setCount(s.total)})},[country.code,city]);
 const quote=campaignQuote({durationDays:duration,recipients:count,daily:5,perRecipient:.01,perOpen:.08,perPurchase:1});
 const send=async()=>{setBusy(true);setResult(null);try{const r=await launchCityCampaign({advertiser_user_id:localStorage.getItem('sb1_account_user_id')||null,advertiser_role:localStorage.getItem('sb1_account_role')||'institution',title:title||'إعلان SB1',body:body||'اكتشف خدمتنا الجديدة على SB1',destination_url:'/facilities',country_code:country.code,city,audience_mode:'all_registered',duration_days:duration,price_per_recipient:.01,price_per_open:.08,price_per_purchase:1});setResult(r)}catch(e){setResult({error:String(e)})}finally{setBusy(false)}};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-indigo-700 via-blue-700 to-cyan-600 p-8 text-white"><div className="flex items-center gap-3"><BellRing/><div><h1 className="text-3xl font-black">{lang==='ar'?'إعلانات الإشعارات حسب المدينة':'City Notification Advertising'}</h1><p className="mt-2 text-white/85">إرسال الإعلان لكل المسجلين في المدينة، وليس للعملاء فقط.</p></div></div></div>
 <div className="mt-6 grid gap-4 md:grid-cols-4"><div className="rounded-2xl bg-white border p-5"><Users className="text-indigo-600"/><b className="mt-3 block text-2xl">{stats.total}</b><span className="text-sm text-gray-500">كل المسجلين</span></div><div className="rounded-2xl bg-white border p-5"><div className="text-green-600 font-bold">● نشط</div><b className="mt-3 block text-2xl">{stats.active}</b><span className="text-sm text-gray-500">نشط خلال {30} يوماً</span></div><div className="rounded-2xl bg-white border p-5"><div className="text-gray-400 font-bold">● غير نشط</div><b className="mt-3 block text-2xl">{stats.inactive}</b><span className="text-sm text-gray-500">غير نشط</span></div><div className="rounded-2xl bg-white border p-5"><MapPin className="text-rose-600"/><b className="mt-3 block">{city||'—'}</b><span className="text-sm text-gray-500">{country.nameKey||country.code}</span></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">إنشاء حملة</h2><p className="mt-1 text-sm text-gray-500">الجمهور الأساسي: جميع الحسابات المسجلة في المدينة، بما فيها العملاء والأخصائيون والمؤسسات.</p><div className="grid gap-4 mt-5 md:grid-cols-2"><label>الدولة<input readOnly value={country.code} className="input-field mt-1"/></label><label>المدينة<select value={city} onChange={e=>setCity(e.target.value)} className="input-field mt-1">{cities.map(x=><option key={x.key} value={x.key}>{x.name}</option>)}</select></label><label>عدد المستلمين<input type="number" min="1" max={stats.total||1} value={count} onChange={e=>setCount(Math.min(stats.total||1,Math.max(1,Number(e.target.value)||1)))} className="input-field mt-1"/></label><label>مدة الحملة<select value={duration} onChange={e=>setDuration(Number(e.target.value))} className="input-field mt-1">{[1,3,7,14,30].map(x=><option key={x} value={x}>{x} يوم</option>)}</select></label></div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان الإعلان" className="input-field w-full mt-4"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="نص الإشعار" className="input-field w-full mt-3 min-h-28"/><button disabled={busy||!stats.total} onClick={send} className="mt-4 rounded-xl bg-indigo-700 px-6 py-3 font-bold text-white disabled:opacity-50"><Send className="inline h-4 w-4 me-2"/>{busy?'جارٍ إنشاء الحملة…':'إرسال الحملة لكل الجمهور المحدد'}</button>{result&&<pre className="mt-4 rounded-xl bg-slate-50 p-4 text-xs overflow-auto">{JSON.stringify(result,null,2)}</pre>}</section>
 <aside className="space-y-4"><div className="rounded-3xl bg-white border p-6"><h2 className="font-extrabold">تسعير الحملة</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span><Clock3 className="inline h-4 w-4 me-1"/>المدة</span><b>{quote.fixed.toFixed(2)} USD</b></div><div className="flex justify-between"><span><Users className="inline h-4 w-4 me-1"/>عدد الإرسال</span><b>{quote.send.toFixed(2)} USD</b></div><div className="flex justify-between"><span><MousePointerClick className="inline h-4 w-4 me-1"/>كل فتح</span><b>0.08 USD</b></div><div className="flex justify-between"><span><ShoppingBag className="inline h-4 w-4 me-1"/>كل شراء من الحملة</span><b>1.00 USD</b></div></div><div className="mt-5 rounded-2xl bg-indigo-50 p-4"><span className="text-sm text-indigo-700">الجزء الثابت قبل الفتح والشراء</span><b className="block text-2xl text-indigo-900">{quote.totalBase.toFixed(2)} USD</b></div><p className="mt-3 text-xs text-gray-500">الأسعار الحالية تجريبية وقابلة لتعديل المالك. النظام يسجل الإرسال والفتح والضغط والشراء ليحسب التكلفة الفعلية.</p></div><div className="rounded-3xl bg-white border p-6"><h2 className="font-extrabold">القياس</h2><ul className="mt-3 space-y-2 text-sm text-gray-600"><li>✓ عدد المسجلين الحقيقي من بيانات التسجيل والمدينة.</li><li>✓ نشط/غير نشط بناءً على آخر ظهور.</li><li>✓ إرسال لجميع الأدوار، وليس العملاء فقط.</li><li>✓ تسجيل فتح الإشعار.</li><li>✓ تسجيل دخول المؤسسة من الإعلان.</li><li>✓ إسناد الشراء للحملة عند إتمام الخدمة.</li></ul></div></aside></div></div></div>}
