import {useEffect,useState} from 'react';
import {Bookmark,Heart,MessageCircle,Archive,RotateCcw,Users,ShieldCheck,LockKeyhole,Trash2} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {getSaved,getLiked,getArchived,getComments,getFollowing,restoreItem,toggleSaved,setProfilePrivacy,getProfilePrivacy,type VaultItem} from '@/lib/socialVault';
export default function ClientDashboardPage(){const {lang,dir}=useI18n();const [tab,setTab]=useState('saved');const [saved,setSaved]=useState<VaultItem[]>([]);const [liked,setLiked]=useState<VaultItem[]>([]);const [archived,setArchived]=useState<VaultItem[]>([]);const [comments,setComments]=useState<Record<string,string[]>>({});const [following,setFollowing]=useState<string[]>([]);const [privacy,setPrivacy]=useState(getProfilePrivacy());
 const refresh=()=>{setSaved(getSaved());setLiked(getLiked());setArchived(getArchived());setComments(getComments());setFollowing(getFollowing())};useEffect(()=>{refresh();window.addEventListener('sb1-social-change',refresh);return()=>window.removeEventListener('sb1-social-change',refresh)},[]);
 const restore=(id:string)=>{restoreItem(id);refresh()};const tabs=[['saved','المحفوظات',Bookmark],['liked','الإعجابات',Heart],['comments','تعليقاتي',MessageCircle],['following','المتابَعون',Users],['archive','الأرشيف الخاص',Archive]];
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-gradient-to-br from-slate-900 via-indigo-800 to-teal-700 p-7 text-white"><h1 className="text-3xl font-black">{lang==='ar'?'لوحة العميل والزائر':'Client & Visitor Dashboard'}</h1><p className="mt-2 text-white/75">المحفوظات، الإعجابات، التعليقات، المتابعة والأرشيف الخاص.</p><div className="mt-5 flex flex-wrap gap-3"><span className="rounded-xl bg-white/10 px-4 py-2"><Bookmark className="inline h-4 w-4"/> {saved.length} محفوظ</span><span className="rounded-xl bg-white/10 px-4 py-2"><Heart className="inline h-4 w-4"/> {liked.length} إعجاب</span><span className="rounded-xl bg-white/10 px-4 py-2"><Users className="inline h-4 w-4"/> {following.length} متابعة</span></div></div>
 <div className="mt-5 rounded-2xl bg-white border p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-teal-600"/><div className="flex-1"><b>خصوصية المحتوى</b><p className="text-sm text-slate-500">المحتوى الشخصي لا يظهر للعامة. وضع المتابعين يسمح بالعرض للمتابعين فقط.</p></div><select value={privacy} onChange={e=>{const v=e.target.value as any;setPrivacy(v);setProfilePrivacy(v)}} className="rounded-xl border px-3 py-2"><option value="followers">المتابعون فقط</option><option value="private">خاص بالكامل</option></select><LockKeyhole className="text-slate-500"/></div></div>
 <div className="mt-5 flex flex-wrap gap-2">{tabs.map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={'rounded-xl px-4 py-3 font-bold '+(tab===k?'bg-teal-700 text-white':'bg-white border text-slate-600') }><I className="inline h-4 w-4 me-1"/>{l}</button>)}</div>
 <div className="mt-5 rounded-2xl bg-white border p-6">{tab==='following'&&<div><h2 className="text-xl font-extrabold mb-4">الأخصائيون الذين أتابعهم</h2>{following.length?<ul className="space-y-2">{following.map(x=><li key={x} className="rounded-xl bg-slate-50 p-4 flex justify-between"><span>{x}</span><a href={'/doctors/'+x} className="text-teal-700 font-bold">فتح الصفحة</a></li>)}</ul>:<p className="text-slate-400">لا توجد متابعات بعد.</p>}</div>}
 {tab==='comments'&&<div><h2 className="text-xl font-extrabold mb-4">تعليقاتي</h2>{Object.keys(comments).length?Object.entries(comments).map(([id,c])=><div key={id} className="mb-3 rounded-xl bg-slate-50 p-4"><b>{id}</b>{c.map((x,i)=><p key={i} className="mt-1 text-slate-600">{x}</p>)}</div>):<p className="text-slate-400">لا توجد تعليقات بعد.</p>}</div>}
 {['saved','liked','archive'].includes(tab)&&<div><h2 className="text-xl font-extrabold mb-4">{tab==='saved'?'المحفوظات':tab==='liked'?'الإعجابات':'الأرشيف الخاص'}</h2><div className="grid gap-3 md:grid-cols-2">{(tab==='saved'?saved:tab==='liked'?liked:archived).map((x:any)=><div key={x.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-start gap-3"><div className="flex-1"><b>{x.title||x.kind}</b><p className="text-sm text-slate-500 mt-1">{x.body}</p><p className="text-xs text-slate-400 mt-2">{x.author}</p></div>{tab==='archive'?<button onClick={()=>restore(x.id)} className="rounded-lg bg-white border px-3 py-2 text-teal-700"><RotateCcw className="inline h-4 w-4"/> استعادة</button>:<button onClick={()=>{toggleSaved(x);refresh()}} className="text-slate-400"><Trash2/></button>}</div></div>)}</div></div>}</div></div></div>}