import {useEffect,useState} from 'react';import {Shield,Lock,Unlock,Save,AlertTriangle} from 'lucide-react';import {supabase} from '@/lib/supabase';
export default function ComplaintsAdminPage(){const [complaints,setComplaints]=useState<any[]>([]);const [sanctions,setSanctions]=useState<any[]>([]);const [rules,setRules]=useState<any[]>([]);const [auth,setAuth]=useState(false);
useEffect(()=>{try{setAuth(!!localStorage.getItem('admin_auth'))}catch{};load()},[]);
async function load(){const [c,s,r]=await Promise.all([supabase.from('complaints').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('provider_sanctions').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('sanction_rules').select('*').order('rule_key')]);setComplaints(c.data||[]);setSanctions(s.data||[]);setRules(r.data||[])}
async function saveRule(r:any){const {id,...payload}=r;await supabase.from('sanction_rules').update({...payload,updated_at:new Date().toISOString()}).eq('id',id);load()}
async function freeze(id:string,freeze:boolean){await supabase.from('provider_wallets').update({is_frozen:freeze,frozen_reason:freeze?'قرار إداري من مركز الشكاوى':'تم رفع التجميد',frozen_at:freeze?new Date().toISOString():null}).eq('provider_id',id);load()}
if(!auth)return <div dir="rtl" className="min-h-screen pt-24 p-6 grid place-items-center"><div className="card p-8 text-center"><Shield className="mx-auto h-12 w-12 text-teal-600"/><h1 className="text-2xl font-bold mt-3">مركز الرقابة والشكاوى</h1><p className="text-gray-500 mt-2">يجب الدخول كمالك أو مشرف من لوحة الإدارة.</p></div></div>;
return <div dir="rtl" className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="max-w-7xl mx-auto px-4"><div className="rounded-3xl bg-slate-900 text-white p-7"><h1 className="text-3xl font-black">الرقابة والجزاءات والشكاوى</h1><p className="mt-2 text-white/70">القواعد المالية والتجميد والحجز والتعويض تعمل آلياً وفق الحدود التي يحددها المالك.</p></div>
<div className="grid md:grid-cols-3 gap-4 mt-6">{[['الشكاوى',complaints.length],['الجزاءات',sanctions.length],['قواعد العقوبات',rules.length]].map(x=><div className="card p-5" key={x[0]}><div className="text-3xl font-black">{x[1]}</div><div className="text-gray-500">{x[0]}</div></div>)}</div>
<div className="card p-6 mt-6"><h2 className="text-xl font-bold mb-4">قواعد المالك</h2><div className="space-y-4">{rules.map(r=><div key={r.id} className="border rounded-2xl p-4"><div className="flex justify-between"><div><b>{r.name}</b><p className="text-xs text-gray-500">{r.description}</p></div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={r.enabled} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,enabled:e.target.checked}:x))}/>تفعيل</label></div><div className="grid grid-cols-2 md:grid-cols-6 gap-3 mt-4"><label className="text-xs">غرامة<input className="input-field mt-1" type="number" value={r.penalty_amount} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,penalty_amount:Number(e.target.value)}:x))}/></label><label className="text-xs">حجز %<input className="input-field mt-1" type="number" max="100" value={r.hold_percent} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,hold_percent:Number(e.target.value)}:x))}/></label><label className="text-xs">تجميد بالساعات<input className="input-field mt-1" type="number" value={r.freeze_hours} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,freeze_hours:Number(e.target.value)}:x))}/></label><label className="text-xs">حد الشكاوى<input className="input-field mt-1" type="number" value={r.complaint_threshold} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,complaint_threshold:Number(e.target.value)}:x))}/></label><label className="text-xs">خصم التعويض %<input className="input-field mt-1" type="number" max="30" value={r.compensation_discount_percent} onChange={e=>setRules(rs=>rs.map(x=>x.id===r.id?{...x,compensation_discount_percent:Math.min(30,Number(e.target.value))}:x))}/></label><button className="btn-primary h-10 mt-4" onClick={()=>saveRule(r)}><Save className="inline h-4 w-4 me-1"/>حفظ</button></div></div>)}</div></div>
<div className="card p-6 mt-6"><h2 className="text-xl font-bold mb-4">الشكاوى الأخيرة</h2>{complaints.map(c=><div className="border-b py-4" key={c.id}><div className="flex justify-between gap-4"><div><b>{c.customer_name||'عميل'}</b><span className="mx-2 text-gray-400">★ {c.rating||'-'}</span><span className="badge bg-gray-100">{c.severity}</span><p className="text-sm mt-1">{c.description}</p><p className="text-xs text-gray-400 mt-1">{c.reason_category} · {c.status}</p></div><div className="text-left"><button className="text-red-600 text-sm" onClick={()=>freeze(c.provider_id,true)}><Lock className="inline h-4 w-4"/> تجميد</button><button className="text-green-600 text-sm ms-3" onClick={()=>freeze(c.provider_id,false)}><Unlock className="inline h-4 w-4"/> رفع التجميد</button></div></div></div>)}{!complaints.length&&<p className="text-gray-400">لا توجد شكاوى مسجلة.</p>}</div>
<div className="card p-6 mt-6"><h2 className="text-xl font-bold mb-4">سجل الجزاءات</h2>{sanctions.map(s=><div className="border-b py-3 flex justify-between" key={s.id}><div><b>{s.sanction_type}</b><p className="text-sm text-gray-500">{s.reason}</p></div><div className="font-bold">{Number(s.amount||0).toFixed(2)} USD {s.freeze_account?'· تجميد':''}</div></div>)}{!sanctions.length&&<p className="text-gray-400">لا توجد جزاءات.</p>}</div>
</div></div>}