import {useEffect,useMemo,useState} from 'react';
import {Heart,Bookmark,Share2,Download,MessageCircle,Eye,Users,Clock,Lock,Play,Headphones,BookOpen,FileText,Send,Maximize2} from 'lucide-react';
import {useI18n} from '@/lib/i18n';import {useRouter,parseQuery} from '@/lib/router';import {supabase} from '@/lib/supabase';import {virtualContentById} from '@/lib/catalog';

type Item=any;
const cover=(x:any)=>x.cover_url||x.thumbnail_url||x.image_url||'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80';
const paidFor=(x:any)=>Boolean(x.is_paid||Number(x.price||0)>0);
export default function ContentDetailPage({id}:{id:string}){const {lang,dir}=useI18n();const {path,navigate}=useRouter();const q=parseQuery(path);const [item,setItem]=useState<Item|null>(null);const [loading,setLoading]=useState(true);const [purchased,setPurchased]=useState(localStorage.getItem('sb1_paid_'+id)==='1'||q.paid==='1');const [liked,setLiked]=useState(localStorage.getItem('sb1_like_'+id)==='1');const [favorite,setFavorite]=useState(localStorage.getItem('sb1_fav_'+id)==='1');const [comments,setComments]=useState<any[]>([]);const [comment,setComment]=useState('');const [message,setMessage]=useState('');
useEffect(()=>{(async()=>{setLoading(true);try{const r=await supabase.from('content_items').select('*').eq('id',id).maybeSingle();if(r.data)setItem(r.data);else{const s=await supabase.from('content_submissions').select('*').eq('id',id).maybeSingle();if(s.data){let url=s.data.file_path||'';let coverUrl=s.data.cover_path||'';if(s.data.file_path){const z=await supabase.storage.from('specialist-content').createSignedUrl(s.data.file_path,3600);url=z.data?.signedUrl||url}if(s.data.cover_path){const z=await supabase.storage.from('specialist-content').createSignedUrl(s.data.cover_path,3600);coverUrl=z.data?.signedUrl||coverUrl}setItem({...s.data,cover_url:coverUrl,file_url:url,is_paid:Number(s.data.price||0)>0,price:s.data.price||0,offer_duration_days:s.data.offer_duration_days||30,buyers_count:s.data.buyers_count||0,views_count:s.data.views||0})}else setItem(virtualContentById(id))} }catch{setItem(virtualContentById(id))}finally{setLoading(false)}})()},[id,lang]);
useEffect(()=>{if(!item)return;supabase.from('content_interactions').select('*').eq('content_item_id',id).eq('interaction_type','comment').order('created_at',{ascending:false}).limit(20).then((r:any)=>{if(r.data?.length)setComments(r.data)}).catch(()=>{const x=JSON.parse(localStorage.getItem('sb1_comments_'+id)||'[]');setComments(x)})},[id,item]);
const isPaid=paidFor(item);const canOpen=!isPaid||purchased;const stats=useMemo(()=>({views:Number(item?.views_count??item?.views??0),likes:Number(item?.likes_count??0),comments:Number(item?.comments_count??comments.length),buyers:Number(item?.buyers_count??item?.enrolled_count??0)}),[item,comments]);
const interaction=async(type:string,body?:string)=>{try{await supabase.from('content_interactions').insert({content_item_id:id,interaction_type:type,body:body||null})}catch{}};
const toggleLike=()=>{const v=!liked;setLiked(v);localStorage.setItem('sb1_like_'+id,v?'1':'0');if(v)interaction('like')};
const toggleFav=()=>{const v=!favorite;setFavorite(v);localStorage.setItem('sb1_fav_'+id,v?'1':'0');if(v)interaction('favorite')};
const share=async()=>{if(isPaid)return;const url=location.href;try{if(navigator.share)await navigator.share({title:item.title,url});else{await navigator.clipboard.writeText(url);setMessage(lang==='ar'?'تم نسخ الرابط':'Link copied')}interaction('share')}catch{}};
const download=()=>{if(!canOpen||isPaid)return;const url=item.file_url||item.video_url||item.audio_url||item.url;if(url){const a=document.createElement('a');a.href=url;a.download=item.title||'SB1-content';a.target='_blank';a.click();interaction('download')}else if(item.body){const blob=new Blob([item.body],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=(item.title||'SB1-article')+'.txt';a.click();URL.revokeObjectURL(u);interaction('download')}};
const publish=()=>{if(isPaid)return;localStorage.setItem('sb1_published_'+id,JSON.stringify(item));interaction('publish');setMessage(lang==='ar'?'تم نشر المحتوى على صفحتك':'Published to your page')};
const buy=async()=>{setMessage('');try{const reference='content-'+id+'-'+Date.now();const res=await fetch('/api/create-checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:Number(item.price||0),currency:String(item.currency_code||'usd').toLowerCase(),description:item.title,reference_id:reference,success_url:location.origin+'/content/'+id+'?paid=1',cancel_url:location.href})});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'checkout unavailable');location.href=data.url}catch(e:any){setMessage(lang==='ar'?'الدفع الإلكتروني غير مفعّل حالياً لهذا المحتوى.':'Online payment is not configured for this content yet.')}}; 
const addComment=async()=>{if(!comment.trim())return;const c={id:'local-'+Date.now(),content_item_id:id,body:comment.trim(),created_at:new Date().toISOString()};setComments(x=>[c,...x]);setComment('');localStorage.setItem('sb1_comments_'+id,JSON.stringify([c,...comments].slice(0,20)));await interaction('comment',c.body)};
if(loading)return <div className="min-h-screen pt-32 text-center">جاري تحميل المحتوى…</div>;if(!item)return <div className="min-h-screen pt-32 text-center"><h1 className="text-2xl font-bold">المحتوى غير موجود</h1></div>;
return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
<div className="grid gap-6 lg:grid-cols-[1fr_320px]"><main className="rounded-3xl bg-white border overflow-hidden">
<div className="relative"><img src={cover(item)} alt={item.title} className="w-full aspect-video object-cover"/>{isPaid&&!canOpen&&<div className="absolute inset-0 bg-black/55 flex items-center justify-center"><div className="rounded-2xl bg-white p-6 text-center max-w-md"><Lock className="mx-auto h-9 w-9 text-teal-700"/><h2 className="mt-3 text-xl font-extrabold">محتوى مدفوع</h2><p className="mt-2 text-sm text-gray-500">ادفع لفتح المحتوى. لا يمكن تنزيل أو مشاركة المحتوى المدفوع.</p><div className="mt-4 font-extrabold text-2xl">{item.price} {item.currency_code||'USD'}</div><p className="text-sm text-gray-500 mt-1">عدد المشترين: {stats.buyers} · مدة العرض: {item.offer_duration_days||30} يوم</p><button onClick={buy} className="mt-5 rounded-xl bg-teal-700 px-6 py-3 text-white font-bold">الدفع وفتح المحتوى</button></div></div>}</div>
{canOpen&&<div className="p-6">{item.content_type==='video'&&<div className="mb-5"><video controls className="w-full rounded-2xl bg-black" src={item.file_url||item.video_url}/></div>}{item.content_type==='audio'&&<div className="mb-5 rounded-2xl bg-gray-50 p-6"><img src={cover(item)} className="w-full max-h-72 object-cover rounded-xl mb-5"/><audio controls className="w-full" src={item.file_url||item.audio_url}/></div>}<div className="flex items-center gap-2 text-xs text-gray-500"><span className="rounded-full bg-teal-50 px-3 py-1">{item.content_type}</span>{item.is_ai_generated&&<span className="rounded-full bg-purple-50 px-3 py-1">AI Editorial</span>}</div><h1 className="mt-4 text-3xl font-extrabold">{item.title}</h1><p className="mt-3 text-gray-600">{item.description||item.excerpt}</p>{item.body&&<div className="prose prose-slate max-w-none mt-6 whitespace-pre-wrap leading-8">{item.body}</div>}</div>}</main>
<aside className="space-y-4">{item.content_type==='video'&&<div className="rounded-2xl bg-white border p-4"><h3 className="font-extrabold mb-3">الفيديوهات التالية</h3><div className="space-y-3">{[1,2,3,4,5].map(n=><button key={n} className="w-full flex gap-3 text-start" onClick={()=>navigate('/videos')}><img src={cover(item)} className="w-28 h-16 rounded-lg object-cover"/><span className="text-sm font-bold line-clamp-2">{item.title} · {n}</span></button>)}</div></div>}<div className="rounded-2xl bg-white border p-4"><div className="grid grid-cols-2 gap-3 text-sm"><span><Eye className="inline h-4 w-4 me-1"/>{stats.views}</span><span><Heart className="inline h-4 w-4 me-1"/>{stats.likes}</span><span><MessageCircle className="inline h-4 w-4 me-1"/>{stats.comments}</span><span><Users className="inline h-4 w-4 me-1"/>{stats.buyers} مشترٍ</span></div>{isPaid&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm"><b>{item.price} {item.currency_code||'USD'}</b> · العرض {item.offer_duration_days||30} يوم</div>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={toggleLike} className={`rounded-xl border p-3 ${liked?'bg-rose-50 text-rose-600':''}`}><Heart className={`mx-auto h-5 w-5 ${liked?'fill-current':''}`}/></button><button onClick={toggleFav} className={`rounded-xl border p-3 ${favorite?'bg-amber-50 text-amber-600':''}`}><Bookmark className={`mx-auto h-5 w-5 ${favorite?'fill-current':''}`}/></button></div>{canOpen&&!isPaid&&<div className="mt-2 grid grid-cols-2 gap-2"><button onClick={share} className="rounded-xl border p-3"><Share2 className="mx-auto h-5 w-5"/></button><button onClick={download} className="rounded-xl border p-3"><Download className="mx-auto h-5 w-5"/></button><button onClick={publish} className="col-span-2 rounded-xl bg-teal-50 text-teal-700 p-3 font-bold">نشر على صفحتي</button></div>}</div>
<div className="rounded-2xl bg-white border p-4"><h3 className="font-extrabold mb-3">التعليقات</h3><div className="flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} className="input-field flex-1" placeholder="اكتب تعليقاً"/><button onClick={addComment} className="rounded-xl bg-teal-700 text-white px-4"><Send className="h-5 w-5"/></button></div><div className="mt-4 space-y-3">{comments.slice(0,10).map((c:any)=><div key={c.id} className="rounded-xl bg-gray-50 p-3 text-sm">{c.body}</div>)}</div></div></aside></div>{message&&<div className="fixed bottom-5 start-1/2 -translate-x-1/2 rounded-xl bg-gray-900 text-white px-5 py-3 shadow-xl">{message}</div>}</div></div>}
