import {useEffect,useMemo,useRef,useState} from 'react';
import {FileText,FileSignature,Download,Send,Save,Power,Plus,Trash2,Copy,ExternalLink,Clock,ShieldCheck} from 'lucide-react';
import {Document,Paragraph,TextRun,HeadingLevel,AlignmentType,Packer} from 'docx';
import {jsPDF} from 'jspdf';
import html2canvas from 'html2canvas';
import {supabase} from '@/lib/supabase';

type ContractTemplate={id:string;key:string;title:string;category:string;language:string;body:string;enabled:boolean;disabledUntil:string;version:number;updatedAt:string};
type Delivery={channel:string;target:string;templateId:string;sentAt:string};

const LANGS=[['ar','العربية'],['en','English'],['de','Deutsch'],['ru','Русский'],['uk','Українська'],['uz','O‘zbekcha'],['hy','Հայերեն'],['tg','Тоҷикӣ'],['az','Azərbaycan'],['am','አማርኛ'],['ka','ქართული']];
const seed:ContractTemplate[]=[
{id:'specialist-registration',key:'specialist-registration',title:'استمارة تسجيل الأخصائي',category:'registration',language:'ar',body:'الاسم القانوني الكامل\nالتخصص\nرقم الترخيص المهني\nالدولة والمدينة\nبيانات التواصل\nالإقرار بصحة الوثائق والتراخيص.\nالالتزام بسرية بيانات العملاء وسياسات SB1.\nالموافقة على المراجعة والتحقق قبل تفعيل الحساب.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()},
{id:'specialist-contract',key:'specialist-contract',title:'عقد وشروط الأخصائي',category:'specialist',language:'ar',body:'يلتزم الأخصائي بصحة بياناته ووثائقه وترخيصه.\nيلتزم بمواعيد الجلسات وجودة الخدمة المهنية.\nيحافظ على سرية بيانات العملاء ولا يستخدمها خارج الغرض المشروع.\nتحدد العمولات والأسعار وفق سياسة SB1 المنشورة.\nيجوز تعليق الحساب عند المخالفات وفق إجراءات المراجعة.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()},
{id:'pharmacy-contract',key:'pharmacy-contract',title:'عقد الصيدلية',category:'pharmacy',language:'ar',body:'تقر الصيدلية بصحة الترخيص والبيانات التجارية.\nتلتزم بقواعد صرف المنتجات والوصفات والقوانين المحلية.\nتلتزم بالأسعار والمخزون ومواعيد التجهيز والتوصيل.\nتتحمل مسؤولية المنتجات التي تبيعها وفق القانون.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()},
{id:'delivery-contract',key:'delivery-contract',title:'عقد المندوب وعامل التوصيل',category:'delivery',language:'ar',body:'يلتزم المندوب بالمحافظة على الطلب وعدم العبث به.\nيستخدم بيانات العميل لتنفيذ الطلب فقط.\nيلتزم بالمواعيد وإجراءات السلامة وقواعد التواصل.\nيمنع مشاركة بيانات العملاء أو استخدامها لأغراض شخصية.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()},
{id:'facility-lease',key:'facility-lease',title:'استمارة إيجار المنشأة الطبية',category:'facility',language:'ar',body:'بيانات المنشأة الطبية والعنوان.\nبيانات المؤجر والمستأجر.\nمدة الإيجار وتاريخ البداية والنهاية.\nالقيمة والدفعات والتأمين.\nالاستخدام المسموح للمنشأة والالتزام بالتراخيص المحلية.\nشروط الإنهاء والتسليم.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()},
{id:'institution-registration',key:'institution-registration',title:'استمارة تسجيل المؤسسة الطبية',category:'registration',language:'ar',body:'اسم المؤسسة ونوعها.\nالترخيص والجهة المانحة.\nالعنوان والدولة والمدينة.\nالخدمات والأسعار وساعات العمل.\nبيانات المسؤول القانوني.\nالموافقة على التحقق والمراجعة.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()}
];

function readTemplates(){try{const x=JSON.parse(localStorage.getItem('sb1_contract_center_templates')||'null');return Array.isArray(x)&&x.length?x:seed}catch{return seed}}
function downloadBlob(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function active(t:ContractTemplate){return !t.disabledUntil||new Date(t.disabledUntil).getTime()<=Date.now()}

export default function ContractsCenterPage(){
 const [authorized,setAuthorized]=useState<boolean|null>(null);
 useEffect(()=>{try{const a=JSON.parse(localStorage.getItem('admin_auth')||'null');setAuthorized(!!a&&['owner','moderator','content_manager','support'].includes(a.role))}catch{setAuthorized(false)}},[]);
 const [templates,setTemplates]=useState<ContractTemplate[]>(readTemplates);
 const [selectedId,setSelectedId]=useState(templates[0]?.id||'');
 const [lang,setLang]=useState('ar');
 const [target,setTarget]=useState('');
 const [email,setEmail]=useState('');
 const [channel,setChannel]=useState('whatsapp');
 const [notice,setNotice]=useState('');
 const [previewRef]=useState({current:null as HTMLDivElement|null});
 const current=useMemo(()=>templates.find(t=>t.id===selectedId)||templates[0],[templates,selectedId]);
 if(authorized===null)return <div className="min-h-screen grid place-items-center">جارٍ التحقق من صلاحية لوحة التحكم...</div>;
 if(!authorized)return <div className="min-h-screen grid place-items-center p-6"><div className="rounded-2xl bg-white border p-8 text-center"><h1 className="text-xl font-extrabold">غير مصرح</h1><p className="mt-2 text-slate-500">هذا المركز متاح للمالك والمشرفين فقط.</p><button onClick={()=>window.location.href='/admin'} className="mt-4 rounded-xl bg-teal-700 text-white px-5 py-3 font-bold">العودة للوحة التحكم</button></div></div>;
 const persist=(next:ContractTemplate[])=>{setTemplates(next);localStorage.setItem('sb1_contract_center_templates',JSON.stringify(next));};
 useEffect(()=>{(async()=>{try{const {data}=await supabase.from('contract_templates').select('*').order('updated_at',{ascending:false});if(data?.length){const mapped=data.map((x:any)=>({id:x.id,key:x.template_key,title:x.title,category:x.category,language:x.language||'ar',body:x.body||'',enabled:x.is_active!==false,disabledUntil:x.disabled_until||'',version:x.version||1,updatedAt:x.updated_at||new Date().toISOString()}));setTemplates(mapped);localStorage.setItem('sb1_contract_center_templates',JSON.stringify(mapped));}}catch{}})()},[]);
 if(!current)return null;
 const update=(patch:Partial<ContractTemplate>)=>persist(templates.map(t=>t.id===current.id?{...t,...patch,updatedAt:new Date().toISOString()}:t));
 const addTemplate=()=>{const id='custom-'+Date.now();persist([...templates,{id,key:id,title:'استمارة جديدة',category:'custom',language:lang,body:'اكتب بنود الاستمارة هنا.',enabled:true,disabledUntil:'',version:1,updatedAt:new Date().toISOString()}]);setSelectedId(id)};
 const remove=()=>{if(templates.length===1)return;persist(templates.filter(t=>t.id!==current.id));setSelectedId(templates.find(t=>t.id!==current.id)?.id||'')};
 const saveServer=async()=>{try{await supabase.from('contract_templates').upsert({id:current.id,template_key:current.key,title:current.title,category:current.category,language:current.language,body:current.body,is_active:current.enabled,disabled_until:current.disabledUntil||null,version:current.version,updated_at:new Date().toISOString()});setNotice('تم حفظ الوثيقة محلياً ومحاولة مزامنتها مع قاعدة البيانات.')}catch{setNotice('تم الحفظ محلياً؛ قاعدة البيانات غير متاحة حالياً.')}};
 const exportDocx=async()=>{const paras=current.body.split(/\\n+/).map((x,i)=>new Paragraph({children:[new TextRun({text:x,bold:/^(البند|المادة|الاسم|التخصص)/.test(x)})],spacing:{after:180}}));const doc=new Document({sections:[{properties:{page:{margin:{top:900,right:900,bottom:900,left:900}}},children:[new Paragraph({text:current.title,heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({children:[new TextRun({text:`SB1 · الإصدار ${current.version}`,bold:true})],alignment:AlignmentType.CENTER}),...paras,new Paragraph({children:[new TextRun({text:`آخر تحديث: ${new Date(current.updatedAt).toLocaleString()}`})]})]}]});downloadBlob(await Packer.toBlob(doc),`${current.key}-v${current.version}.docx`)};
 const exportPdf=async()=>{if(!previewRef.current)return;const canvas=await html2canvas(previewRef.current,{scale:2,backgroundColor:'#fff',useCORS:true});const pdf=new jsPDF({unit:'mm',format:'a4'});const pageW=210;const imgW=pageW-20;const imgH=canvas.height*imgW/canvas.width;let y=10;let remaining=imgH;let srcY=0;const pageH=277;while(remaining>0){pdf.addImage(canvas.toDataURL('image/png'),'PNG',10,y,imgW,imgH,undefined,'FAST');remaining-=pageH;if(remaining>0){pdf.addPage();y=10-srcY;srcY+=pageH;}}pdf.save(`${current.key}-v${current.version}.pdf`)};
 const link=`${window.location.origin}/contracts?template=${encodeURIComponent(current.id)}`;
 const send=()=>{const text=`SB1 — ${current.title}\\nالإصدار ${current.version}\\n${link}`;const urls:any={whatsapp:`https://wa.me/${target.replace(/[^0-9+]/g,'')}?text=${encodeURIComponent(text)}`,telegram:`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(link)}`,sms:`sms:${target}?body=${encodeURIComponent(text)}`,email:`mailto:${email}?subject=${encodeURIComponent(current.title)}&body=${encodeURIComponent(text)}`};window.open(urls[channel], '_blank');const deliveries:Delivery[]=JSON.parse(localStorage.getItem('sb1_contract_deliveries')||'[]');deliveries.unshift({channel,target:channel==='email'?email:target,templateId:current.id,sentAt:new Date().toISOString()});localStorage.setItem('sb1_contract_deliveries',JSON.stringify(deliveries.slice(0,200)));setNotice('تم فتح قناة الإرسال بالوثيقة والرابط.');};
 const addClause=()=>update({body:current.body+`\\nبند جديد — اكتب الشرط هنا.`,version:current.version+1});
 const disable=()=>{const value=new Date(Date.now()+24*60*60*1000).toISOString();update({enabled:false,disabledUntil:value,version:current.version+1})};
 const enable=()=>update({enabled:true,disabledUntil:'',version:current.version+1});
 return <div dir="rtl" className="min-h-screen bg-slate-50 pt-20 pb-16"><div className="mx-auto max-w-7xl px-4">
 <div className="mb-6 rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-teal-800 p-7 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck className="h-7 w-7"/><h1 className="text-2xl font-extrabold">مركز إدارة العقود والاستمارات الرقمية</h1></div><p className="mt-2 text-sm text-white/75">إدارة النصوص والبنود والإصدارات والتعطيل والتصدير والإرسال من مكان واحد.</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-sm">المالك / المشرفون</span></div></div>
 <div className="grid gap-6 lg:grid-cols-[280px_1fr]">
 <aside className="rounded-2xl bg-white border p-3 h-fit"><div className="flex items-center justify-between mb-3"><b>الوثائق</b><button onClick={addTemplate} className="rounded-lg bg-teal-50 p-2 text-teal-700" title="إضافة"><Plus className="h-4 w-4"/></button></div>{templates.map(t=><button key={t.id} onClick={()=>setSelectedId(t.id)} className={`w-full rounded-xl p-3 text-right mb-1 ${t.id===current.id?'bg-teal-50 text-teal-800':'hover:bg-slate-50'}`}><div className="font-bold text-sm">{t.title}</div><div className="text-[11px] text-slate-400">{t.category} · v{t.version} · {active(t)?'مفعلة':'معطلة'}</div></button>)}</aside>
 <main className="space-y-5">
 <div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl bg-white border p-4"><b>الحالة</b><div className={`mt-2 font-bold ${current.enabled&&active(current)?'text-emerald-600':'text-red-600'}`}>{current.enabled&&active(current)?'مفعلة':'معطلة'}</div></div><div className="rounded-2xl bg-white border p-4"><b>الإصدار</b><div className="mt-2 font-bold">v{current.version}</div></div><div className="rounded-2xl bg-white border p-4"><b>اللغة</b><select value={current.language} onChange={e=>update({language:e.target.value})} className="mt-2 w-full rounded-lg border p-2">{LANGS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div className="rounded-2xl bg-white border p-4"><b>تعطيل حتى</b><input type="datetime-local" value={current.disabledUntil?new Date(current.disabledUntil).toISOString().slice(0,16):''} onChange={e=>update({disabledUntil:e.target.value?new Date(e.target.value).toISOString():'' ,enabled:false,version:current.version+1})} className="mt-2 w-full rounded-lg border p-2"/></div></div>
 <section className="rounded-2xl bg-white border p-5"><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><h2 className="text-xl font-extrabold">المحرر الديناميكي</h2><p className="text-sm text-slate-500">غيّر أي نص، أضف أو احذف البنود، ثم احفظ إصداراً جديداً.</p></div><div className="flex flex-wrap gap-2"><button onClick={saveServer} className="rounded-xl bg-teal-700 text-white px-4 py-2 font-bold flex gap-2 items-center"><Save className="h-4 w-4"/>حفظ</button><button onClick={addClause} className="rounded-xl bg-slate-100 px-4 py-2 font-bold flex gap-2 items-center"><Plus className="h-4 w-4"/>إضافة بند</button><button onClick={remove} className="rounded-xl bg-red-50 text-red-700 px-4 py-2"><Trash2 className="h-4 w-4 inline"/> حذف</button></div></div><input value={current.title} onChange={e=>update({title:e.target.value,version:current.version+1})} className="w-full rounded-xl border p-3 mb-3 text-lg font-bold"/><textarea value={current.body} onChange={e=>update({body:e.target.value,version:current.version+1})} rows={18} className="w-full rounded-2xl border p-4 leading-8 font-medium" placeholder="اكتب بنود الوثيقة هنا..."/><div className="mt-3 flex flex-wrap gap-2"><button onClick={current.enabled&&active(current)?disable:enable} className={`rounded-xl px-4 py-2 font-bold flex gap-2 items-center ${current.enabled&&active(current)?'bg-red-600 text-white':'bg-emerald-600 text-white'}`}><Power className="h-4 w-4"/>{current.enabled&&active(current)?'تعطيل الوثيقة 24 ساعة':'إعادة تفعيل الوثيقة'}</button><button onClick={async()=>{update({version:current.version+1});await saveServer()}} className="rounded-xl bg-indigo-50 text-indigo-700 px-4 py-2 font-bold">إنشاء إصدار جديد</button></div>{notice&&<p className="mt-3 rounded-xl bg-emerald-50 text-emerald-700 p-3 text-sm">{notice}</p>}</section>
 <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-white border p-5"><h2 className="font-extrabold text-lg">التصدير</h2><p className="text-sm text-slate-500 mt-1">الملف ينتج مباشرة من النص الحالي.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={exportDocx} className="rounded-xl bg-blue-600 text-white px-4 py-3 font-bold flex gap-2"><Download className="h-4 w-4"/>Word .docx</button><button onClick={exportPdf} className="rounded-xl bg-red-600 text-white px-4 py-3 font-bold flex gap-2"><Download className="h-4 w-4"/>PDF للطباعة</button></div></div><div className="rounded-2xl bg-white border p-5"><h2 className="font-extrabold text-lg">الإرسال المباشر</h2><div className="grid gap-2 mt-3"><select value={channel} onChange={e=>setChannel(e.target.value)} className="rounded-xl border p-3"><option value="whatsapp">WhatsApp</option><option value="telegram">Telegram</option><option value="facebook">Facebook</option><option value="sms">SMS</option><option value="email">البريد الإلكتروني</option></select><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="رقم الهاتف مع رمز الدولة (WhatsApp/SMS/Telegram)" className="rounded-xl border p-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني عند اختيار Email" className="rounded-xl border p-3"/><div className="flex gap-2"><button onClick={send} className="rounded-xl bg-teal-700 text-white px-4 py-3 font-bold flex gap-2"><Send className="h-4 w-4"/>إرسال / فتح القناة</button><button onClick={()=>navigator.clipboard?.writeText(link).then(()=>setNotice('تم نسخ رابط الوثيقة.'))} className="rounded-xl bg-slate-100 px-4 py-3"><Copy className="h-4 w-4"/></button><a href={link} target="_blank" className="rounded-xl bg-slate-100 px-4 py-3"><ExternalLink className="h-4 w-4"/></a></div><p className="text-xs text-slate-400 mt-2">Facebook يستخدم رابط مشاركة؛ الإرسال الخاص المباشر عبر API يحتاج ربط Meta Business. WhatsApp/SMS/Email تفتح القناة بالبيانات المدخلة.</p></div></section>
 <section className="rounded-2xl bg-white border p-5"><h2 className="font-extrabold text-lg mb-3">معاينة جاهزة للطباعة</h2><div ref={el=>(previewRef.current=el)} className="mx-auto max-w-3xl bg-white border p-8 text-right leading-8"><h1 className="text-2xl font-extrabold mb-2">{current.title}</h1><p className="text-xs text-slate-500 mb-6">SB1 · الإصدار {current.version} · {current.language}</p>{current.body.split(/\\n+/).map((x,i)=><p key={i} className="mb-2">{x}</p>)}<hr className="my-6"/><p>الاسم: __________________________</p><p>التوقيع: ________________________</p><p>التاريخ: _________________________</p></div></section>
 </main></div></div></div>
}