import {useEffect,useState} from 'react';import {Check,Trash2,X,Clock,Shield,Camera} from 'lucide-react';import html2canvas from 'html2canvas';import {supabase} from '@/lib/supabase';
export default function ContentModerationPage(){const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [authed,setAuthed]=useState(false);const load=async()=>{const {data}=await supabase.from('content_submissions').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{setAuthed(!!localStorage.getItem('admin_auth'));load()},[]);const act=async(id:string,status:string)=>{
 setBusy(true);
 const row=rows.find(x=>x.id===id);
 if(row && (status==='rejected'||status==='deleted')){
   let screenshot='';
   try{const el=document.getElementById('submission-'+id);if(el){const canvas=await html2canvas(el,{backgroundColor:'#fff',scale:1});screenshot=canvas.toDataURL('image/jpeg',0.72)}}catch{}
   const snapshot={...row,review_action:status,reviewed_at:new Date().toISOString()};
   await supabase.rpc('sb1_create_banned_backup',{p_content_type:row.content_type,p_content_id:id,p_source_table:'content_submissions',p_source_file_path:row.file_path||null,p_snapshot:snapshot,p_screenshot_data_url:screenshot||null,p_block_reason:row.rejection_reason||'content moderation',p_blocked_by:'smart-moderation'});
 }
 await supabase.from('content_submissions').update({status,reviewed_at:new Date().toISOString()}).eq('id',id);
 if(status==='approved' && row){try{const origin=window.location.origin;await fetch(origin+'/api/marketing/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:row.title,body:row.description||'',media_url:row.cover_path||undefined,providers:['telegram','whatsapp','facebook','instagram']})})}catch{}}
 await load();setBusy(false)
};if(!authed)return <div className="min-h-screen pt-28 flex items-center justify-center"><div className="card p-8 text-center"><Shield className="mx-auto h-10 w-10 text-teal-600"/><h1 className="text-xl font-bold mt-3">لوحة مراجعة محتوى SB1</h1><p className="text-gray-500 mt-2">سجل دخول الإدارة أولاً.</p><a href="/admin" className="btn-primary inline-block mt-5">فتح الإدارة</a></div></div>;return <div className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="mb-6"><h1 className="text-2xl font-extrabold">مراجعة محتوى الأخصائيين</h1><p className="text-gray-500">لا يظهر أي محتوى للجمهور قبل الموافقة.</p></div><div className="grid gap-4">{rows.map(x=><div id={'submission-'+x.id} key={x.id} className="rounded-2xl bg-white border p-5 flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><div className="flex items-center gap-2"><span className="rounded-lg bg-gray-100 px-2 py-1 text-xs font-bold">{x.content_type}</span><span className={`rounded-lg px-2 py-1 text-xs font-bold ${x.status==='approved'?'bg-green-50 text-green-700':x.status==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{x.status}</span></div><h3 className="font-bold mt-2">{x.title}</h3><p className="text-sm text-gray-500 mt-1">{x.description}</p><p className="text-xs text-gray-400 mt-2"><Clock className="inline h-3 w-3"/> {x.language} · السعر {x.price} · 50% / 50%</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>act(x.id,'approved')} className="rounded-xl bg-green-600 text-white px-4 py-2 flex items-center gap-1"><Check className="h-4 w-4"/>موافقة</button><button disabled={busy} onClick={()=>act(x.id,'rejected')} className="rounded-xl bg-amber-100 text-amber-800 px-4 py-2 flex items-center gap-1"><X className="h-4 w-4"/>رفض</button><button disabled={busy} onClick={()=>act(x.id,'deleted')} className="rounded-xl bg-red-50 text-red-700 px-4 py-2 flex items-center gap-1"><Trash2 className="h-4 w-4"/>حذف</button></div></div>)}{!rows.length&&<div className="rounded-2xl bg-white border p-10 text-center text-gray-500">لا توجد طلبات محتوى.</div>}</div></div></div>}