import { useI18n } from '@/lib/i18n';
import { useRouter } from '@/lib/router';
import { Award, BookOpen, CheckCircle2, Clock3, PlayCircle, Users, Download, Video, MessageCircle } from 'lucide-react';
import { pt } from '@/lib/portalText';

export default function CourseDetailPage(){const {lang}=useI18n();const {navigate}=useRouter();const lessons=[
  pt(lang,{ar:'مقدمة وأساسيات المجال',ru:'Введение и основы направления',en:'Introduction and Foundations',de:'Einführung und Grundlagen'}),
  pt(lang,{ar:'المفاهيم الأساسية',ru:'Ключевые понятия',en:'Core Concepts',de:'Kernkonzepte'}),
  pt(lang,{ar:'التقييم العملي',ru:'Практическая оценка',en:'Practical Assessment',de:'Praktische Bewertung'}),
  pt(lang,{ar:'دراسة حالة تطبيقية',ru:'Практический кейс',en:'Applied Case Study',de:'Praxisfall'},),
];return <section className="min-h-screen bg-gray-50 py-12"><div className="mx-auto max-w-5xl px-4"><button onClick={()=>navigate('/courses')} className="mb-5 text-sm font-semibold text-primary-700">← {pt(lang,{ar:'العودة للكورسات',ru:'Назад к курсам',en:'Back to Courses',de:'Zurück zu Kursen'})}</button><div className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="bg-gradient-to-br from-primary-700 to-teal-700 p-8 text-white md:p-12"><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold"><Award className="h-4 w-4"/> SB1 ACADEMY</div><h1 className="mt-5 text-4xl font-extrabold">{pt(lang,{ar:'برنامج مهني متكامل',ru:'Комплексная профессиональная программа',en:'Professional Comprehensive Program',de:'Umfassendes Berufsprogramm'})}</h1><p className="mt-4 max-w-2xl text-white/80">{pt(lang,{ar:'منهج مرن يمكن تطويره وتحديثه وإضافة وحدات جديدة إليه.',ru:'Гибкая программа, которую можно обновлять и расширять.',en:'A flexible program that can be updated and expanded.',de:'Ein flexibles Programm, das erweitert und aktualisiert werden kann.'})}</p></div><div className="grid gap-6 p-6 md:grid-cols-3"><div className="card border p-5"><Clock3 className="h-5 w-5 text-primary-600"/><div className="mt-3 font-bold">6 {pt(lang,{ar:'أشهر',ru:'месяцев',en:'months',de:'Monate'})}</div></div><div className="card border p-5"><Users className="h-5 w-5 text-primary-600"/><div className="mt-3 font-bold">1,420 {pt(lang,{ar:'طالبًا',ru:'студентов',en:'students',de:'Studierende'})}</div></div><div className="card border p-5"><BookOpen className="h-5 w-5 text-primary-600"/><div className="mt-3 font-bold">24 {pt(lang,{ar:'وحدة',ru:'модуля',en:'modules',de:'Module'})}</div></div></div><div className="border-t p-6 md:p-8"><h2 className="text-2xl font-bold">{pt(lang,{ar:'محتوى البرنامج',ru:'Содержание программы',en:'Program Content',de:'Programminhalte'})}</h2><div className="mt-5 space-y-3">{lessons.map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-gray-100 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-primary-700">{i+1}</div><span className="flex-1 font-semibold text-gray-800">{x}</span><PlayCircle className="h-5 w-5 text-gray-300"/></div>)}</div><div className="mt-6 flex flex-wrap gap-3">
<button onClick={()=>navigate('/exams')} className="btn-primary inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4"/>{pt(lang,{ar:'ابدأ التقييم',ru:'Начать оценивание',en:'Start Assessment',de:'Bewertung starten'})}</button>
<button onClick={()=>{const text='SB1 Course\n'+lessons.join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download='SB1-course-outline.txt';a.click();URL.revokeObjectURL(a.href)}} className="btn-secondary inline-flex items-center gap-2"><Download className="h-4 w-4"/>{pt(lang,{ar:'تحميل الدورة',ru:'Скачать курс',en:'Download course',de:'Kurs herunterladen'})}</button>
<button onClick={()=>window.open('https://meet.jit.si/SB1-Course-Room','_blank')} className="btn-secondary inline-flex items-center gap-2"><Video className="h-4 w-4"/>{pt(lang,{ar:'غرفة الاجتماع',ru:'Комната встречи',en:'Meeting room',de:'Meetingraum'})}</button>
<button onClick={()=>navigate('/chat')} className="btn-secondary inline-flex items-center gap-2"><MessageCircle className="h-4 w-4"/>{pt(lang,{ar:'دردشة الدورة',ru:'Чат курса',en:'Course chat',de:'Kurs-Chat'})}</button>
</div></div></div></div></section>}
