import { useI18n } from '@/lib/i18n';
const items:any={ar:[
 ['الطب النفسي','تحديثات تعليمية حول النوم والقلق والوسواس وطرق طلب المساعدة المناسبة.'],
 ['القلب والأوعية','معلومات يومية عن عوامل الخطورة والمتابعة والوقاية وصحة القلب.'],
 ['الأطفال','إرشادات تثقيفية حول التطور والنمو والتغذية ومتى يفضل طلب تقييم متخصص.'],
 ['التحاليل والتصوير','شرح مبسط لكيفية فهم الفحوصات والأسئلة التي يمكن مناقشتها مع الطبيب.'],
 ['التأهيل','تحديثات تعليمية عن الحركة والعلاج الطبيعي والتأهيل بعد الإصابات.'],
 ['الصحة العامة','ملخصات يومية تعليمية عن الوقاية والنشاط والنوم والتغذية.']
],en:[['Mental health','Educational updates on sleep, anxiety, OCD and appropriate care pathways.'],['Cardiology','Daily educational notes on risk factors, prevention and heart health.'],['Pediatrics','Education on development, nutrition and when specialist assessment may help.'],['Diagnostics','Plain-language explanations of tests and questions to discuss with clinicians.'],['Rehabilitation','Educational updates on mobility, physiotherapy and recovery.'],['Public health','Daily education on prevention, activity, sleep and nutrition.']],ru:[['Психическое здоровье','Образовательные обновления о сне, тревоге, ОКР и обращении за помощью.'],['Кардиология','Ежедневные материалы о факторах риска, профилактике и здоровье сердца.'],['Педиатрия','Материалы о развитии детей, питании и необходимости оценки специалиста.'],['Диагностика','Понятные объяснения анализов и вопросов для врача.'],['Реабилитация','Образовательные материалы о движении и физиотерапии.'],['Общественное здоровье','Ежедневные материалы о профилактике, сне, активности и питании.']]};
export default function DailyNewsPage(){const {lang,dir}=useI18n();const list=items[lang]||items.en;const title=lang==='ar'?'الأخبار الطبية اليومية':lang==='ru'?'Ежедневные медицинские новости':'Daily Medical News';return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4"><div className="rounded-3xl bg-gradient-to-br from-slate-900 to-teal-700 p-8 text-white"><h1 className="text-3xl font-extrabold">{title}</h1><p className="mt-2">{lang==='ar'?'تحديثات وموجزات طبية يومية باللغة المختارة.':'Daily medical updates in the selected language.'}</p><div className="mt-3 text-sm opacity-80">{new Date().toLocaleDateString(lang==='ar'?'ar-EG':lang)}</div></div><div className="mt-6 grid gap-5 md:grid-cols-3">{list.map((x:any,i:number)=><article key={i} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="text-xs font-bold text-teal-700">SB1 · {new Date().toLocaleDateString(lang==='ar'?'ar-EG':lang)}</div><h2 className="mt-3 text-xl font-extrabold">{x[0]}</h2><p className="mt-3 leading-8 text-gray-600">{x[1]}</p><span className="mt-5 inline-block rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{lang==='ar'?'محتوى تثقيفي يحتاج مراجعة تحريرية':'Educational content · editorial review'}</span></article>)}</div></div></div>}