import {useEffect,useMemo,useState} from 'react';
import {Bike,MapPin,PackageCheck,ShieldCheck,WalletCards,FileText,AlertTriangle,Navigation,Clock3,CheckCircle2,Store,UserRound,Truck,LockKeyhole} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {useRouter} from '@/lib/router';
import {supabase} from '@/lib/supabase';

type Role='client'|'institution'|'delivery_worker'|'owner';
type Status='created'|'accepted'|'picked_up'|'on_route'|'delivered'|'disputed'|'cancelled';
type Order={id:string;institution:string;institutionAddress:string;customer:string;customerAddress:string;items:string;subtotal:number;deliveryFee:number;total:number;workerFee:number;workerFeeType:'fixed'|'percent';workerId:string|null;paymentMethod:'online'|'cod';paymentStatus:'held'|'cod_pending'|'released'|'refunded'|'disputed';status:Status;createdAt:string;updatedAt:string;workerName?:string};

const KEY='sb1_delivery_system_v3';
const WORKERS_KEY='sb1_delivery_workers_v3';
const roleLabels:any={ar:{client:'عميل',institution:'مؤسسة',delivery_worker:'عامل توصيل'},en:{client:'Client',institution:'Institution',delivery_worker:'Delivery worker'},ru:{client:'Клиент',institution:'Учреждение',delivery_worker:'Курьер'},de:{client:'Kunde',institution:'Einrichtung',delivery_worker:'Lieferfahrer'}};
const statusLabels:any={created:'تم إنشاء الطلب',accepted:'قبله عامل التوصيل',picked_up:'استلم الطلب من المؤسسة',on_route:'في الطريق إلى العميل',delivered:'تم التسليم',disputed:'معلّق للتحقيق',cancelled:'ملغي'};
const read=<T,>(key:string,fallback:T):T=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}};
const write=(key:string,v:any)=>localStorage.setItem(key,JSON.stringify(v));
const seedWorkers=[{id:'dw-demo-1',name:'عامل توصيل تجريبي',phone:'+000000000',city:'دمشق',active:true,ownerControlled:true}];

function MapCard({order}:{order:Order}){const steps=[['created','المؤسسة'],['picked_up','استلام الطلب'],['on_route','في الطريق'],['delivered','العميل']];const idx=Math.max(0,steps.findIndex(x=>x[0]===order.status));return <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h3 className="font-extrabold">خريطة متابعة الطلب</h3><p className="text-sm text-gray-500 mt-1">{order.institution} ← {order.customer}</p></div><Navigation className="h-6 w-6 text-teal-600"/></div><div className="relative mt-5 h-52 overflow-hidden rounded-2xl bg-slate-100 border"><div className="absolute inset-0 opacity-50" style={{backgroundImage:'linear-gradient(30deg,transparent 48%,#cbd5e1 49%,#cbd5e1 51%,transparent 52%),linear-gradient(120deg,transparent 48%,#cbd5e1 49%,#cbd5e1 51%,transparent 52%)',backgroundSize:'70px 70px'}}/><div className="absolute start-[12%] top-[70%] flex flex-col items-center"><Store className="h-8 w-8 text-teal-700"/><span className="rounded bg-white px-2 text-xs font-bold shadow">المؤسسة</span></div><div className="absolute end-[12%] top-[18%] flex flex-col items-center"><MapPin className="h-8 w-8 text-blue-700"/><span className="rounded bg-white px-2 text-xs font-bold shadow">العميل</span></div><div className="absolute start-[18%] top-[60%] h-1 w-[64%] rotate-[-25deg] rounded-full bg-teal-500"/><div className="absolute start-[45%] top-[43%] rounded-full bg-orange-500 p-2 shadow-lg transition-all"><Truck className="h-5 w-5 text-white"/></div></div><div className="mt-5 grid grid-cols-4 gap-2">{steps.map(([s,l],i)=><div key={s} className="text-center"><div className={'mx-auto h-8 w-8 rounded-full grid place-items-center text-xs font-bold '+(i<=idx?'bg-teal-600 text-white':'bg-gray-200 text-gray-500')}>{i+1}</div><p className="mt-1 text-[11px]">{l}</p></div>)}</div><p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">الخريطة داخل SB1 هنا تجريبية. عند ربط مزود خرائط خارجي يمكن استبدالها بتحديد موقع GPS فعلي لحظياً.</p></div>}

export default function DeliveryPage(){
 const{lang,dir}=useI18n(); const{path}=useRouter();
 const [role,setRole]=useState<Role>(()=>(localStorage.getItem('sb1_preview_role')||localStorage.getItem('sb1_account_role') as Role)||'client');
 const [orders,setOrders]=useState<Order[]>(()=>read(KEY,[]));
 const [workers,setWorkers]=useState<any[]>(()=>read(WORKERS_KEY,seedWorkers));
 const [tab,setTab]=useState('orders');
 const [institution,setInstitution]=useState('صيدلية SB1 التجريبية'); const [institutionAddress,setInstitutionAddress]=useState('العنوان المسجل للمؤسسة');
 const [customer,setCustomer]=useState('العميل'); const [customerAddress,setCustomerAddress]=useState('عنوان العميل');
 const [items,setItems]=useState('أدوية وأدوات طبية'); const [subtotal,setSubtotal]=useState('50'); const [deliveryFee,setDeliveryFee]=useState('5');
 const [paymentMethod,setPaymentMethod]=useState<'online'|'cod'>('online'); const [feeType,setFeeType]=useState<'fixed'|'percent'>('fixed'); const [feeValue,setFeeValue]=useState('3');
 const [workerPolicy,setWorkerPolicy]=useState<'all'|'selected'>('all'); const [selectedWorker,setSelectedWorker]=useState('');
 const [notice,setNotice]=useState('');
 const current=orders[0];

 useEffect(()=>{const r=(localStorage.getItem('sb1_account_role') as Role)||'client';setRole(['client','institution','delivery_worker','owner'].includes(r)?r:'client')},[path]);
 useEffect(()=>write(KEY,orders),[orders]);

 const total=Number(subtotal||0)+Number(deliveryFee||0);
 const workerFee=feeType==='percent'?Math.round(total*Number(feeValue||0)/100*100)/100:Number(feeValue||0);
 const roleText=roleLabels[lang]?.[role]||roleLabels.en[role];

 const createOrder=()=>{const id='DEL-'+Date.now().toString(36).toUpperCase();const w=workerPolicy==='selected'?(workers.find(x=>x.id===selectedWorker)||null):null;const o:Order={id,institution,institutionAddress,customer,customerAddress,items,subtotal:Number(subtotal||0),deliveryFee:Number(deliveryFee||0),total,workerFee,workerFeeType:feeType,workerId:w?.id||null,paymentMethod,paymentStatus:paymentMethod==='cod'?'cod_pending':'held',status:'created',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),workerName:w?.name};setOrders([o,...orders]);void supabase.from('sb1_delivery_orders').insert({id,institution_name:institution,institution_address:institutionAddress,customer_name:customer,customer_address:customerAddress,items:[{name:items}],subtotal:Number(subtotal||0),delivery_fee:Number(deliveryFee||0),total,worker_id:w?.id||null,worker_fee_type:feeType,worker_fee_value:workerFee,payment_method:paymentMethod,payment_status:paymentMethod==='cod'?'cod_pending':'held',status:'created'});setNotice('تم إنشاء الطلب. المبلغ الإلكتروني محجوز ولا تُصرف أي نسبة قبل التسليم.');setTab('orders')};
 const advance=(id:string)=>setOrders(os=>os.map(o=>{if(o.id!==id)return o;const next:Status=o.status==='created'?'accepted':o.status==='accepted'?'picked_up':o.status==='picked_up'?'on_route':o.status==='on_route'?'delivered':o.status;return {...o,status:next,updatedAt:new Date().toISOString(),paymentStatus:next==='delivered'?(o.paymentMethod==='cod'?'released':'released'):o.paymentStatus}}));
 const dispute=(id:string)=>{setOrders(os=>os.map(o=>o.id===id?{...o,status:'disputed',paymentStatus:'disputed',updatedAt:new Date().toISOString()}:o));setNotice('تم تعليق المبلغ وفتح تحقيق. لن تُصرف نسبة المؤسسة أو عامل التوصيل حتى انتهاء التحقيق.')};
 const acceptOrder=(id:string)=>setOrders(os=>os.map(o=>o.id===id?{...o,status:'accepted',workerId:'self',workerName:'العامل الحالي',updatedAt:new Date().toISOString()}:o));
 const cancelOrder=(id:string)=>{const reason=window.prompt('سبب إلغاء الطلب؟');if(!reason?.trim())return;const weak=reason.trim().length<12;const key='sb1_delivery_cancellations';const log=read<any[]>(key,[]);log.push({id,role,reason,weak,at:new Date().toISOString()});write(key,log);if(weak||log.filter(x=>x.role===role).length>=3)localStorage.setItem('sb1_delivery_penalty_'+role,JSON.stringify({reason:weak?'إلغاء بسبب غير كافٍ':'تكرار الإلغاءات',at:new Date().toISOString()}));setOrders(os=>os.map(o=>o.id===id?{...o,status:'cancelled',updatedAt:new Date().toISOString(),paymentStatus:'refunded'}:o));setNotice(weak?'تم إلغاء الطلب وتسجيل مخالفة بسبب ضعف سبب الإلغاء.':'تم إلغاء الطلب وتسجيل السبب للمراجعة.')};

 const tabs=(role==='client'?[['orders','طلباتي'],['map','التتبع']]:role==='delivery_worker'?[['orders','الطلبات المكلف بها'],['map','الخريطة'],['rules','القواعد والعقوبات']]:role==='institution'?[['orders','طلبات المؤسسة'],['create','طلب توصيل'],['map','التتبع'],['workers','العاملون'],['rules','القواعد والعقوبات'],['contract','العقد والوثائق']]:[['orders','كل الطلبات'],['create','طلب توصيل'],['map','الخريطة'],['workers','العاملون'],['rules','القواعد والعقوبات'],['contract','العقد والوثائق']]) as string[][];
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-slate-900 via-teal-800 to-cyan-700 p-8 text-white"><div className="flex items-center gap-4"><div className="rounded-2xl bg-white/10 p-3"><Bike className="h-9 w-9"/></div><div><h1 className="text-3xl font-extrabold">خدمات التوصيل والخرائط</h1><p className="mt-2 text-white/80">نظام مستقل للعميل والمؤسسة وعامل التوصيل مع الدفع والحجز والتتبع والتحقيق.</p></div></div><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/15 px-4 py-2">دورك: {roleText}</span><button onClick={()=>{localStorage.removeItem('sb1_account_role');window.location.href='/register'}} className="rounded-full bg-white px-4 py-2 font-bold text-slate-800">تغيير نوع الحساب</button></div></div>
  <div className="mt-5 flex gap-2 overflow-x-auto pb-2">{tabs.map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={'shrink-0 rounded-xl px-4 py-3 font-bold '+(tab===v?'bg-teal-700 text-white':'bg-white border text-gray-700')}>{l}</button>)}</div>
  {notice&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><CheckCircle2 className="inline h-5 w-5 me-2"/>{notice}</div>}

  {tab==='create'&&<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">إنشاء طلب توصيل</h2><p className="mt-1 text-sm text-gray-500">يمكن استخدامه للصيدلية أو الأدوات الطبية أو أي خدمة مؤسسة تدعم التوصيل.</p><div className="mt-4 grid gap-3"><input value={institution} onChange={e=>setInstitution(e.target.value)} className="rounded-xl border p-3" placeholder="اسم المؤسسة"/><input value={institutionAddress} onChange={e=>setInstitutionAddress(e.target.value)} className="rounded-xl border p-3" placeholder="عنوان المؤسسة"/><input value={customer} onChange={e=>setCustomer(e.target.value)} className="rounded-xl border p-3" placeholder="اسم العميل"/><input value={customerAddress} onChange={e=>setCustomerAddress(e.target.value)} className="rounded-xl border p-3" placeholder="عنوان العميل"/><textarea value={items} onChange={e=>setItems(e.target.value)} className="rounded-xl border p-3" placeholder="محتويات الطلب"/><div className="grid grid-cols-2 gap-3"><input type="number" value={subtotal} onChange={e=>setSubtotal(e.target.value)} className="rounded-xl border p-3" placeholder="قيمة الطلب"/><input type="number" value={deliveryFee} onChange={e=>setDeliveryFee(e.target.value)} className="rounded-xl border p-3" placeholder="رسوم التوصيل"/></div><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as any)} className="rounded-xl border p-3"><option value="online">دفع إلكتروني — المبلغ يُحجز</option><option value="cod">الدفع عند الاستلام</option></select><div className="rounded-2xl bg-gray-50 p-4"><b>أجر عامل التوصيل</b><div className="mt-3 grid grid-cols-2 gap-3"><select value={feeType} onChange={e=>setFeeType(e.target.value as any)} className="rounded-xl border p-3"><option value="fixed">مبلغ ثابت</option><option value="percent">نسبة من الطلب</option></select><input type="number" value={feeValue} onChange={e=>setFeeValue(e.target.value)} className="rounded-xl border p-3" placeholder={feeType==='percent'?'النسبة %':'المبلغ'}/></div></div><button onClick={createOrder} className="rounded-xl bg-teal-700 py-3 font-bold text-white">إنشاء الطلب وحجز المبلغ</button></div></div><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">سياسة الدفع</h2><div className="mt-4 space-y-3 text-sm leading-7"><p><WalletCards className="inline h-5 w-5 me-2 text-teal-600"/>الدفع الإلكتروني يبقى <b>معلقاً/محجوزاً</b> حتى تسجيل التسليم.</p><p><PackageCheck className="inline h-5 w-5 me-2 text-teal-600"/>لا تستحق المؤسسة أو عامل التوصيل النسبة قبل وصول الطلب واستلامه.</p><p><AlertTriangle className="inline h-5 w-5 me-2 text-orange-600"/>عند وجود شكوى يمكن تعليق المبلغ وفتح تحقيق قبل الصرف.</p><p><LockKeyhole className="inline h-5 w-5 me-2 text-indigo-600"/>الدفع عند الاستلام يسجل كمبلغ مستحق ولا يعتبر مكتمل التسوية حتى تأكيد الاستلام.</p></div></div></section>}

  {tab==='orders'&&<section className="mt-5 space-y-4">{orders.length===0?<div className="rounded-3xl bg-white border p-10 text-center text-gray-500">لا توجد طلبات. أنشئ أول طلب من تبويب «طلب توصيل».</div>:orders.map(o=><div key={o.id} className="rounded-3xl bg-white border p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-xs text-gray-400">{o.id}</span><h3 className="mt-1 text-lg font-extrabold">{o.institution} → {o.customer}</h3><p className="mt-1 text-sm text-gray-500">{o.items}</p></div><span className={'rounded-full px-3 py-1 text-xs font-bold '+(o.status==='delivered'?'bg-green-50 text-green-700':o.status==='disputed'?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700')}>{statusLabels[o.status]}</span></div><div className="mt-4 grid gap-3 md:grid-cols-4 text-sm"><div className="rounded-xl bg-gray-50 p-3">الإجمالي<br/><b>{o.total.toFixed(2)}</b></div><div className="rounded-xl bg-gray-50 p-3">طريقة الدفع<br/><b>{o.paymentMethod==='cod'?'عند الاستلام':'إلكتروني'}</b></div><div className="rounded-xl bg-gray-50 p-3">التسوية<br/><b>{o.paymentStatus}</b></div><div className="rounded-xl bg-gray-50 p-3">أجر العامل<br/><b>{o.workerFeeType==='percent'?o.workerFee+' (نسبة)':'ثابت '+o.workerFee}</b></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setTab('map')} className="rounded-xl bg-teal-50 px-4 py-2 font-bold text-teal-700">عرض الخريطة</button>{o.status!=='delivered'&&o.status!=='disputed'&&<button onClick={()=>advance(o.id)} className="rounded-xl bg-teal-700 px-4 py-2 font-bold text-white">تحديث حالة الطلب</button>{((role==='institution'||role==='delivery_worker'||role==='owner')&&o.status!=='cancelled')&&<button onClick={()=>cancelOrder(o.id)} className="rounded-xl bg-red-50 px-4 py-2 font-bold text-red-700">إلغاء الطلب مع ذكر السبب</button>}}{o.status!=='delivered'&&o.status!=='disputed'&&<button onClick={()=>dispute(o.id)} className="rounded-xl bg-red-50 px-4 py-2 font-bold text-red-700">الإبلاغ عن مشكلة وتعليق المبلغ</button>}</div></div>)}</section>}

  {tab==='map'&&current?<MapCard order={current}/>:tab==='map'&&<div className="mt-5 rounded-3xl bg-white border p-10 text-center text-gray-500">أنشئ طلباً أولاً لتظهر الخريطة.</div>}

  {tab==='workers'&&<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">سياسة ظهور الطلب للعاملين</h2><div className="mt-4 space-y-3"><label className="flex gap-3 rounded-xl border p-4"><input type="radio" name="wp" checked={workerPolicy==='all'} onChange={()=>setWorkerPolicy('all')}/><span><b>كل العاملين المتاحين</b><br/><small className="text-gray-500">يظهر الطلب للعاملين المطابقين للمدينة والنطاق.</small></span></label><label className="flex gap-3 rounded-xl border p-4"><input type="radio" name="wp" checked={workerPolicy==='selected'} onChange={()=>setWorkerPolicy('selected')}/><span><b>عاملون تحددهم المؤسسة</b><br/><small className="text-gray-500">المؤسسة تختار مجموعة محددة لاستقبال الطلبات.</small></span></label>{workerPolicy==='selected'&&<select value={selectedWorker} onChange={e=>setSelectedWorker(e.target.value)} className="w-full rounded-xl border p-3">{workers.map(w=><option key={w.id} value={w.id}>{w.name} — {w.city}</option>)}</select>}</div></div><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">العاملون المسجلون</h2>{workers.map(w=><div key={w.id} className="mt-3 flex items-center justify-between rounded-2xl border p-4"><div><b>{w.name}</b><p className="text-sm text-gray-500">{w.city} · {w.phone}</p></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs text-green-700">متاح</span></div>)}</div></section>}

  {tab==='rules'&&<section className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">شرح النظام لجميع الأطراف</h2><div className="mt-4 space-y-4 text-sm leading-7"><p><b>العميل:</b> يحدد العنوان وطريقة الدفع ويستلم الطلب، ويبلغ عن المشكلة فوراً مع الأدلة.</p><p><b>المؤسسة:</b> تعبئ بياناتها ووثائقها، تحدد طريقة التوصيل والعاملين والنسب، وتسلم الطلب مغلقاً ومطابقاً.</p><p><b>عامل التوصيل:</b> يقبل الطلب، يستلم من المؤسسة، يحافظ عليه، يتبع المسار، ويسجل التسليم.</p><p><b>SB1:</b> يدير النظام والإشعارات وسجل الحالة وآلية الحجز والتحقيق، ولا يضمن جودة المنتجات أو النقل أو تصرفات الأطراف.</p></div></div><div className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">العقوبات والتصعيد</h2><div className="mt-4 space-y-3 text-sm"><div className="rounded-xl bg-yellow-50 p-3"><b>خطأ أول مثبت:</b> تنبيه وتوثيق، وقد يخصم التعويض من الطرف المتسبب وفق العقد والقانون.</div><div className="rounded-xl bg-orange-50 p-3"><b>تكرار الأخطاء:</b> تجميد مؤقت ووقف استقبال طلبات جديدة.</div><div className="rounded-xl bg-red-50 p-3"><b>مخالفات جسيمة:</b> تعليق الحساب، حجز المبلغ محل النزاع، ومراجعة الإدارة.</div><div className="rounded-xl bg-slate-50 p-3"><b>التحقيق:</b> تحفظ حالة الطلب والأدلة والوقت وأطراف العملية قبل اتخاذ قرار التسوية.</div></div></div></section>}

  {tab==='contract'&&<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white border p-6"><FileText className="h-8 w-8 text-teal-600"/><h2 className="mt-3 text-xl font-extrabold">عقد المؤسسة وطلب التوصيل</h2><p className="mt-2 text-sm text-gray-600 leading-7">قبل تفعيل التوصيل يجب أن ترفق المؤسسة الهوية/السجل أو الترخيص، الترخيص المهني، بيانات الحساب المالي، عنوان المؤسسة، سياسة الإلغاء والاسترداد، وقائمة العاملين إن كان التوصيل داخلياً.</p><a href="/contracts?template=delivery" className="mt-4 inline-block rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">فتح عقد التوصيل</a></div><div className="rounded-3xl bg-white border p-6"><ShieldCheck className="h-8 w-8 text-indigo-600"/><h2 className="mt-3 text-xl font-extrabold">إخلاء المسؤولية</h2><p className="mt-2 text-sm text-gray-600 leading-7">يجب عرض شروط المسؤولية وفق القانون المحلي وبصياغة يراجعها محامٍ في الدولة. لا يجوز استخدام هذه الصفحة لإسقاط حقوق إلزامية للمستهلك أو مسؤوليات لا يسمح القانون باستبعادها.</p><div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-900">SB1 وسيط تقني: مسؤولية المنتج، التغليف، صحة العنوان، وسلامة النقل تقع على الطرف المسؤول عنها وفق العقد والقانون، مع احتفاظ العميل بحقوقه القانونية.</div></div></section>}
 </div></div>
}