import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,Star,MapPin,Clock,Users,Heart,MessageCircle,Send,Video,BookOpen,Mic,Image as ImageIcon,Upload,Settings2,Repeat2,Bookmark,Search,Globe2,Lock,UserPlus,Plus } from 'lucide-react';
import { useRouter } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { supabase,type Doctor } from '@/lib/supabase';
import { virtualDoctorsForSpecialty } from '@/lib/catalog';

type P={id:string;body:string;kind:'post'|'reel'|'article'|'video'|'audio'|'book';media?:string;likes:number;comments:{name:string;body:string}[];privacy:'public'|'followers'|'selected';created:number;doctor_id:string};
const tr=(lang:string,a:string,r:string,e:string)=>lang==='ar'?a:lang==='ru'?r:e;

export default function DoctorProfilePage({id}:{id:string}){
 const {navigate}=useRouter();const {lang,dir,specialtyName}=useI18n();
 const [doctor,setDoctor]=useState<Doctor|null>(null);const [loading,setLoading]=useState(true);
 const [posts,setPosts]=useState<P[]>([]);const [composer,setComposer]=useState('');const [kind,setKind]=useState<P['kind']>('post');const [privacy,setPrivacy]=useState<P['privacy']>('public');const [autoShare,setAutoShare]=useState(true);const [cover,setCover]=useState<string>(()=>localStorage.getItem('sb1_cover_'+id)||'');
 const [liked,setLiked]=useState<string[]>(()=>JSON.parse(localStorage.getItem('sb1_liked_'+id)||'[]'));const [saved,setSaved]=useState<string[]>(()=>JSON.parse(localStorage.getItem('sb1_saved_'+id)||'[]'));const [following,setFollowing]=useState(false);const [followBack,setFollowBack]=useState(true);const [search,setSearch]=useState('');
 const [comment,setComment]=useState<Record<string,string>>({});const [showComposer,setShowComposer]=useState(false);const [mediaUrl,setMediaUrl]=useState('');

 useEffect(()=>{(async()=>{try{const {data}=await supabase.from('doctors').select('*, specialty(*)').eq('id',id).maybeSingle();if(data)setDoctor(data);else{const m=id.match(/^catalog-doctor-([^\\-]+)-(.+)-(\\d+)$/);if(m){const d=virtualDoctorsForSpecialty(m[2],m[1],8).find(x=>x.id===id);if(d)setDoctor(d)}}}catch{}setLoading(false)})()},[id]);
 useEffect(()=>{if(!doctor)return;try{const all=JSON.parse(localStorage.getItem('sb1_profile_posts')||'{}');setPosts(Array.isArray(all[id])?all[id]:[])}catch{setPosts([])}},[doctor,id,lang]);
 const save=(next:P[])=>{setPosts(next);try{const all=JSON.parse(localStorage.getItem('sb1_profile_posts')||'{}');all[id]=next;localStorage.setItem('sb1_profile_posts',JSON.stringify(all))}catch{}};
 const reels=useMemo(()=>posts.filter(p=>p.kind==='reel'),[posts]);const filtered=useMemo(()=>posts.filter(p=>!search||p.body.toLowerCase().includes(search.toLowerCase())),[posts,search]);
 const publish=()=>{if(!composer.trim()&&!mediaUrl)return;const p:P={id:'profile-local-'+Date.now(),doctor_id:id,body:composer.trim(),kind,media:mediaUrl||undefined,likes:0,comments:[],privacy,created:Date.now()};save([p,...posts]);setComposer('');setMediaUrl('');setShowComposer(false)}; const onMedia=(file:File)=>{if(file.size>4*1024*1024)return;const r=new FileReader();r.onload=()=>setMediaUrl(String(r.result));r.readAsDataURL(file)};
 const toggle=(set:string[],key:string,storage:string)=>{const n=set.includes(key)?set.filter(x=>x!==key):[...set,key];if(storage.includes('liked'))setLiked(n);else setSaved(n);localStorage.setItem(storage,n.length?JSON.stringify(n):'[]')};
 const addComment=(p:P)=>{const body=(comment[p.id]||'').trim();if(!body)return;save(posts.map(x=>x.id===p.id?{...x,comments:[...x.comments,{name:localStorage.getItem('chat_name')||'مستخدم SB1',body}]}:x));setComment({...comment,[p.id]:''})};
 const onCover=(file:File)=>{if(file.size>3*1024*1024)return;const r=new FileReader();r.onload=()=>{const v=String(r.result);setCover(v);localStorage.setItem('sb1_cover_'+id,v)};r.readAsDataURL(file)};
 if(loading)return <div className="min-h-screen pt-28 text-center text-gray-400">{tr(lang,'جاري تحميل الملف...','Загрузка профиля...','Loading profile...')}</div>;
 if(!doctor)return <div className="min-h-screen pt-28 text-center"><p className="text-gray-500">الملف غير موجود</p><button onClick={()=>navigate('/doctors')} className="btn-primary mt-4">العودة</button></div>;
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-20 pb-16"><div className="mx-auto max-w-5xl px-4">
  <button onClick={()=>navigate('/doctors')} className="flex items-center gap-2 text-gray-500 py-4"><ArrowRight className="h-4 w-4"/>{tr(lang,'الأخصائيون والأطباء','Специалисты и врачи','Specialists & Doctors')}</button>
  <section className="bg-white border rounded-3xl overflow-hidden mb-5">
   <div className="h-52 relative bg-gradient-to-r from-teal-700 via-cyan-600 to-teal-500">{cover&&<img src={cover} className="absolute inset-0 w-full h-full object-cover" alt="cover"/>}<label className="absolute top-4 end-4 cursor-pointer rounded-xl bg-black/35 text-white px-3 py-2 text-sm"><Upload className="inline h-4 w-4 me-1"/>{tr(lang,'تغيير الغلاف / بانوراما','Изменить обложку / панораму','Change cover / panorama')}<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&onCover(e.target.files[0])}/></label></div>
   <div className="px-6 pb-6"><div className="-mt-16 flex flex-col md:flex-row gap-4 md:items-end"><div className="h-32 w-32 rounded-3xl border-4 border-white bg-white overflow-hidden shadow-lg shrink-0">{doctor.photo_url?<img src={doctor.photo_url} className="h-full w-full object-cover" alt={doctor.name}/>:<div className="h-full grid place-items-center text-4xl font-bold text-teal-600">{doctor.name.charAt(0)}</div>}</div><div className="flex-1"><h1 className="text-2xl font-extrabold text-gray-900">{doctor.name}</h1><p className="text-teal-700 font-semibold">{doctor.specialty&&specialtyName(doctor.specialty)}</p><div className="flex flex-wrap gap-3 text-xs text-gray-500 mt-2"><span><Star className="inline h-4 w-4 text-amber-400 fill-amber-400"/> {Number(doctor.rating).toFixed(1)}</span><span><MapPin className="inline h-4 w-4"/> {doctor.city}</span><span><Clock className="inline h-4 w-4"/> {doctor.experience_years} سنوات</span><span><Users className="inline h-4 w-4"/> {doctor.follower_count} متابع</span></div></div><div className="flex gap-2"><button onClick={()=>setFollowing(!following)} className={'rounded-xl px-5 py-3 font-bold '+(following?'bg-gray-100 text-gray-700':'bg-teal-600 text-white')}><UserPlus className="inline h-4 w-4 me-1"/>{following?'متابَع':'متابعة'}</button>{followBack&&<button onClick={()=>setFollowBack(false)} className="rounded-xl border px-4 py-3 text-sm">متابع لك — تابع بالمقابل</button>}</div></div>
   {doctor.bio&&<p className="mt-5 text-gray-600 leading-7">{doctor.bio}</p>}
  </div>
  </section>
  {reels.length>0&&<section className="bg-white border rounded-3xl p-5 mb-5"><div className="flex items-center justify-between mb-4"><h2 className="font-extrabold text-xl">{tr(lang,'ريلز من يتابعهم الأخصائي','Reels','Following Reels')}</h2><Video className="text-teal-600"/></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{reels.map(r=><div key={r.id} className="rounded-2xl overflow-hidden bg-black"><video src={r.media} controls className="w-full aspect-[9/16] object-cover"/></div>)}</div></section>}
  <section className="bg-white border rounded-3xl p-5 mb-5"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-xl">{tr(lang,'النشر على الواجهة','Publish on profile','Publish')}</h2><p className="text-sm text-gray-500">{tr(lang,'أنشئ منشوراً أو مقالاً أو ارفع ريلز أو فيديو أو صوت أو كتاب.','Создайте публикацию, статью, рилс, видео, аудио или книгу.','Create a post, article, reel, video, audio or book.')}</p></div><button onClick={()=>setShowComposer(!showComposer)} className="rounded-xl bg-teal-600 text-white px-4 py-2.5"><Plus className="inline h-4 w-4"/> {tr(lang,'إنشاء','Создать','Create')}</button></div>
   {showComposer&&<div className="mt-4 border-t pt-4"><textarea value={composer} onChange={e=>setComposer(e.target.value)} rows={4} className="w-full rounded-2xl border p-4 outline-none focus:border-teal-500" placeholder={tr(lang,'اكتب ما تريد نشره...','Напишите, что хотите опубликовать...','Write what you want to publish...')}/><div className="mt-3 flex flex-wrap gap-2 items-center"><select value={kind} onChange={e=>setKind(e.target.value as P['kind'])} className="rounded-xl border px-3 py-2"><option value="post">Post</option><option value="reel">Reel</option><option value="article">Article</option><option value="video">Video</option><option value="audio">Audio</option><option value="book">Book</option></select><select value={privacy} onChange={e=>setPrivacy(e.target.value as P['privacy'])} className="rounded-xl border px-3 py-2"><option value="public">عام</option><option value="followers">المتابعون فقط</option><option value="selected">أشخاص محددون</option></select><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={autoShare} onChange={e=>setAutoShare(e.target.checked)}/> مشاركة تلقائية في قسم المحتوى</label><label className="cursor-pointer rounded-xl bg-gray-50 px-3 py-2 text-sm"><ImageIcon className="inline h-4 w-4"/> رفع صورة/فيديو/صوت<input type="file" accept="image/*,video/*,audio/*" className="hidden" onChange={e=>e.target.files?.[0]&&onMedia(e.target.files[0])}/></label><button onClick={publish} disabled={!composer.trim()} className="ms-auto rounded-xl bg-teal-600 text-white px-5 py-2 disabled:opacity-40">نشر</button></div><p className="text-xs text-gray-400 mt-2">المحتوى المخصص للمتابعين لا يظهر للعامة. المشاركة التلقائية تنشر المحتوى المنشور باسم الأخصائي في القسم المناسب.</p></div>}
  </section>
  <div className="bg-white border rounded-2xl p-3 mb-5 flex gap-2"><Search className="h-5 w-5 text-gray-400 mt-2"/><input value={search} onChange={e=>setSearch(e.target.value)} className="flex-1 outline-none p-2" placeholder={tr(lang,'ابحث في منشورات هذا الأخصائي...','Поиск по публикациям специалиста...','Search this specialist posts...')}/></div>
  <div className="space-y-5">{filtered.map(p=><article key={p.id} className="bg-white border rounded-3xl p-5"><div className="flex gap-3"><div className="h-11 w-11 rounded-full bg-teal-50 grid place-items-center font-bold text-teal-700">{doctor.name.charAt(0)}</div><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><b>{doctor.name}</b><span className="text-xs text-gray-400">{new Date(p.created).toLocaleString()}</span><span className="text-xs rounded-full bg-gray-100 px-2 py-1">{p.privacy==='public'?'عام':p.privacy==='followers'?'المتابعون فقط':'محددون'}</span></div><p className="mt-3 leading-7 text-gray-700">{p.body}</p>{p.media&&<video src={p.media} controls className="mt-3 w-full max-h-[520px] rounded-2xl"/>}<div className="mt-4 flex flex-wrap gap-2 border-t pt-3"><button onClick={()=>toggle(liked,p.id,'sb1_liked_'+id)} className="rounded-xl px-3 py-2 hover:bg-rose-50"><Heart className={'inline h-4 w-4 '+(liked.includes(p.id)?'fill-rose-500 text-rose-500':'')}/> {p.likes+(liked.includes(p.id)?1:0)}</button><button className="rounded-xl px-3 py-2"><MessageCircle className="inline h-4 w-4"/> {p.comments.length}</button><button onClick={()=>toggle(saved,p.id,'sb1_saved_'+id)} className="rounded-xl px-3 py-2"><Bookmark className={'inline h-4 w-4 '+(saved.includes(p.id)?'fill-amber-400':'')}/></button><button onClick={()=>navigator.clipboard?.writeText(location.origin+'/doctors/'+id)} className="rounded-xl px-3 py-2"><Share2Icon/></button><button onClick={()=>save([{...p,id:'repost-'+Date.now(),body:'إعادة نشر: '+p.body},...posts])} className="rounded-xl px-3 py-2"><Repeat2 className="inline h-4 w-4"/> إعادة نشر</button></div>{p.comments.map((c,i)=><div key={i} className="mt-2 rounded-xl bg-gray-50 p-3"><b className="text-sm">{c.name}</b><p className="text-sm text-gray-600">{c.body}</p></div>)}<div className="mt-3 flex gap-2"><input value={comment[p.id]||''} onChange={e=>setComment({...comment,[p.id]:e.target.value})} onKeyDown={e=>e.key==='Enter'&&addComment(p)} className="flex-1 rounded-xl border px-3 py-2" placeholder="اكتب تعليقاً"/><button onClick={()=>addComment(p)} className="rounded-xl bg-teal-600 text-white p-2"><Send className="h-4 w-4"/></button></div></div></div></article>)}</div>
  <div className="mt-6 rounded-2xl bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900">ممنوع تحميل أو نسخ محتوى الغير ونشره باسمك، وممنوع نسخ إجابة طبيب آخر ولصقها باعتبارها إجابتك. استخدم إعادة النشر مع إظهار صاحب المحتوى.</div>
 </div></div>
}
function Share2Icon(){return <span className="inline-flex"><Globe2 className="h-4 w-4"/></span>}
