import { useEffect,useMemo,useState } from 'react';
import { Search } from 'lucide-react';
import { useRouter,parseQuery } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { supabase,type Doctor } from '@/lib/supabase';
import DoctorCard from '@/components/DoctorCard';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import { specialtyCatalog,virtualDoctorsForSpecialty,languageCountry,countriesForLanguage } from '@/lib/catalog';
export default function DoctorsPage(){
 const {path,navigate}=useRouter();const {lang,dir}=useI18n();const q=parseQuery(path);const [specialty,setSpecialty]=useState(q.specialty||'');const [search,setSearch]=useState(q.q||'');const [city,setCity]=useState('');const [count,setCount]=useState(10);const [dbDoctors,setDbDoctors]=useState<Doctor[]>([]);
 const specs=useMemo(()=>specialtyCatalog(lang),[lang]);const profile=languageCountry(lang);const countries=countriesForLanguage(lang);const [country,setCountry]=useState(countries[0]?.key||'');
 useEffect(()=>{setSpecialty(q.specialty||'');setSearch(q.q||'')},[q.specialty,q.q]);
 useEffect(()=>{supabase.from('doctors').select('*, specialty(*)').eq('is_virtual',false).then(({data})=>setDbDoctors((data||[]) as Doctor[])).catch(()=>setDbDoctors([]))},[]);
 const doctors=useMemo(()=>{if(!specialty){const demo=comprehensiveSpecialties.slice(0,8).flatMap(s=>virtualDoctorsForSpecialty(s.slug,lang,Math.max(5,Math.min(25,count)),country));return [...dbDoctors.filter(d=>d.native_language===lang),...demo].slice(0,24)}const real=dbDoctors.filter(d=>d.native_language===lang&&d.specialty?.slug===specialty);return (real.length?[...real,...virtualDoctorsForSpecialty(specialty,lang,count,country)]:virtualDoctorsForSpecialty(specialty,lang,count,country)).filter(d=>!search||d.name.toLowerCase().includes(search.toLowerCase())).filter(d=>!city||d.city===city)},[dbDoctors,specialty,lang,search,city,country,count]);
 const labels:any={ar:{title:'الأخصائيون والأطباء',lang:'اللغة الحالية',search:'ابحث باسم الأخصائي',spec:'اختار التخصص',country:'اختر البلد',city:'المدينة',count:'عدد الأخصائيين',all:'كل التخصصات',note:'يتم عرض الملفات الخاصة باللغة المختارة فقط. الملفات الافتراضية تعليمية وليست أشخاصاً حقيقيين.'},en:{title:'Specialists & Doctors',lang:'Current language',search:'Search specialist name',spec:'Choose specialty',country:'Choose country',city:'City',count:'Number of specialists',all:'All specialties',note:'Only profiles in the selected language are shown. Virtual profiles are educational, not real people.'},ru:{title:'Специалисты и врачи',lang:'Текущий язык',search:'Поиск специалиста',spec:'Выберите специальность',country:'Выберите страну',city:'Город',count:'Количество специалистов',all:'Все специальности',note:'Показываются только профили выбранного языка. Виртуальные профили учебные.'},de:{title:'Fachärzte & Ärzte',lang:'Aktuelle Sprache',search:'Name suchen',spec:'Fachgebiet wählen',country:'Land wählen',city:'Stadt',count:'Anzahl',all:'Alle Fachgebiete',note:'Nur Profile der ausgewählten Sprache. Virtuelle Profile sind Lernprofile.'}}[lang]||{title:'Specialists & Doctors',lang:'Current language',search:'Search',spec:'Choose specialty',country:'Country',city:'City',count:'Number',all:'All',note:'Virtual profiles are educational.'};
 return <div className="min-h-screen pt-24 pb-16 bg-gray-50" dir={dir}><div className="mx-auto max-w-7xl px-4">
  <div className="mb-6 rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-7 text-white"><h1 className="text-3xl font-extrabold">{labels.title}</h1><p className="mt-2">{labels.lang}: {profile.native} · {labels.note}</p></div>
  <div className="rounded-2xl bg-white border p-5 mb-6 grid gap-3 md:grid-cols-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={labels.search} className="rounded-xl border px-4 py-3"/><select value={specialty} onChange={e=>{setSpecialty(e.target.value);navigate('/doctors'+(e.target.value?'?specialty='+encodeURIComponent(e.target.value):''))}} className="rounded-xl border px-4 py-3"><option value="">{labels.all}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)} className="rounded-xl border px-4 py-3">{countries.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select><input value={city} onChange={e=>setCity(e.target.value)} placeholder={labels.city+' · '+profile.city} className="rounded-xl border px-4 py-3"/><select value={count} onChange={e=>setCount(Number(e.target.value))} className="rounded-xl border px-4 py-3" aria-label={labels.count}>{[5,10,15,20,25].map(n=><option key={n} value={n}>{labels.count}: {n}</option>)}</select></div>
  <div className="mb-5 rounded-2xl bg-white border p-5"><p className="font-bold text-gray-800">{specialty?specs.find(s=>s.slug===specialty)?.name:labels.title}</p><p className="text-sm text-gray-500 mt-1">{count} ملفات باللغة {profile.native} · {countries.find(c=>c.key===country)?.name}</p></div>
  <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{doctors.map(d=><DoctorCard key={d.id} doctor={d}/>)}</div>
  {!doctors.length&&<div className="rounded-2xl bg-white border p-10 text-center text-gray-500"><Search className="mx-auto h-10 w-10 text-gray-300"/><p className="mt-3">{labels.note}</p></div>}
 </div></div>;
}