import { useEffect,useMemo,useState } from 'react';
import { Search } from 'lucide-react';
import { useRouter,parseQuery } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { supabase,type Doctor } from '@/lib/supabase';
import DoctorCard from '@/components/DoctorCard';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import { specialtyCatalog,virtualDoctorsForSpecialty,languageCountry,countriesForLanguage } from '@/lib/catalog';
export default function DoctorsPage(){
 const {path,navigate}=useRouter();const {lang,dir}=useI18n();const q=parseQuery(path);const [specialty,setSpecialty]=useState(q.specialty||'');const [search,setSearch]=useState(q.q||'');const [age,setAge]=useState('all');const [gender,setGender]=useState('all');const [count,setCount]=useState(10);const [priceSort,setPriceSort]=useState('none');const [dbDoctors,setDbDoctors]=useState<Doctor[]>([]);
 const specs=useMemo(()=>specialtyCatalog(lang),[lang]);const profile=languageCountry(lang);const countries=countriesForLanguage(lang);const [country,setCountry]=useState(countries[0]?.key||'');
 useEffect(()=>{setSpecialty(q.specialty||'');setSearch(q.q||'')},[q.specialty,q.q]);
 useEffect(()=>{supabase.from('doctors').select('*, specialty(*)') .eq('is_virtual',false).eq('approval_status','approved').then(({data})=>setDbDoctors((data||[]) as Doctor[])).catch(()=>setDbDoctors([]))},[]);
 const normalizeGender=(value:any)=>{const v=String(value??'').trim().toLowerCase();if(['female','woman','women','أنثى','انثى','أنثى','female doctor','f'].includes(v))return 'female';if(['male','man','men','ذكر','m'].includes(v))return 'male';return v};
 const doctors=useMemo(()=>{const nameMatches=(d:any)=>!search||String(d.name||'').toLocaleLowerCase(lang).includes(search.trim().toLocaleLowerCase(lang));if(!specialty){const demo=comprehensiveSpecialties.flatMap(s=>virtualDoctorsForSpecialty(s.slug,lang,Math.max(5,Math.min(25,count)),country));const all=[...dbDoctors.filter(d=>d.native_language===lang&&(!d.country_code||d.country_code===country)),...demo].filter(nameMatches).filter((d:any)=>age==='all'||(age==='young'&&d.age<35)||(age==='mid'&&d.age>=35&&d.age<50)||(age==='senior'&&d.age>=50)).filter((d:any)=>gender==='all'||normalizeGender(d.gender)===gender);return all.sort((a,b)=>{if(priceSort==='low')return Number(a.consultation_price??75)-Number(b.consultation_price??75);if(priceSort==='high')return Number(b.consultation_price??75)-Number(a.consultation_price??75);const jamal=(x:any)=>/جمال|james|джеймс|ջեյմս|ჯეიმსი|jeyms|ceyms/i.test(x.name||'')?0:1;return jamal(a)-jamal(b)}).slice(0,count)}const real=dbDoctors.filter(d=>d.native_language===lang&&d.approval_status==='approved'&&d.specialty?.slug===specialty&&(!d.country_code||d.country_code===country));const virtual=virtualDoctorsForSpecialty(specialty,lang,count,country);const all=[...real,...virtual].filter(nameMatches) .filter((d:any)=>age==='all'||(age==='young'&&d.age<35)||(age==='mid'&&d.age>=35&&d.age<50)||(age==='senior'&&d.age>=50)) .filter((d:any)=>gender==='all'||normalizeGender(d.gender)===gender).filter((d:any,i:any,a:any[])=>a.findIndex((x:any)=>x.name===d.name&&x.photo_url===d.photo_url)===i);return all.sort((a:any,b:any)=>priceSort==='low'?Number(a.consultation_price??75)-Number(b.consultation_price??75):priceSort==='high'?Number(b.consultation_price??75)-Number(a.consultation_price??75):0).slice(0,count)},[dbDoctors,specialty,lang,search,age,gender,country,count,priceSort]);
 const labels:any={ar:{title:'الأخصائيون والأطباء',lang:'اللغة الحالية',search:'ابحث باسم الأخصائي',spec:'اختار التخصص',country:'اختر البلد',count:'عدد الأخصائيين',all:'كل التخصصات'},en:{title:'Specialists & Doctors',lang:'Current language',search:'Search specialist name',spec:'Choose specialty',country:'Choose country',count:'Number of specialists',all:'All specialties'},ru:{title:'Специалисты и врачи',lang:'Текущий язык',search:'Поиск специалиста',spec:'Выберите специальность',country:'Выберите страну',count:'Количество специалистов',all:'Все специальности'},de:{title:'Fachärzte & Ärzte',lang:'Aktuelle Sprache',search:'Name suchen',spec:'Fachgebiet wählen',country:'Land wählen',count:'Anzahl',all:'Alle Fachgebiete'}}[lang as any]||{title:'Specialists & Doctors',lang:'Current language',search:'Search',spec:'Choose specialty',country:'Country',city:'City',count:'Number',all:'All',note:'Virtual profiles are educational.'};
 return <div className="min-h-screen pt-24 pb-16 bg-gray-50" dir={dir}><div className="mx-auto max-w-7xl px-4">
  <div className="mb-6 rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-7 text-white"><h1 className="text-3xl font-extrabold">{labels.title}</h1><p className="mt-2">{labels.lang}: {profile.native}</p></div>
  <div className="grid gap-6 lg:grid-cols-[300px_1fr] items-start"><aside className="rounded-2xl border bg-white p-5 shadow-sm lg:sticky lg:top-24"><h2 className="text-xl font-extrabold text-gray-900">تصفية النتائج</h2><div className="mt-5 space-y-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={labels.search} className="w-full rounded-xl border px-4 py-3"/><select value={specialty} onChange={e=>{setSpecialty(e.target.value);navigate('/doctors'+(e.target.value?'?specialty='+encodeURIComponent(e.target.value):''))}} className="w-full rounded-xl border px-4 py-3"><option value="">{labels.all}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)} className="w-full rounded-xl border px-4 py-3">{countries.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select><select value={age} onChange={e=>setAge(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="all">العمر: الكل</option><option value="young">أقل من 35</option><option value="mid">35–49</option><option value="senior">50+</option></select><select value={gender} onChange={e=>setGender(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="all">النوع: الكل</option><option value="male">ذكر</option><option value="female">أنثى</option></select><select value={priceSort} onChange={e=>setPriceSort(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="none">ترتيب السعر</option><option value="low">الأقل سعراً</option><option value="high">الأعلى سعراً</option></select><select value={count} onChange={e=>setCount(Number(e.target.value))} className="w-full rounded-xl border px-4 py-3">{[5,10,15,20,25].map(n=><option key={n} value={n}>{labels.count}: {n}</option>)}</select></div></aside><main><div className="mb-4 flex items-center justify-between rounded-2xl border bg-white px-5 py-4"><div><b className="text-gray-900">{specialty?specs.find(s=>s.slug===specialty)?.name:labels.title}</b><p className="mt-1 text-sm text-gray-500">{count} {labels.title}</p></div><span className="text-sm text-gray-400">{doctors.length} {labels.title}</span></div><div className="grid gap-5 md:grid-cols-2">{doctors.map(d=><DoctorCard key={d.id} doctor={d} directory />)}</div></main></div>
  {!doctors.length&&<div className="rounded-2xl bg-white border p-10 text-center text-gray-500"><Search className="mx-auto h-10 w-10 text-gray-300"/><p className="mt-3">{labels.note}</p></div>}
 </div></div>;
}