import { useMemo,useState } from 'react';
import { Building2,Pill,HeartPulse,Home,Stethoscope,MapPin,Scan,FlaskConical,Accessibility } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useRouter,parseQuery } from '@/lib/router';
import { virtualFacilities,countriesForLanguage } from '@/lib/catalog';
const icons:any={clinic:Stethoscope,lab:FlaskConical,radiology:Scan,elderly:Home,pharmacy:Pill,addiction:HeartPulse,rehab:Accessibility,'medical-supplies':Building2};
const labels:any={ar:{clinic:'العيادات والمستشفيات',lab:'التحاليل',radiology:'الأشعة',elderly:'دور رعاية المسنين',pharmacy:'الصيدليات',addiction:'علاج الإدمان',rehab:'التأهيل والعلاج الطبيعي','medical-supplies':'الأدوات الطبية'},en:{clinic:'Clinics & Hospitals',lab:'Laboratories',radiology:'Radiology',elderly:'Elderly Care',pharmacy:'Pharmacies',addiction:'Addiction Care',rehab:'Rehabilitation & Physiotherapy','medical-supplies':'Medical Supplies'},ru:{clinic:'Клиники и больницы',lab:'Лаборатории',radiology:'Радиология',elderly:'Уход за пожилыми',pharmacy:'Аптеки',addiction:'Лечение зависимостей',rehab:'Реабилитация и физиотерапия','medical-supplies':'Медицинские товары'},de:{clinic:'Kliniken & Krankenhäuser',lab:'Labore',radiology:'Radiologie',elderly:'Seniorenpflege',pharmacy:'Apotheken',addiction:'Suchtbehandlung',rehab:'Rehabilitation & Physiotherapie','medical-supplies':'Medizinbedarf'},uk:{clinic:'Клініки та лікарні',lab:'Лабораторії',radiology:'Радіологія',elderly:'Догляд за літніми',pharmacy:'Аптеки',addiction:'Лікування залежностей',rehab:'Реабілітація та фізіотерапія','medical-supplies':'Медичні товари'},uz:{clinic:'Klinikalar va shifoxonalar',lab:'Laboratoriyalar',radiology:'Radiologiya',elderly:'Keksalar parvarishi',pharmacy:'Dorixonalar',addiction:'Giyohvandlik davolash',rehab:'Reabilitatsiya va fizioterapiya','medical-supplies':'Tibbiy jihozlar'},hy:{clinic:'Կլինիկաներ և հիվանդանոցներ',lab:'Լաբորատորիաներ',radiology:'Ռադիոլոգիա',elderly:'Տարեցների խնամք',pharmacy:'Դեղատներ',addiction:'Կախվածությունների բուժում',rehab:'Վերականգնում և ֆիզիոթերապիա','medical-supplies':'Բժշկական պարագաներ'},tg:{clinic:'Клиникаҳо ва беморхонаҳо',lab:'Озмоишгоҳҳо',radiology:'Радиология',elderly:'Нигоҳубини пиронсолон',pharmacy:'Дорухонаҳо',addiction:'Табобати вобастагӣ',rehab:'Барқарорсозӣ ва физиотерапия','medical-supplies':'Таҷҳизоти тиббӣ'},az:{clinic:'Klinikalar və xəstəxanalar',lab:'Laboratoriyalar',radiology:'Radiologiya',elderly:'Yaşlılara qayğı',pharmacy:'Apteklər',addiction:'Asılılıq müalicəsi',rehab:'Reabilitasiya və fizioterapiya','medical-supplies':'Tibbi ləvazimatlar'},am:{clinic:'ክሊኒኮች እና ሆስፒታሎች',lab:'ላቦራቶሪዎች',radiology:'ራዲዮሎጂ',elderly:'የአረጋውያን እንክብካቤ',pharmacy:'ፋርማሲዎች',addiction:'የሱስ ሕክምና',rehab:'ማገገሚያ እና ፊዚዮቴራፒ','medical-supplies':'የሕክምና እቃዎች'},ka:{clinic:'კლინიკები და საავადმყოფოები',lab:'ლაბორატორიები',radiology:'რადიოლოგია',elderly:'ხანდაზმულთა მოვლა',pharmacy:'აფთიაქები',addiction:'დამოკიდებულების მკურნალობა',rehab:'რეაბილიტაცია და ფიზიოთერაპია','medical-supplies':'სამედიცინო ინვენტარი'}};
export default function FacilitiesPage(){
 const {lang,dir}=useI18n();const {navigate,path}=useRouter();const query=parseQuery(path);const routeType=path.split('/')[1];const initialType=['clinic','lab','radiology','elderly','pharmacy','addiction','rehab','medical-supplies'].includes(query.type||'')?(query.type as string):(routeType==='labs'?'lab':routeType==='radiology'?'radiology':'clinic');const [type,setType]=useState(initialType);const countries=countriesForLanguage(lang);const [country,setCountry]=useState(countries[0]?.key||'');
 const list=useMemo(()=>virtualFacilities(lang,country).filter(f=>f.facility_type===type),[lang,country,type]);
 const labelsFor=labels[lang]||labels.en; const txt=pageTextMap[lang]||pageTextMap.en;
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir={dir}><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-8 text-white"><h1 className="text-3xl font-extrabold">{txt[0]}</h1><p className="mt-2 text-teal-50">{txt[1]}</p></div>
  <div className="sticky top-20 z-20 mt-4 rounded-2xl bg-white border p-3 shadow-sm overflow-x-auto"><div className="flex min-w-max gap-2">{Object.keys(icons).map(k=>{const I=icons[k];return <button key={k} onClick={()=>{setType(k);navigate('/facilities?type='+k)}} className={'flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold '+(type===k?'bg-teal-600 text-white':'bg-gray-50 text-gray-700')}><I className="h-4 w-4"/>{labelsFor[k]}</button>})}</div></div>
  <div className="my-5 flex flex-wrap items-center gap-3"><span className="font-semibold text-gray-700">{txt[2]}</span><select value={country} onChange={e=>setCountry(e.target.value)} className="rounded-xl border px-4 py-2.5 bg-white">{countries.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select></div>
  <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map(f=>{const I=icons[f.facility_type]||Building2;return <div key={f.id} className="rounded-2xl bg-white border p-6 shadow-sm"><div className="flex items-start gap-4"><div className="h-12 w-12 rounded-xl bg-teal-50 flex items-center justify-center"><I className="h-6 w-6 text-teal-600"/></div><div><h3 className="font-bold text-gray-900">{f.name}</h3><p className="text-sm text-gray-500 mt-1">{f.description}</p></div></div><div className="mt-4 flex items-center gap-2 text-sm text-gray-500"><MapPin className="h-4 w-4"/>{f.address}</div><button onClick={()=>navigate('/facilities/'+f.id)} className="mt-5 w-full rounded-xl bg-teal-50 py-3 font-bold text-teal-700 hover:bg-teal-100">{txt[3]}</button></div>})}</div>
 </div></div>;
}
const pageTextMap:any={ar:['المرافق الطبية','اختر نوع المرفق ثم البلد. البيانات التجريبية مفصولة حسب اللغة.','اختر البلد','تفاصيل المؤسسة والحجز'],en:['Medical Facilities','Choose a facility type and country. Demo data is separated by language.','Choose country','Facility details & booking'],ru:['Медицинские учреждения','Выберите тип учреждения и страну. Демо-данные разделены по языкам.','Выберите страну','Подробнее и запись'],de:['Medizinische Einrichtungen','Wählen Sie Einrichtung und Land. Demo-Daten sind nach Sprache getrennt.','Land wählen','Details & Buchung'],uk:['Медичні заклади','Оберіть тип закладу та країну.','Оберіть країну','Деталі та запис'],uz:['Tibbiy muassasalar','Muassasa turi va mamlakatni tanlang.','Mamlakatni tanlang','Tafsilot va yozilish'],hy:['Բժշկական հաստատություններ','Ընտրեք հաստատության տեսակը և երկիրը։','Ընտրեք երկիրը','Մանրամասներ և գրանցում'],tg:['Муассисаҳои тиббӣ','Навъ ва кишварро интихоб кунед.','Кишварро интихоб кунед','Тафсилот ва сабтином'],az:['Tibbi müəssisələr','Müəssisə növünü və ölkəni seçin.','Ölkə seçin','Ətraflı və qeydiyyat'],am:['የሕክምና ተቋማት','የተቋሙን አይነት እና አገር ይምረጡ።','አገር ይምረጡ','ዝርዝር እና ቀጠሮ'],ka:['სამედიცინო დაწესებულებები','აირჩიეთ დაწესებულების ტიპი და ქვეყანა.','აირჩიეთ ქვეყანა','დეტალები და ჩაწერა']};
