import { useMemo,useState } from 'react';
import { Building2,Pill,HeartPulse,Home,Stethoscope,MapPin,ShoppingCart,Scan,FlaskConical,Accessibility } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useRouter } from '@/lib/router';
import { virtualFacilities,languageCountry,countryLabel } from '@/lib/catalog';
import { ALL_COUNTRIES } from '@/types/i18n';
import { citiesForCountry } from '@/lib/cities';
const icons:any={clinic:Stethoscope,lab:FlaskConical,radiology:Scan,elderly:Home,pharmacy:Pill,addiction:HeartPulse,rehab:Accessibility,'medical-supplies':Building2};
const labels:any={
 ar:{clinic:'العيادات والمستشفيات',lab:'التحاليل',radiology:'الأشعة',elderly:'دور رعاية المسنين',pharmacy:'الصيدليات',addiction:'مراكز علاج الإدمان',rehab:'التأهيل والعلاج الطبيعي','medical-supplies':'الأدوات الطبية'},
 en:{clinic:'Clinics & Hospitals',lab:'Laboratories',radiology:'Radiology',elderly:'Elderly Care',pharmacy:'Pharmacies',addiction:'Addiction Care',rehab:'Rehabilitation & Physiotherapy','medical-supplies':'Medical Supplies'},
 de:{clinic:'Kliniken',lab:'Labore',radiology:'Radiologie',elderly:'Seniorenpflege',pharmacy:'Apotheken',addiction:'Suchtbehandlung',rehab:'Rehabilitation & Physiotherapie','medical-supplies':'Medizinische Hilfsmittel'},
 ru:{clinic:'Клиники и больницы',lab:'Лаборатории',radiology:'Радиология',elderly:'Дома престарелых',pharmacy:'Аптеки',addiction:'Лечение зависимостей',rehab:'Реабилитация и физиотерапия','medical-supplies':'Медицинские товары'},
 uk:{clinic:'Клініки та лікарні',lab:'Лабораторії',radiology:'Радіологія',elderly:'Догляд за літніми',pharmacy:'Аптеки',addiction:'Лікування залежностей',rehab:'Реабілітація та фізіотерапія','medical-supplies':'Медичні товари'},
 uz:{clinic:'Klinikalar',lab:'Laboratoriyalar',radiology:'Radiologiya',elderly:'Keksalar parvarishi',pharmacy:'Dorixonalar',addiction:'Giyohvandlik davosi',rehab:'Reabilitatsiya va fizioterapiya','medical-supplies':'Tibbiy buyumlar'},
 hy:{clinic:'Կլինիկաներ և հիվանդանոցներ',lab:'Լաբորատորիաներ',radiology:'Ռադիոլոգիա',elderly:'Տարեցների խնամք',pharmacy:'Դեղատներ',addiction:'Կախվածության բուժում',rehab:'Վերականգնում և ֆիզիոթերապիա','medical-supplies':'Բժշկական պարագաներ'},
 tg:{clinic:'Клиникаҳо ва беморхонаҳо',lab:'Лабораторияҳо',radiology:'Радиология',elderly:'Нигоҳубини пиронсолон',pharmacy:'Дорухонаҳо',addiction:'Табобати вобастагӣ',rehab:'Барқарорсозӣ ва физиотерапия','medical-supplies':'Таҷҳизоти тиббӣ'},
 az:{clinic:'Klinikalar və xəstəxanalar',lab:'Laboratoriyalar',radiology:'Radiologiya',elderly:'Yaşlılara qulluq',pharmacy:'Apteklər',addiction:'Asılılıq müalicəsi',rehab:'Reabilitasiya və fizioterapiya','medical-supplies':'Tibbi ləvazimatlar'},
 am:{clinic:'ክሊኒኮች እና ሆስፒታሎች',lab:'ላቦራቶሪዎች',radiology:'ራዲዮሎጂ',elderly:'የአረጋውያን እንክብካቤ',pharmacy:'ፋርማሲዎች',addiction:'የሱስ ሕክምና',rehab:'ማገገሚያ እና ፊዚዮቴራፒ','medical-supplies':'የሕክምና መሳሪያዎች'},
 ka:{clinic:'კლინიკები და საავადმყოფოები',lab:'ლაბორატორიები',radiology:'რადიოლოგია',elderly:'ხანდაზმულთა მოვლა',pharmacy:'აფთიაქები',addiction:'დამოკიდებულების მკურნალობა',rehab:'რეაბილიტაცია და ფიზიოთერაპია','medical-supplies':'სამედიცინო მოწყობილობები'}
};
export default function FacilitiesPage({initialType='clinic'}:{initialType?:string}){
 const {lang,dir}=useI18n();const ui:any={ar:{title:'المرافق الطبية',sub:'العيادات والمختبرات والأشعة والصيدليات والتأهيل وغيرها حسب اللغة والبلد.',details:'{ui.details}',search:'ابحث باسم المرفق أو المدينة'},en:{title:'Medical facilities',sub:'Clinics, laboratories, radiology, pharmacies, rehabilitation and more by language and country.',details:'Facility details & booking',search:'Search facility or city'},de:{title:'Medizinische Einrichtungen',sub:'Kliniken, Labore, Radiologie, Apotheken und Rehabilitation nach Sprache und Land.',details:'Details & Buchung',search:'Einrichtung oder Stadt suchen'},ru:{title:'Медицинские учреждения',sub:'Клиники, лаборатории, радиология, аптеки и реабилитация по языку и стране.',details:'Подробнее и запись',search:'Поиск учреждения или города'}}[lang]||{title:'Medical facilities',sub:'Facilities by selected language and country.',details:'Details & booking',search:'Search facility or city'};const {navigate}=useRouter();const p=languageCountry(lang);const [type,setType]=useState(initialType);const [country,setCountry]=useState(ALL_COUNTRIES.find(c=>c.code===(lang==='ru'?'RU':lang==='de'?'DE':lang==='uz'?'UZ':lang==='hy'?'AM':lang==='ka'?'KA':lang==='en'?'GB':lang==='uk'?'UA':lang==='az'?'AZ':lang==='tg'?'TG':lang==='am'?'ET':'SA'))?.code||'SA');const [city,setCity]=useState('');const [search,setSearch]=useState('');const countryOptions=ALL_COUNTRIES;const cities=citiesForCountry(country);
 const list=useMemo(()=>{const term=search.trim().toLowerCase();return virtualFacilities(lang,country).filter(f=>f.facility_type===type).filter(f=>!city||f.city===city).filter(f=>!term||(f.name+' '+f.address+' '+f.description).toLowerCase().includes(term))},[lang,country,type,city,search]);
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir={dir}><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-8 text-white"><h1 className="text-3xl font-extrabold">{ui.title}</h1><p className="mt-2 text-teal-50">{ui.sub}</p></div>
  <div className="sticky top-20 z-20 mt-4 rounded-2xl bg-white border p-3 shadow-sm overflow-x-auto"><div className="flex min-w-max gap-2">{Object.keys(labels).map(k=>{const I=icons[k];return <button key={k} onClick={()=>setType(k)} className={'flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold '+(type===k?'bg-teal-600 text-white':'bg-gray-50 text-gray-700')}><I className="h-4 w-4"/>{(labels[lang]||labels.en)[k]}</button>})}</div></div>
  <div className="my-5 grid gap-3 md:grid-cols-[1fr_auto] items-center"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={ui.search} className="rounded-xl border px-4 py-3 bg-white"/><div className="flex items-center gap-3"><span className="font-semibold text-gray-700">{lang==='ar'?'البلد':lang==='ru'?'Страна':lang==='de'?'Land':'Country'}</span><select value={country} onChange={e=>{setCountry(e.target.value);setCity('')}} className="rounded-xl border px-4 py-2.5 bg-white">{countryOptions.map(c=><option key={c.code} value={c.code}>{c.flag} {countryLabel(lang,c.code)}</option>)}</select><select value={city} onChange={e=>setCity(e.target.value)} className="rounded-xl border px-4 py-2.5 bg-white"><option value="">{lang==='ar'?'كل المدن':'All cities'}</option>{cities.map(c=><option key={c}>{c}</option>)}</select></div></div>
  <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map(f=>{const I=icons[f.facility_type]||Building2;return <div key={f.id} className="rounded-2xl bg-white border p-6 shadow-sm"><div className="flex items-start gap-4"><div className="h-12 w-12 rounded-xl bg-teal-50 flex items-center justify-center"><I className="h-6 w-6 text-teal-600"/></div><div><h3 className="font-bold text-gray-900">{f.name}</h3><p className="text-sm text-gray-500 mt-1">{f.description}</p></div></div><div className="mt-4 flex items-center gap-2 text-sm text-gray-500"><MapPin className="h-4 w-4"/>{f.address}</div><button onClick={()=>navigate('/facilities/'+f.id)} className="mt-5 w-full rounded-xl bg-teal-50 py-3 font-bold text-teal-700 hover:bg-teal-100">تفاصيل المؤسسة والحجز</button></div>})}</div>
  <div className="mt-8 rounded-2xl bg-white p-6 border flex items-center gap-2"><ShoppingCart className="text-teal-600"/><span>متجر الأدوات والمنتجات الطبية متاح ضمن SB1.</span></div>
 </div></div>;
}