import {useEffect,useState} from 'react';
import {useI18n} from '@/lib/i18n';
import {Bell,CheckCircle2,MessageCircle,PlayCircle,Trophy,MapPin} from 'lucide-react';
import {pt} from '@/lib/portalText';
import {supabase} from '@/lib/supabase';
import {recordCampaignEvent} from '@/lib/cityNotificationAds';
export default function NotificationsPage(){
 const {lang}=useI18n();const [campaigns,setCampaigns]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const uid=localStorage.getItem('sb1_account_user_id');if(!uid)return;const a=await supabase.from('sb1_audience_profiles').select('*').eq('user_id',uid).maybeSingle();if(!a.data)return;const d=await supabase.from('sb1_notification_deliveries').select('*').eq('audience_profile_id',a.data.id);const rows=d.data||[];setCampaigns(rows)})()},[]);
 const items=[
  {icon:PlayCircle,title:pt(lang,{ar:'درس جديد متاح',ru:'Доступен новый урок',en:'New lesson available',de:'Neue Lektion verfügbar'}),desc:pt(lang,{ar:'تمت إضافة درس جديد إلى كورسك الحالي.',ru:'В ваш текущий курс добавлен новый урок.',en:'A new lesson was added to your current course.',de:'Eine neue Lektion wurde zu Ihrem Kurs hinzugefügt.'})},
  {icon:MessageCircle,title:pt(lang,{ar:'رسالة جديدة',ru:'Новое сообщение',en:'New message',de:'Neue Nachricht'}),desc:pt(lang,{ar:'لديك رسالة جديدة من أحد أعضاء المجتمع.',ru:'У вас новое сообщение от участника сообщества.',en:'You have a new community message.',de:'Sie haben eine neue Community-Nachricht.'})},
  {icon:Trophy,title:pt(lang,{ar:'إنجاز جديد',ru:'Новое достижение',en:'New achievement',de:'Neue Auszeichnung'}),desc:pt(lang,{ar:'لقد أكملت 10 دروس تعليمية.',ru:'Вы завершили 10 уроков.',en:'You completed 10 lessons.',de:'Sie haben 10 Lektionen abgeschlossen.'})},
  {icon:CheckCircle2,title:pt(lang,{ar:'تم اعتماد التسجيل',ru:'Регистрация подтверждена',en:'Registration confirmed',de:'Anmeldung bestätigt'}),desc:pt(lang,{ar:'تم تحديث حالة حسابك بنجاح.',ru:'Статус вашего аккаунта успешно обновлён.',en:'Your account status was updated successfully.',de:'Ihr Kontostatus wurde успешно обновлён.'})},
 ];
 return <section className="min-h-screen bg-gray-50 py-12"><div className="mx-auto max-w-4xl px-4"><div className="mb-8 flex items-center gap-3"><div className="rounded-2xl bg-primary-50 p-3 text-primary-600"><Bell/></div><div><h1 className="text-3xl font-extrabold text-gray-900">{pt(lang,{ar:'الإشعارات',ru:'Уведомления',en:'Notifications',de:'Benachrichtigungen'})}</h1><p className="text-sm text-gray-500">{pt(lang,{ar:'إشعارات الحساب والحملات المحلية.',ru:'Уведомления аккаунта и местных кампаний.',en:'Account and local campaign notifications.',de:'Konto- und lokale Kampagnenbenachrichtigungen.'})}</p></div></div>
 {campaigns.length>0&&<div className="mb-5 space-y-3">{campaigns.map(d=><button key={d.id} onClick={async()=>{await recordCampaignEvent(d.id,'open');await recordCampaignEvent(d.id,'destination_click');const campaign=await supabase.from('sb1_notification_campaigns').select('*').eq('id',d.campaign_id).maybeSingle();const url=campaign.data?.destination_url||'/facilities';window.location.href=url+(url.includes('?')?'&':'?')+'campaign_id='+encodeURIComponent(d.campaign_id)+'&delivery_id='+encodeURIComponent(d.id)}} className="w-full text-start rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><div className="flex items-center gap-3"><MapPin className="text-indigo-600"/><div><b className="text-indigo-950">إعلان محلي</b><p className="mt-1 text-sm text-indigo-800">اضغط لفتح المؤسسة أو الخدمة المعلنة.</p></div></div></button>)}</div>}
 <div className="space-y-3">{items.map(({icon:Icon,title,desc},i)=><div key={i} className="card flex gap-4 p-5"><div className="rounded-xl bg-gray-50 p-3 text-primary-600"><Icon className="h-5 w-5"/></div><div className="flex-1"><div className="font-bold text-gray-800">{title}</div><p className="mt-1 text-sm text-gray-500">{desc}</p></div><span className="h-2.5 w-2.5 rounded-full bg-primary-500"/></div>)}</div></div></section>
}