import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import {ExternalLink,RefreshCw,Power,Save,ShieldCheck,Link2} from 'lucide-react';
const seed:any[]=[
 {provider:'github',name:{ar:'GitHub',en:'GitHub',ru:'GitHub'},website_url:'https://github.com',dashboard_url:'https://github.com/gom3aelhoot-prog/sb1',account_label:'gom3aelhoot-prog',project_label:'sb1',status:'connected',enabled:true},
 {provider:'vercel',name:{ar:'Vercel',en:'Vercel',ru:'Vercel'},website_url:'https://vercel.com',dashboard_url:'https://vercel.com/gamynady1256-9909/sb1',account_label:'gamynady1256-9909',project_label:'sb1',status:'connected',enabled:true},
 {provider:'supabase',name:{ar:'Supabase',en:'Supabase',ru:'Supabase'},website_url:'https://supabase.com',dashboard_url:'https://supabase.com/dashboard',account_label:'SB1 database/auth/storage',project_label:'SB1',status:'configured',enabled:true},
 {provider:'stripe',name:{ar:'Stripe',en:'Stripe',ru:'Stripe'},website_url:'https://stripe.com',dashboard_url:'https://dashboard.stripe.com',account_label:'SB1 payments',project_label:'Stripe Connect',status:'not_configured',enabled:true},
 {provider:'jitsi',name:{ar:'Jitsi Meet',en:'Jitsi Meet',ru:'Jitsi Meet'},website_url:'https://meet.jit.si',dashboard_url:'https://meet.jit.si',account_label:'Public rooms',project_label:'SB1 video rooms',status:'available',enabled:true},
 {provider:'ai_provider',name:{ar:'مزود الذكاء الاصطناعي',en:'AI Provider',ru:'ИИ-провайдер'},website_url:'https://platform.openai.com',dashboard_url:'https://platform.openai.com/api-keys',account_label:'SB1 AI',project_label:'AI API',status:'not_configured',enabled:true},
 {provider:'messaging',name:{ar:'SMS / WhatsApp',en:'SMS / WhatsApp',ru:'SMS / WhatsApp'},website_url:'https://www.twilio.com',dashboard_url:'https://console.twilio.com',account_label:'SB1 notifications',project_label:'Messaging',status:'not_configured',enabled:false},
 {provider:'delivery',name:{ar:'خدمات التوصيل',en:'Delivery Provider',ru:'Служба доставки'},website_url:'https://www.google.com/maps',dashboard_url:'',account_label:'SB1 pharmacy delivery',project_label:'Logistics',status:'not_configured',enabled:false}
];
const label=(lang:string,o:any)=>o?.[lang]||o?.en||o?.ar||'';
const statusLabel=(s:string,lang:string)=>({connected:lang==='ar'?'متصل فعلياً':lang==='ru'?'Подключено':'Connected',configured:lang==='ar'?'مُهيأ':lang==='ru'?'Настроено':'Configured',available:lang==='ar'?'متاح':lang==='ru'?'Доступно':'Available',not_configured:lang==='ar'?'غير مُهيأ':lang==='ru'?'Не настроено':'Not configured',error:lang==='ar'?'خطأ':lang==='ru'?'Ошибка':'Error'}[s]||s);
export default function OwnerIntegrationsPage(){
 const {lang,dir}=useI18n(); const [items,setItems]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const load=async()=>{setBusy(true);const {data,error}=await supabase.from('owner_integrations').select('*').order('created_at');setItems(data?.length?data:seed);setMsg(error?error.message:'');setBusy(false)};
 useEffect(()=>{load()},[]);
 const save=async(item:any)=>{const {error}=await supabase.from('owner_integrations').update({account_label:item.account_label,project_label:item.project_label,dashboard_url:item.dashboard_url,enabled:item.enabled,status:item.status,updated_at:new Date().toISOString()}).eq('provider',item.provider);setMsg(error?error.message:(lang==='ar'?'تم حفظ الإعدادات في لوحة المالك.':'Saved to owner control plane.'));};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4">
 <div className="rounded-3xl bg-slate-900 p-7 text-white"><div className="flex items-center justify-between gap-4"><div><div className="text-xs tracking-widest opacity-60">SB1 OWNER CONTROL PLANE</div><h1 className="mt-2 text-3xl font-extrabold">{lang==='ar'?'المواقع والحسابات المرتبطة':'Connected sites & accounts'}</h1><p className="mt-2 opacity-75">{lang==='ar'?'هذه البيانات محفوظة في قاعدة بيانات لوحة المالك وليست نصوصاً ثابتة في الواجهة.':'Managed records are stored in the owner control plane, not hard-coded UI text.'}</p></div><button onClick={load} className="rounded-xl bg-white/10 p-3" title="refresh"><RefreshCw className={busy?'animate-spin':''}/></button></div></div>
 {msg&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{msg}</div>}
 <div className="mt-6 grid gap-5 md:grid-cols-2">{items.map(item=><div key={item.provider} className="rounded-2xl bg-white p-5 shadow-sm border">
 <div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">{label(lang,item.name)}</h2><div className="mt-1 text-sm text-slate-500">{item.project_label||'—'}</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{statusLabel(item.status,lang)}</span></div>
 <div className="mt-4 grid gap-3"><label className="text-sm font-semibold">{lang==='ar'?'الحساب / الجهة':'Account / organization'}<input value={item.account_label||''} onChange={e=>setItems(xs=>xs.map(x=>x.provider===item.provider?{...x,account_label:e.target.value}:x))} className="mt-1 w-full rounded-xl border p-3"/></label>
 <label className="text-sm font-semibold">{lang==='ar'?'المشروع':'Project'}<input value={item.project_label||''} onChange={e=>setItems(xs=>xs.map(x=>x.provider===item.provider?{...x,project_label:e.target.value}:x))} className="mt-1 w-full rounded-xl border p-3"/></label>
 <label className="text-sm font-semibold">{lang==='ar'?'رابط لوحة الحساب':'Dashboard URL'}<input value={item.dashboard_url||''} onChange={e=>setItems(xs=>xs.map(x=>x.provider===item.provider?{...x,dashboard_url:e.target.value}:x))} className="mt-1 w-full rounded-xl border p-3"/></label>
 <div className="flex flex-wrap gap-2 pt-1"><button onClick={()=>setItems(xs=>xs.map(x=>x.provider===item.provider?{...x,enabled:!x.enabled}:x))} className={'rounded-xl px-3 py-2 text-sm font-bold '+(item.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600')}><Power className="inline h-4 w-4 me-1"/>{item.enabled?(lang==='ar'?'مفعّل':'Enabled'):(lang==='ar'?'متوقف':'Disabled')}</button><button onClick={()=>save(item)} className="rounded-xl bg-teal-600 px-3 py-2 text-sm font-bold text-white"><Save className="inline h-4 w-4 me-1"/>{lang==='ar'?'حفظ':'Save'}</button>{item.dashboard_url&&<a href={item.dashboard_url} target="_blank" rel="noreferrer" className="rounded-xl bg-indigo-50 px-3 py-2 text-sm font-bold text-indigo-700"><ExternalLink className="inline h-4 w-4 me-1"/>{lang==='ar'?'فتح الحساب':'Open'}</a>}</div>
 </div></div>)}</div>
 <div className="mt-6 rounded-2xl bg-white p-5 text-sm text-slate-600"><ShieldCheck className="inline h-5 w-5 text-emerald-600 me-2"/>{lang==='ar'?'المفاتيح السرية لا تُعرض في هذه الصفحة. حالة Stripe والذكاء الاصطناعي والرسائل تتحول إلى متصل بعد إعداد أسرار الخادم والتحقق منها.':'Secret keys are never displayed here. Stripe, AI and messaging become connected only after server-side secrets are configured and verified.'}</div>
 </div></div>
}