import {useEffect,useState} from 'react';
import {Shield,Save,UserPlus,Lock,Ban,CheckCircle,DollarSign,Globe2,Trash2,RefreshCw} from 'lucide-react';
import {supabase} from '@/lib/supabase';

const types=['article','video','audio','course','book','app','game','question','doctor','clinic','lab','radiology','facility','pharmacy','medical_supply'];
const statuses=['draft','published','hidden','blocked','deleted'];
const langs=['ar','en','de','ru','uk','uz','hy','tg','az','am','ka'];
const accountTypes=['doctor','specialist','clinic','lab','radiology','facility','pharmacy','delivery','other'];

export default function OwnerSovereigntyPage(){
 const [allowed,setAllowed]=useState(false),[tab,setTab]=useState<'content'|'accounts'|'sanctions'|'audit'|'backups'|'capacity'>('content'),[msg,setMsg]=useState('');
 const [controls,setControls]=useState<any[]>([]);const [audit,setAudit]=useState<any[]>([]);const [backups,setBackups]=useState<any[]>([]);const [capacity,setCapacity]=useState<any>(null);
 const [form,setForm]=useState({content_type:'article',content_id:'',publication_status:'published',billing_mode:'free',base_price:'0',currency:'USD',country_prices:'{}',country_currencies:'{}'});
 const [account,setAccount]=useState({email:'',password:'',display_name:'',account_type:'doctor',notes:'',skip_contracts:true,skip_document_verification:true,skip_digital_signature:true});
 const [statusForm,setStatusForm]=useState({user_key:'',status:'suspended',reason:''});
 const [busy,setBusy]=useState(false);
 const check=async()=>{const u=(await supabase.auth.getUser()).data.user;if(!u){setAllowed(false);return}const {data}=await supabase.from('admin_role_grants').select('role').eq('user_id',u.id).eq('is_active',true).maybeSingle();setAllowed(data?.role==='owner')};
 const load=async()=>{
 const [{data:c},{data:a},{data:b}]=await Promise.all([
  supabase.from('owner_content_controls').select('*').order('updated_at',{ascending:false}).limit(100),
  supabase.from('owner_control_audit').select('*').order('created_at',{ascending:false}).limit(100),
  supabase.from('sb1_banned_backups_registry').select('*').order('blocked_at',{ascending:false}).limit(100)
 ]);
 setControls(c||[]);setAudit(a||[]);setBackups(b||[]);
};
 useEffect(()=>{check();load()},[]);
 const saveContent=async()=>{setBusy(true);setMsg('');try{const cp=JSON.parse(form.country_prices||'{}');const cc=JSON.parse(form.country_currencies||'{}');const {data,error}=await supabase.rpc('sb1_owner_set_content_control',{p_content_type:form.content_type,p_content_id:form.content_id.trim(),p_publication_status:form.publication_status,p_billing_mode:form.billing_mode,p_base_price:Number(form.base_price||0),p_currency:form.currency,p_country_prices:cp,p_country_currencies:cc,p_metadata:{language_hint:'owner-control'}});setMsg(error?error.message:JSON.stringify(data));if(!error)load()}catch(e){setMsg('صيغة JSON غير صحيحة في أسعار الدول.')}setBusy(false)};
 const provision=async()=>{setBusy(true);setMsg('');try{const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/owner-provision-account',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify(account)});const d=await r.json();setMsg(r.ok?JSON.stringify(d):d.error||'فشل إنشاء الحساب')}catch(e){setMsg('تعذر الاتصال بخدمة إنشاء الحساب')}setBusy(false)};
 const changeStatus=async()=>{setBusy(true);const {data,error}=await supabase.rpc('sb1_owner_set_account_status',{p_user_key:statusForm.user_key.trim(),p_status:statusForm.status,p_reason:statusForm.reason});setMsg(error?error.message:JSON.stringify(data));setBusy(false);load()};
 if(!allowed)return <div className="min-h-screen bg-slate-50 pt-28 p-6"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 text-center shadow"><Lock className="mx-auto h-12 w-12 text-red-500"/><h1 className="mt-4 text-2xl font-extrabold">هذه الصفحة للمالك فقط</h1><p className="mt-2 text-slate-500">يجب تسجيل دخول حساب المالك.</p></div></div>;
 return <div dir="rtl" className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
 <div className="rounded-3xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-3"><Shield/><div><div className="text-xs tracking-widest text-cyan-300">SB1 OWNER SOVEREIGNTY</div><h1 className="text-3xl font-extrabold">السيادة الكاملة للمالك</h1><p className="mt-2 text-white/60">تحكم مباشر في المحتوى والأسعار والحسابات والاستثناءات والحظر.</p></div></div></div>
 <div className="mt-5 flex flex-wrap gap-2">{[['content','المحتوى والأسعار'],['backups','نسخ المحظورين واسترجاعهم'],['capacity','ضغط الخادم والتخزين'],['accounts','إنشاء حسابات واستثناء العقود'],['sanctions','حظر وتجميد الحسابات'],['audit','سجل المالك']].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`rounded-xl px-4 py-3 font-bold ${tab===k?'bg-teal-700 text-white':'bg-white text-slate-700'}`}>{l}</button>)}</div>
 {msg&&<div className="mt-4 rounded-xl bg-amber-50 p-4 text-amber-900 whitespace-pre-wrap">{msg}</div>}
 {tab==='content'&&<div className="mt-5 grid gap-6 lg:grid-cols-3">
 <section className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-1"><h2 className="font-extrabold flex items-center gap-2"><DollarSign/>تحكم المحتوى</h2><p className="mt-2 text-sm text-slate-500">غيّر مجاني/مدفوع والحالة والسعر وأسعار كل دولة/عملة.</p><select className="input-field mt-4" value={form.content_type} onChange={e=>setForm({...form,content_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><input className="input-field mt-3" placeholder="معرّف المحتوى" value={form.content_id} onChange={e=>setForm({...form,content_id:e.target.value})}/><select className="input-field mt-3" value={form.publication_status} onChange={e=>setForm({...form,publication_status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select><select className="input-field mt-3" value={form.billing_mode} onChange={e=>setForm({...form,billing_mode:e.target.value})}><option value="free">مجاني</option><option value="paid">مدفوع</option></select><div className="grid grid-cols-2 gap-2 mt-3"><input className="input-field" type="number" min="0" value={form.base_price} onChange={e=>setForm({...form,base_price:e.target.value})}/><input className="input-field" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></div><textarea className="input-field mt-3 h-24" placeholder='أسعار الدول JSON مثال {"DE":19.99,"SA":39}' value={form.country_prices} onChange={e=>setForm({...form,country_prices:e.target.value})}/><textarea className="input-field mt-3 h-20" placeholder='عملات الدول JSON مثال {"DE":"EUR","SA":"SAR"}' value={form.country_currencies} onChange={e=>setForm({...form,country_currencies:e.target.value})}/><button disabled={busy||!form.content_id} onClick={saveContent} className="mt-4 w-full rounded-xl bg-teal-700 px-4 py-3 font-bold text-white"><Save className="inline h-4 w-4"/> حفظ</button></section>
 <section className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2"><h2 className="font-extrabold">آخر أوامر المحتوى</h2><div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2">النوع</th><th>المعرف</th><th>الحالة</th><th>الدفع</th><th>السعر</th><th>آخر تعديل</th></tr></thead><tbody>{controls.map(x=><tr key={x.id} className="border-b"><td className="p-2">{x.content_type}</td><td>{x.content_id}</td><td>{x.publication_status}</td><td>{x.billing_mode}</td><td>{x.base_price} {x.currency}</td><td>{new Date(x.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section></div>}
 {tab==='backups'&&<div className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Admin Banned Backups Registry</h2><p className="mt-2 text-sm text-slate-500">كل محتوى حُظر من نظام المراجعة يُسجل هنا مع نسخة بيانات وصورة عند توفرها. الاسترجاع بقرار المالك فقط.</p><div className="mt-5 space-y-3">{backups.map(x=><div key={x.id} className="rounded-2xl border bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{x.content_type}</b> · {x.content_id}<div className="text-sm text-slate-500 mt-1">{x.block_reason||'بدون سبب'} · {new Date(x.blocked_at).toLocaleString()}</div></div><span className={'rounded-full px-3 py-1 text-xs font-bold '+(x.restored?'bg-green-100 text-green-700':'bg-red-100 text-red-700')}>{x.restored?'مسترجع بقرار المالك':'محظور'}</span></div>{x.screenshot_data_url&&<img src={x.screenshot_data_url} alt="backup" className="mt-3 max-h-48 rounded-xl border object-contain bg-white"/>}<div className="mt-3 flex flex-wrap gap-2">{!x.restored&&<button onClick={async()=>{if(!confirm('تأكيد استرجاع المحتوى للعامة؟'))return;setBusy(true);const {error}=await supabase.rpc('sb1_restore_banned_content',{p_registry_id:x.id});setMsg(error?error.message:'تم الاسترجاع بقرار المالك.');setBusy(false);load()}} disabled={busy} className="rounded-xl bg-green-700 px-4 py-2 font-bold text-white">إعادة تفعيل واسترجاع المحتوى للعامة</button>}{x.source_file_path&&<span className="rounded-xl bg-white px-3 py-2 text-xs text-slate-500">ملف المصدر: {x.source_file_path}</span>}</div></div>)}{!backups.length&&<div className="rounded-xl bg-slate-50 p-8 text-center text-slate-500">لا توجد نسخ محظورة بعد.</div>}</div></div>}
 {tab==='capacity'&&<div className="mt-5 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">وحدة ضغط الخادم والتخزين</h2><p className="mt-2 text-sm text-slate-500">يحسب النظام حجم Storage وقاعدة البيانات ويصدر تنبيهاً عند بلوغ 85% من الحدود التي تحددها هنا.</p><button onClick={async()=>{setBusy(true);const {data,error}=await supabase.rpc('sb1_capacity_snapshot',{p_storage_limit_gb:100,p_db_limit_gb:20});setCapacity(data);setMsg(error?error.message:'تم إنشاء تقرير ضغط جديد.');setBusy(false)}} disabled={busy} className="mt-5 rounded-xl bg-slate-900 px-5 py-3 font-bold text-white">فحص الضغط الآن</button>{capacity&&<pre className="mt-5 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-green-300">{JSON.stringify(capacity,null,2)}</pre>}</section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">الحذف الذكي السريع للميديا الزائدة</h2><p className="mt-2 text-sm text-slate-500">لا يتم حذف أي ملف تلقائياً. يعرض النظام الضغط والتكرارات أولاً، ثم يطلب قرار المالك.</p><button onClick={()=>setMsg('خطة التنظيف الآمنة: حذف التكرارات المؤكدة والملفات المؤرشفة الثقيلة بعد مراجعة المالك فقط.')} className="mt-5 rounded-xl bg-amber-600 px-5 py-3 font-bold text-white">اقتراح تنظيف الميديا الزائدة</button></section></div>}
 {tab==='accounts'&&<div className="mt-5 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold flex items-center gap-2"><UserPlus/>إنشاء حساب مالك مباشر</h2><p className="mt-2 text-sm text-slate-500">الحساب ينشأ من خادم آمن، ويتم تأكيد البريد تلقائياً. مفتاح Supabase السري لا يصل للمتصفح.</p><input className="input-field mt-4" placeholder="الاسم" value={account.display_name} onChange={e=>setAccount({...account,display_name:e.target.value})}/><input className="input-field mt-3" type="email" placeholder="البريد" value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/><input className="input-field mt-3" type="password" placeholder="كلمة المرور — 10 أحرف على الأقل" value={account.password} onChange={e=>setAccount({...account,password:e.target.value})}/><select className="input-field mt-3" value={account.account_type} onChange={e=>setAccount({...account,account_type:e.target.value})}>{accountTypes.map(x=><option key={x}>{x}</option>)}</select>{[['skip_contracts','تجاوز العقود'],['skip_document_verification','تجاوز رفع الوثائق'],['skip_digital_signature','تجاوز التوقيع الرقمي']].map(([k,l])=><label key={k} className="mt-3 flex items-center gap-2"><input type="checkbox" checked={(account as any)[k]} onChange={e=>setAccount({...account,[k]:e.target.checked})}/>{l}</label>)}<textarea className="input-field mt-3" placeholder="ملاحظات الاستثناء" value={account.notes} onChange={e=>setAccount({...account,notes:e.target.value})}/><button disabled={busy||!account.email||account.password.length<10} onClick={provision} className="mt-4 w-full rounded-xl bg-indigo-700 px-4 py-3 font-bold text-white"><UserPlus className="inline h-4 w-4"/> إنشاء وتفعيل فوراً</button></section>
 <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold">الاستثناءات المسجلة</h2><p className="text-sm text-slate-500 mt-2">الحسابات التي منحها المالك تجاوزاً إدارياً.</p><Exceptions/></section></div>}
 {tab==='sanctions'&&<div className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold flex items-center gap-2"><Ban/>حظر أو تجميد فوري</h2><div className="grid gap-3 md:grid-cols-4 mt-4"><input className="input-field" placeholder="user_id أو email" value={statusForm.user_key} onChange={e=>setStatusForm({...statusForm,user_key:e.target.value})}/><select className="input-field" value={statusForm.status} onChange={e=>setStatusForm({...statusForm,status:e.target.value})}><option value="suspended">تجميد</option><option value="deleted">حظر/حذف</option><option value="active">إعادة تفعيل</option></select><input className="input-field md:col-span-2" placeholder="سبب داخلي اختياري" value={statusForm.reason} onChange={e=>setStatusForm({...statusForm,reason:e.target.value})}/></div><button disabled={busy||!statusForm.user_key} onClick={changeStatus} className="mt-4 rounded-xl bg-red-700 px-5 py-3 font-bold text-white">تنفيذ فوراً</button><div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">الحالة الإدارية تسري فوراً على طبقة الحماية في SB1. الحذف النهائي من Auth يحتاج خادم Supabase الإداري.</div></div>}
 {tab==='audit'&&<div className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold">سجل المالك</h2><div className="mt-4 space-y-2">{audit.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{x.action}</b> · {x.target_type} · {x.target_id} · {new Date(x.created_at).toLocaleString()}<pre className="mt-1 whitespace-pre-wrap text-xs text-slate-500">{JSON.stringify(x.details)}</pre></div>)}</div></div>}
 </div></div>
}
function Exceptions(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('owner_account_exceptions').select('*').order('granted_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]))},[]);return <div className="mt-4 space-y-2">{rows.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{x.display_name||x.email}</b><div>{x.account_type} · العقود: {x.skip_contracts?'متجاوز':'مطلوب'} · الوثائق: {x.skip_document_verification?'متجاوزة':'مطلوبة'} · التوقيع: {x.skip_digital_signature?'متجاوز':'مطلوب'}</div></div>)}{!rows.length&&<div className="text-sm text-slate-400">لا توجد استثناءات.</div>}</div>}
