import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase';import {useI18n} from '@/lib/i18n';import {Shield,Send,History,Lock} from 'lucide-react';
const intents:any[]=[{k:'hide_section',a:['اخف','إخفاء','скрыть','დამალე','hide']},{k:'maintenance_mode',a:['صيانة','ارفع الموقع','maintenance','режим обслуживания','ტექნიკური']},{k:'delete_content',a:['احذف المحتوى','احذف المقال','delete content','удалить контент','კონტენტის წაშლა']},{k:'delete_institution',a:['احذف المؤسسة','delete institution','удалить учреждение','დაწესებულების წაშლა']},{k:'issue_warning',a:['انذر','تحذير','warn','предупредить','გაფრთხილება']},{k:'issue_fine',a:['غرامة','فرض غرامة','fine','штраф','ჯარიმა']},{k:'issue_reward',a:['مكافأة','اعط مكافأة','reward','награда','ჯილდო']},{k:'create_store_product',a:['أنشئ منتج','منتج جديد','create store product','создай товар','შექმენი პროდუქტი']},{k:'change_prices',a:['غير السعر','عدل السعر','change price','изменить цену','ფასის შეცვლა']},{k:'link_records',a:['اربط هذا بهذا','link records','связать','დაკავშირება']}];
function detect(s:string){const x=s.toLowerCase();return intents.find(i=>i.a.some((a:string)=>x.includes(a.toLowerCase())))?.k||''}
export default function OwnerCommandCenterPage(){const {lang,dir}=useI18n();const [text,setText]=useState('');const [key,setKey]=useState('');const [busy,setBusy]=useState(false);const [logs,setLogs]=useState<any[]>([]);const [role,setRole]=useState('');const [message,setMessage]=useState('');
const load=async()=>{const {data}=await supabase.from('admin_role_grants').select('role').eq('user_id',(await supabase.auth.getUser()).data.user?.id||'').eq('is_active',true).maybeSingle();setRole(data?.role||'');if(data?.role==='owner'){const r=await supabase.from('admin_command_audit').select('*').order('created_at',{ascending:false}).limit(30);setLogs(r.data||[])}};
useEffect(()=>{load()},[]);
const run=async()=>{if(!text.trim())return;const detected=detect(text);setKey(detected);if(!detected){setMessage(lang==='ar'?'لم أفهم الأمر. اختر أمراً من القائمة أو اكتب بصيغة أوضح.':'Command not recognized.');return}setBusy(true);setMessage('');const {data,error}=await supabase.rpc('execute_admin_command',{p_command_text:text,p_command_key:detected,p_action_key:detected,p_target_type:null,p_target_id:null,p_payload:{language:lang}});setBusy(false);setMessage(error?error.message:JSON.stringify(data));load()};
if(role!=='owner'&&role!=='moderator')return <div dir={dir} className="min-h-screen pt-28 p-6"><div className="mx-auto max-w-xl rounded-3xl bg-white p-8 shadow"><Lock className="mx-auto h-12 w-12 text-red-500"/><h1 className="mt-4 text-center text-2xl font-extrabold">هذه الصفحة للمالك والمشرفين فقط</h1></div></div>;
return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-slate-900 p-7 text-white"><div className="flex items-center gap-3"><Shield/><div><h1 className="text-2xl font-extrabold">الخادم الذكي — مركز أوامر SB1</h1><p className="opacity-75">الدور الحالي: {role}</p></div></div></div><div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-lg font-extrabold">اكتب الأمر</h2><textarea value={text} onChange={e=>{setText(e.target.value);setKey(detect(e.target.value))}} rows={7} className="mt-4 w-full rounded-2xl border p-4" placeholder="مثال: احذف المقال رقم ... / change price ... / скрыть раздел ..."/><div className="mt-3 text-sm text-slate-500">الأمر المكتشف: <b>{key||'—'}</b></div>{message&&<pre className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{message}</pre>}<button disabled={busy||!key} onClick={run} className="mt-4 rounded-xl bg-teal-600 px-6 py-3 font-bold text-white disabled:opacity-40"><Send className="inline h-4 w-4"/> {busy?'جار التنفيذ…':'تنفيذ الأمر'}</button></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold">أوامر معروفة</h2><div className="mt-3 space-y-2">{intents.map(i=><button key={i.k} onClick={()=>{setText(i.a[0]);setKey(i.k)}} className="block w-full rounded-xl bg-slate-50 p-3 text-start text-sm hover:bg-slate-100">{i.a[0]}</button>)}</div></section></div><section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-extrabold"><History className="inline h-5 w-5"/> سجل الأوامر</h2><div className="mt-4 overflow-auto"><table className="w-full text-sm"><tbody>{logs.map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.command_text}</td><td className="p-3">{x.action_key}</td><td className="p-3">{x.status}</td><td className="p-3">{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section></div></div>}
