import {useEffect,useState} from 'react';import {MessageCircle,Send,Plus,UserPlus,ShieldCheck} from 'lucide-react';import {supabase} from '@/lib/supabase';
export default function OwnerTeamChatPage(){const [rooms,setRooms]=useState<any[]>([]),[room,setRoom]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState(''),[newName,setNewName]=useState(''),[member,setMember]=useState(''),[members,setMembers]=useState<any[]>([]);
const load=async()=>{const {data}=await supabase.from('sb1_team_chat_rooms').select('*').order('created_at',{ascending:false});setRooms(data||[]);if(!room&&data?.[0])setRoom(data[0])};
const loadMembers=async(r:any)=>{if(!r)return;const {data}=await supabase.from('sb1_team_chat_members').select('*').eq('room_id',r.id);setMembers(data||[]);const {data:m}=await supabase.from('sb1_team_chat_messages').select('*').eq('room_id',r.id).order('created_at');setMessages(m||[])};
useEffect(()=>{load()},[]);useEffect(()=>{loadMembers(room)},[room]);
const createRoom=async()=>{if(!newName.trim())return;await supabase.from('sb1_team_chat_rooms').insert({id:'team-'+Date.now(),name:newName.trim(),description:'غرفة خاصة يحدد المالك أعضاءها',member_count:0,is_active:true,created_at:new Date().toISOString()});setNewName('');load()};
const addMember=async()=>{if(!room||!member.trim())return;await supabase.from('sb1_team_chat_members').insert({id:'member-'+Date.now(),room_id:room.id,member_name:member.trim(),member_role:'specialist',created_at:new Date().toISOString()});setMember('');loadMembers(room)};
const send=async()=>{if(!room||!text.trim())return;await supabase.from('sb1_team_chat_messages').insert({id:'msg-'+Date.now(),room_id:room.id,body:text.trim(),sender_name:'المالك',sender_role:'owner',created_at:new Date().toISOString()});setText('');loadMembers(room)};
return <div className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-white border p-6 mb-5"><div className="flex items-center gap-3"><ShieldCheck className="text-teal-600"/><div><h1 className="text-2xl font-extrabold">مجموعات المالك والمشرفين والأخصائيين</h1><p className="text-sm text-slate-500">المالك ينشئ الغرفة ويختار المشرفين أو الأخصائيين الذين يدخلون إليها.</p></div></div></div><div className="grid md:grid-cols-[280px_1fr] gap-5"><aside className="bg-white border rounded-2xl p-4"><h2 className="font-bold mb-3">الغرف</h2>{rooms.map(r=><button key={r.id} onClick={()=>setRoom(r)} className={'w-full text-right rounded-xl p-3 mb-2 '+(room?.id===r.id?'bg-teal-50 text-teal-700':'hover:bg-slate-50')}>{r.name}</button>)}<div className="mt-5 border-t pt-4"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="اسم غرفة جديدة" className="input-field mb-2"/><button onClick={createRoom} className="w-full rounded-xl bg-teal-600 text-white py-2 flex items-center justify-center gap-2"><Plus/>إنشاء غرفة</button></div></aside><section className="bg-white border rounded-2xl min-h-[560px] flex flex-col">{room?<><div className="p-4 border-b"><b>{room.name}</b><div className="flex flex-wrap gap-2 mt-3">{members.map(m=><span key={m.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{m.member_name} · {m.member_role}</span>)}<div className="flex gap-2"><input value={member} onChange={e=>setMember(e.target.value)} placeholder="اسم أخصائي/مشرف" className="border rounded-lg px-3 py-1 text-xs"/><button onClick={addMember} className="rounded-lg bg-indigo-50 text-indigo-700 px-3 py-1 text-xs"><UserPlus className="inline h-4 w-4"/> إضافة</button></div></div></div><div className="flex-1 p-5 space-y-3">{messages.map(m=><div key={m.id} className="rounded-xl bg-slate-100 p-3"><b>{m.sender_name}</b><p>{m.body}</p></div>)}</div><div className="p-3 border-t flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} className="input-field flex-1" placeholder="رسالة خاصة"/><button onClick={send} className="rounded-xl bg-teal-600 text-white px-4"><Send/></button></div></>:<div className="m-auto text-slate-400">اختر غرفة أو أنشئ غرفة</div>}</section></div></div></div>}
