import {useEffect,useState} from 'react';
import {Scale,Calculator,Stethoscope,Megaphone,Video,ShieldCheck,Save,Wallet,BarChart3,Lock} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
const roles=[
 ['accounting','المشرف المحاسبي القانوني والضريبي','Accounting, Legal & Tax Supervisor',Calculator],
 ['legal','المشرف المستشار القانوني والمحامي الدولي','Legal Counsel & International Lawyer',Scale],
 ['medical_audit','مشرف طبي التدقيق والرقابة على الأخصائيين','Medical Audit & Specialist Oversight',Stethoscope],
 ['marketing','مشرف الإعلانات والتطوير التسويقي','Advertising & Marketing Development Supervisor',Megaphone],
 ['privacy_video','مشرف الرقابة وتتبع الجلسات المرئية','Video Session Safety & Privacy Supervisor',Video]
];
const pay=[
 ['stripe','Stripe','الدولي — Stripe Connect / destination charges','https://stripe.com/connect'],
 ['paddle','Paddle','الدولي — Merchant of Record','https://www.paddle.com/'],
 ['yookassa','ЮKassa','روسيا وطرق الدفع المحلية','https://yookassa.ru/'],
 ['robokassa','Robokassa','روسيا وطرق الدفع المحلية','https://robokassa.com/']
];
export default function OwnerGovernancePage(){
 const {lang,dir}=useI18n(); const [enabled,setEnabled]=useState<Record<string,boolean>>({}); const [mode,setMode]=useState('demo'); const [counter,setCounter]=useState({online:12840,doctors:3860,visitors:42190}); const [fee,setFee]=useState(10); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{setEnabled(JSON.parse(localStorage.getItem('sb1_supervisor_roles')||'{}'));setMode(localStorage.getItem('sb1_counter_mode')||'demo');setCounter(JSON.parse(localStorage.getItem('sb1_counters')||JSON.stringify(counter)));setFee(Number(localStorage.getItem('sb1_platform_fee')||10))}catch{}},[]);
 const save=()=>{localStorage.setItem('sb1_supervisor_roles',JSON.stringify(enabled));localStorage.setItem('sb1_counter_mode',mode);localStorage.setItem('sb1_counters',JSON.stringify(counter));localStorage.setItem('sb1_platform_fee',String(fee));setSaved(true);setTimeout(()=>setSaved(false),2000)};
 const tr=(a:string,e:string)=>lang==='ar'?a:e;
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
 <div className="rounded-3xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-3"><ShieldCheck/><div><div className="text-xs opacity-60">SB1 OWNER CONTROL</div><h1 className="text-3xl font-extrabold">{tr('الحوكمة والمشرفون والمالية','Governance, supervisors & finance')}</h1><p className="mt-2 opacity-70">{tr('كل التفعيلات هنا قابلة للتحكم من المالك، والمفاتيح السرية لا تُحفظ في الواجهة.','Owner-controlled configuration; secret keys are never stored in the browser.')}</p></div></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">{tr('طاقم المشرفين والمستشارين','Supervisor & advisor team')}</h2><div className="mt-4 space-y-3">{roles.map(([id,ar,en,Icon]:any)=><label key={id} className="flex items-center gap-3 rounded-xl border p-4"><Icon className="h-6 w-6 text-teal-600"/><span className="flex-1"><b>{tr(ar,en)}</b><small className="block text-slate-500">{id==='marketing'?tr('تقرير استثمار ومساحات إعلانية كل 3 أيام','Investment and ad-space report every 3 days'):id==='privacy_video'?tr('رقابة سلامة وخصوصية الجلسات المرئية بموافقة المستخدم','Safety/privacy oversight for video sessions with user consent'):tr('صلاحيات إشراف وتدقيق قابلة للتدقيق','Auditable supervisory permissions')}</small></span><input type="checkbox" checked={!!enabled[id]} onChange={e=>setEnabled(x=>({...x,[id]:e.target.checked}))}/></label>)}</div></section>
 <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">{tr('المؤشرات والزوار','Site counters')}</h2><div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{tr('الأرقام التجريبية موسومة كتجريبية ولا تُعرض على أنها أرقام حقيقية. وضع الحقيقة يعتمد على بيانات التحليلات الفعلية.','Demo numbers are explicitly marked as demo; real mode must use verified analytics data.')}</div><div className="mt-4 flex gap-2"><button onClick={()=>setMode('real')} className={'rounded-xl px-4 py-2 '+(mode==='real'?'bg-emerald-600 text-white':'bg-slate-100')}>{tr('الحقيقي','Real')}</button><button onClick={()=>setMode('demo')} className={'rounded-xl px-4 py-2 '+(mode==='demo'?'bg-indigo-600 text-white':'bg-slate-100')}>{tr('تجريبي','Demo')}</button></div><div className="mt-4 grid grid-cols-3 gap-3">{[['online','المتصلون الآن',BarChart3],['doctors','الأطباء',Stethoscope],['visitors','الزوار',Wallet]].map(([k,l,I]:any)=><label key={k} className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">{tr(l,l)}</span><I className="my-2 h-5 w-5 text-indigo-600"/><input className="w-full rounded-lg border p-2" type="number" value={(counter as any)[k]} onChange={e=>setCounter(x=>({...x,[k]:Number(e.target.value)}))}/></label>)}</div></section>
 </div>
 <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Lock className="text-emerald-600"/><div><h2 className="text-xl font-extrabold">{tr('بوابات الدفع والعمولات المؤجلة','Payment gateways & deferred platform commission')}</h2><p className="text-sm text-slate-500">{tr('يتم اختيار البوابة حسب بلد العميل، وتدخل مفاتيح API لاحقاً من الخادم.','Gateway selection is country-aware; API secrets are added server-side later.')}</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-4">{pay.map(([id,name,desc,url])=><div key={id} className="rounded-2xl border p-4"><b>{name}</b><p className="mt-2 text-sm text-slate-600">{desc}</p><a className="mt-3 inline-block text-sm text-indigo-700 underline" href={url} target="_blank" rel="noreferrer">{tr('الموقع الرسمي','Official site')}</a><div className="mt-3 text-xs font-bold text-emerald-700">{tr('جاهز للربط التقني','Technical integration slot ready')}</div></div>)}</div><div className="mt-5 flex items-center gap-3"><label className="font-bold">{tr('عمولة المنصة %','Platform fee %')}<input className="ms-3 w-24 rounded-xl border p-2" type="number" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label><span className="text-sm text-slate-500">{tr('تُحسب في طبقة الخادم لكل عملية ناجحة عند تفعيل بوابة حقيقية.','Applied server-side per successful transaction when a live gateway is enabled.')}</span></div></section>
 <button onClick={save} className="mt-6 rounded-xl bg-teal-600 px-6 py-3 font-bold text-white"><Save className="inline h-4 w-4 me-2"/>{saved?tr('تم الحفظ','Saved'):tr('حفظ إعدادات المالك','Save owner settings')}</button>
 </div></div>
}