import { CreditCard, Globe2, LockKeyhole, WalletCards } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useRouter } from '@/lib/router';
import { lt } from '@/lib/featureText';

const providers=[
 {name:'Россия',items:['ЮMoney','SBP / СБП','Банковская карта']},
 {name:'العالم العربي',items:['بطاقة بنكية','تحويل مصرفي','محافظ إلكترونية']},
 {name:'مصر',items:['فوري','بطاقة بنكية','محافظ إلكترونية']},
];
export default function PaymentsPage(){const {lang}=useI18n();const {navigate}=useRouter();return <div className="min-h-screen pt-24 pb-16 bg-gray-50"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center"><CreditCard className="mx-auto w-12 h-12 text-teal-600"/><h1 className="mt-4 text-3xl font-extrabold text-gray-800">{lt(lang,{ar:'الدفع لمرة واحدة',ru:'Разовая оплата',en:'One-time Payments',de:'Einmalzahlung'})}</h1><p className="mt-2 text-gray-500">{lt(lang,{ar:'شراء كورس أو امتحان أو جلسة بدون اشتراك شهري.',ru:'Покупка курса, экзамена или сессии без ежемесячной подписки.',en:'Buy a course, exam or session without a monthly subscription.',de:'Kurs, Prüfung oder Sitzung ohne Monatsabo kaufen.'})}</p></div><div className="mt-8 grid gap-5 md:grid-cols-3">{providers.map(p=><div key={p.name} className="card p-6"><div className="flex items-center gap-3"><Globe2 className="w-6 h-6 text-teal-600"/><h2 className="font-bold text-gray-800">{p.name}</h2></div><div className="mt-4 space-y-2">{p.items.map(item=><button key={item} onClick={()=>navigate('/courses')} className="w-full rounded-xl border p-3 text-left text-sm hover:border-teal-400 hover:bg-teal-50">{item}</button>)}</div></div>)}</div><div className="mt-7 rounded-3xl bg-white border p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h2 className="font-bold text-gray-800">{lt(lang,{ar:'حماية الدفع',ru:'Безопасность оплаты',en:'Payment Security',de:'Zahlungssicherheit'})}</h2><p className="mt-1 text-sm text-gray-500">{lt(lang,{ar:'الدفع الحقيقي يحتاج ربط مزود معتمد وحساب تاجر. هذه الواجهة جاهزة للربط، لكنها لا تنفذ عمليات مالية حقيقية وحدها.',ru:'Для реальных платежей требуется подключение одобренного провайдера и торгового аккаунта. Интерфейс готов к интеграции.',en:'Real payments require an approved provider and merchant account. This UI is ready for integration.',de:'Echte Zahlungen benötigen einen freigegebenen Anbieter und Händlerzugang. Diese Oberfläche ist integrationsbereit.'})}</p></div><div className="rounded-2xl bg-teal-50 p-4 text-teal-700"><LockKeyhole className="w-6 h-6"/></div></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><button onClick={()=>navigate('/courses')} className="btn-primary"><WalletCards className="w-4 h-4"/>{lt(lang,{ar:'اختر كورسًا',ru:'Выбрать курс',en:'Choose a course',de:'Kurs wählen'})}</button><button onClick={()=>navigate('/exams')} className="btn-secondary">{lt(lang,{ar:'اختبار تدريبي',ru:'Тренировочный экзамен',en:'Practice exam',de:'Übungsprüfung'})}</button></div></div></div>;
}
