import { useEffect,useState } from 'react';
import { LockKeyhole,Wallet,Video,ShieldCheck,RefreshCw,LogIn } from 'lucide-react';
import { useI18n } from '@/lib/i18n';import { supabase } from '@/lib/supabase';import { loadPrivateNotifications,markPrivateRead,NotificationItem } from '@/lib/notifications';
const icons:any={wallet:Wallet,booking:Video,account:ShieldCheck,message:LockKeyhole};
export default function PrivateNotificationsPage(){
 const {lang,dir}=useI18n();const [user,setUser]=useState<any>(null);const [items,setItems]=useState<NotificationItem[]>([]);const [loading,setLoading]=useState(true);
 const load=async()=>{const {data}=await supabase.auth.getUser();setUser(data.user);if(data.user)setItems(await loadPrivateNotifications(lang,data.user.id));setLoading(false)};useEffect(()=>{load();const id=setInterval(load,20000);return()=>clearInterval(id)},[lang]);
 const title=lang==='ar'?'الإشعارات الحسابية الخاصة':lang==='ru'?'Личные защищённые уведомления':lang==='de'?'Private geschützte Benachrichtigungen':'Private Protected Notifications';
 if(!user)return <section dir={dir} className="min-h-screen bg-slate-50 py-16"><div className="mx-auto max-w-xl px-4"><div className="rounded-3xl bg-white border p-8 text-center shadow-xl"><LockKeyhole className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-4 text-2xl font-extrabold">{title}</h1><p className="mt-3 text-slate-500">{lang==='ar'?'هذه القائمة خاصة بصاحب الحساب ولا تظهر للزوار. سجّل الدخول للوصول إليها.':'This area is private to the account owner. Sign in to access it.'}</p><a href="/register" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white"><LogIn className="h-4 w-4"/> {lang==='ar'?'تسجيل الدخول / إنشاء حساب':'Sign in / Create account'}</a></div></div></section>;
 return <section dir={dir} className="min-h-screen bg-slate-50 py-10"><div className="mx-auto max-w-4xl px-4"><div className="rounded-3xl bg-gradient-to-br from-emerald-700 to-teal-600 p-7 text-white shadow-lg"><div className="flex items-center gap-4"><div className="rounded-2xl bg-white/15 p-3"><LockKeyhole className="h-8 w-8"/></div><div><h1 className="text-2xl font-extrabold">{title}</h1><p className="mt-1 text-sm text-white/85">{lang==='ar'?'مفصولة عن المجتمع وتُعرض وفق هوية الحساب فقط.': 'Separated from community notifications and scoped to your account.'}</p></div><button onClick={load} className="ms-auto rounded-xl bg-white/15 p-3"><RefreshCw className={loading?'animate-spin':''}/></button></div></div><div className="mt-5 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-900"><strong>🔐 {lang==='ar'?'حماية البيانات':'Data protection'}:</strong> {lang==='ar'?'الاستعلام الخاص مرتبط بمعرّف المستخدم ولا يُعرض ضمن قائمة المجتمع. عند تشغيل Supabase تُفرض حماية الصفوف RLS على قاعدة البيانات.':'Private records are scoped to the authenticated user; Supabase RLS protects database rows when enabled.'}</div><div className="mt-5 space-y-3">{items.map(n=>{const Icon=icons[n.kind]||LockKeyhole;return <button onClick={()=>{markPrivateRead(n.id,user.id);setItems(x=>x.map(v=>v.id===n.id?{...v,read:true}:v));if(n.href)window.location.href=n.href}} key={n.id} className={'flex w-full gap-4 rounded-2xl border bg-white p-5 text-start shadow-sm '+(!n.read?'ring-2 ring-emerald-100':'')}><div className="h-11 w-11 shrink-0 rounded-xl bg-emerald-50 text-emerald-700 grid place-items-center"><Icon/></div><div className="min-w-0 flex-1"><h2 className="font-bold text-slate-900">{n.title}</h2><p className="mt-1 text-sm leading-7 text-slate-600">{n.body}</p><time className="mt-2 block text-xs text-slate-400">{new Date(n.created_at).toLocaleString()}</time></div>{!n.read&&<span className="mt-2 h-2.5 w-2.5 rounded-full bg-emerald-500"/>}</button>})}</div></div></section>
}