import {useEffect,useMemo,useRef,useState} from 'react';
import {Album,CalendarClock,Copy,ExternalLink,FileText,Heart,Home,MessageCircle,QrCode,Settings,Share2,Smartphone,Wallet,Video,GraduationCap,Award,ShoppingBag,BriefcaseBusiness} from 'lucide-react';
import PageProfileTools from '@/components/PageProfileTools';
import ProfessionalCreateStudio from '@/components/ProfessionalCreateStudio';
import ProfessionalSocialHub from '@/components/ProfessionalSocialHub';
import {getRole,type SB1Role} from '@/lib/access';

type Tab={id:string;label:string;icon:any;ownerOnly?:boolean};
const read=(k:string,f='')=>typeof window==='undefined'?f:localStorage.getItem(k)||f;
const roleName:Record<SB1Role,string>={guest:'زائر',client:'عميل',specialist:'أخصائي',institution:'مؤسسة',delivery_worker:'عامل توصيل',property_owner:'صاحب منشأة',moderator:'مشرف',owner:'مالك'};
function makeTabs(role:SB1Role,manage:boolean):Tab[]{const common=[{id:'home',label:'الرئيسية',icon:Home},{id:'posts',label:'منشوراتي',icon:FileText,ownerOnly:true},{id:'favorites',label:'مفضلتي',icon:Heart,ownerOnly:true},{id:'albums',label:'ألبوماتي',icon:Album,ownerOnly:true},{id:'social',label:'منصات التواصل',icon:ExternalLink},{id:'phone',label:'الهاتف وQR',icon:Smartphone}];if(role==='specialist')return[{id:'home',label:'الرئيسية',icon:Home},{id:'sessions',label:'جلساتي',icon:CalendarClock,ownerOnly:true},{id:'articles',label:'مقالتي',icon:FileText},{id:'questions',label:'الأسئلة',icon:MessageCircle},{id:'recordings',label:'تسجيلاتي',icon:Video},{id:'courses',label:'الدورات والكورسات',icon:GraduationCap},{id:'certificates',label:'شهاداتي',icon:Award},...common.slice(1),{id:'appointments',label:'مواعيدي',icon:CalendarClock,ownerOnly:true}];if(role==='institution')return[{id:'home',label:'الرئيسية',icon:Home},{id:'products',label:'الأدوية',icon:ShoppingBag},{id:'services',label:'خدماتي',icon:BriefcaseBusiness},{id:'courses',label:'دوراتي',icon:GraduationCap},...common.slice(1),...(manage?[{id:'settings',label:'الإعدادات',icon:Settings}]:[])];return[...common,...(manage?[{id:'settings',label:'الإعدادات',icon:Settings}]:[])];}
function Notice({title,text}:{title:string;text:string}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></section>}
export default function ProfilePage(){
 const role=getRole();const manage=['client','specialist','institution','delivery_worker','owner','moderator'].includes(role);const id=read('sb1_account_user_id','profile');const name=read('sb1_account_name',read('chat_name','صفحة SB1'));const avatar=read('sb1_account_avatar',read('chat_photo',''));
 const all=useMemo(()=>makeTabs(role,manage),[role,manage]);const visible=all.filter(t=>!t.ownerOnly||manage);const [active,setActive]=useState('home');const navRef=useRef<HTMLElement|null>(null);const [pinned,setPinned]=useState(false);
 useEffect(()=>{const f=()=>setPinned(!!navRef.current&&navRef.current.getBoundingClientRect().top<=1);f();addEventListener('scroll',f,{passive:true});addEventListener('resize',f);return()=>{removeEventListener('scroll',f);removeEventListener('resize',f)}},[]);
 const select=(x:string)=>{setActive(x);requestAnimationFrame(()=>document.getElementById('profile-content')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 return <div dir="rtl" className="min-h-screen bg-slate-50"><div className="mx-auto max-w-[1500px] px-2 sm:px-4 lg:px-6"><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_235px]">
 <main className="min-w-0"><section className="rounded-2xl border bg-white shadow-sm"><div className="p-5 flex items-center gap-3"><div className="h-20 w-20 overflow-hidden rounded-full border-4 border-white bg-teal-100 shadow">{avatar?<img src={avatar} className="h-full w-full object-cover" alt=""/>:<div className="grid h-full place-items-center text-2xl font-black text-teal-700">{name[0]}</div>}</div><div className="min-w-0 flex-1"><h1 className="truncate text-xl font-black">{name}</h1><p className="text-sm text-slate-500">{roleName[role]}</p></div><button className="rounded-xl border p-2"><Share2 className="h-4 w-4"/></button></div></section>
 <nav ref={navRef as any} className="sticky top-0 z-40 mt-2 overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex min-h-12 gap-1 overflow-x-auto p-1">{visible.map(t=>{const I=t.icon;return <button key={t.id} onClick={()=>select(t.id)} className={'flex shrink-0 items-center gap-1.5 rounded-lg px-3 py-2 text-[13px] font-bold '+(active===t.id?'bg-teal-700 text-white':'text-slate-700 hover:bg-teal-50 active:bg-slate-200')}><I className="h-4 w-4"/>{t.label}</button>})}</div></nav>
 <div id="profile-content" className="mt-3 space-y-3">
 {active==='home'&&<><ProfessionalCreateStudio pageId={id} pageName={name} pageAvatar={avatar||undefined}/><PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="home"/></>}
 {active==='social'&&<ProfessionalSocialHub/>}
 {active==='posts'&&<PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="home" onlyOwn/>}
 {active==='albums'&&<PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="albums"/>}
 {active==='favorites'&&<PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="albums"/>}
 {active==='phone'&&<PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="phone"/>}
 {active==='settings'&&<PageProfileTools canManage={manage} pageId={id} pageName={name} pageAvatar={avatar||undefined} focusSection="settings"/>}
 {['sessions','appointments'].includes(active)&&<Notice title={active==='sessions'?'جلساتي':'مواعيدي وجدول أعمالي'} text="هذا القسم خاص بصاحب الحساب والمخولين، وتظهر فيه الجلسات والمواعيد المرتبطة فعلياً بالحساب."/>}
 {['articles','questions','recordings','courses','certificates'].includes(active)&&<Notice title={visible.find(x=>x.id===active)?.label||''} text="المحتوى المرتبط بالحساب يظهر هنا من بيانات SB1 الفعلية."/>}
 {['products','services'].includes(active)&&<Notice title={active==='products'?'الأدوية':'خدماتي'} text="هذا القسم مخصص لربط منتجات وخدمات الحساب بأقسام SB1 الفعلية دون اختراع بيانات منفصلة."/>}
 </div></main>
 <aside className={(pinned?'sticky top-14':'self-start')+' hidden xl:block'}><div className="space-y-2 border-r border-slate-200 pr-3">{manage&&<><button onClick={()=>select('wallet')} className="flex w-full items-center gap-2 rounded-xl bg-black px-3 py-3 text-sm font-extrabold text-white"><Wallet className="h-4 w-4"/>الحساب والمحفظة</button>{(role==='owner'||role==='specialist')&&<button onClick={()=>select('clone')} className="flex w-full items-center gap-2 rounded-xl bg-emerald-100 px-3 py-3 text-sm font-extrabold text-emerald-800"><Copy className="h-4 w-4"/>الاستنساخ</button>}{role==='specialist'&&<button onClick={()=>select('appointments')} className="flex w-full items-center gap-2 rounded-xl border bg-white px-3 py-3 text-sm font-extrabold"><CalendarClock className="h-4 w-4"/>جدول أعمالي</button>}<div className="rounded-xl border bg-white p-2">{visible.filter(t=>['home','favorites','albums','social','phone','settings'].includes(t.id)).map(t=>{const I=t.icon;return <button key={t.id} onClick={()=>select(t.id)} className="flex w-full items-center gap-2 border-b px-3 py-3 text-sm font-bold last:border-0"><I className="h-4 w-4"/>{t.label}</button>})}</div><div className="rounded-xl border bg-white p-3"><div className="mb-2 flex items-center gap-2 text-xs font-black"><QrCode className="h-4 w-4 text-teal-700"/>QR الحساب</div><img src={'https://api.qrserver.com/v1/create-qr-code/?size=220x220&data='+encodeURIComponent(location.origin+'/profile?account='+id)} className="mx-auto h-40 w-40 rounded-lg" alt="QR"/><p className="mt-2 text-center text-[10px] text-slate-500">ظاهر للمالك والمخولين فقط</p></div></>}{!manage&&<div className="rounded-xl border bg-white p-4 text-sm text-slate-500">أدوات الحساب الخاصة لا تظهر للزوار.</div>}</div></aside>
 </div></div></div>
}