import {useEffect,useMemo,useState} from 'react';
import {Building2,MapPin,Plus,Upload,Video,Image as ImageIcon} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {virtualFacilities,countriesForLanguage} from '@/lib/catalog';

type Listing={id:string;mode:'sale'|'rent';name:string;country:string;city:string;address:string;description:string;price:string;images:string[];video?:string};
const KEY='sb1_property_listings';
export default function PropertyListingsPage(){
 const {lang,dir}=useI18n();const countries=countriesForLanguage(lang);const [mode,setMode]=useState<'all'|'sale'|'rent'>('all');const [country,setCountry]=useState(countries[0]?.key||'');const [show,setShow]=useState(false);const [items,setItems]=useState<Listing[]>([]);
 const [form,setForm]=useState({mode:'sale' as 'sale'|'rent',name:'',city:'',address:'',description:'',price:''});const [images,setImages]=useState<string[]>([]);const [video,setVideo]=useState('');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||'[]'))}catch{}},[]);
 const demo=useMemo(()=>virtualFacilities(lang,country).filter((x:any)=>x.facility_type==='property').map((x:any)=>({id:x.id,mode:x.property_mode||'sale',name:x.name,country:x.country,city:x.city,address:x.address,description:x.description,price:String(x.price||''),images:x.gallery_urls||[],video:x.video_url||''})),[lang,country]);
 const list=[...items.filter(x=>!country||x.country===country),...demo].filter(x=>mode==='all'||x.mode===mode);
 const read=(file:File,cb:(v:string)=>void)=>{const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsDataURL(file)};
 const save=()=>{if(!form.name||!form.description)return;const x:Listing={id:'local-'+Date.now(),...form,country,images,video};const next=[x,...items];setItems(next);localStorage.setItem(KEY,JSON.stringify(next));setShow(false);setForm({mode:'sale',name:'',city:'',address:'',description:'',price:''});setImages([]);setVideo('')};
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-slate-800 to-teal-700 p-8 text-white"><h1 className="text-3xl font-extrabold">أماكن للبيع أو الإيجار</h1><p className="mt-2">مساحات وعيادات ومراكز وأماكن صحية يمكن عرضها للبيع أو الإيجار. يمكن لصاحب المكان رفع الصور والفيديو والشرح.</p></div>
  <div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setMode('all')} className={'rounded-xl px-4 py-2 '+(mode==='all'?'bg-teal-600 text-white':'bg-white border')}>الكل</button><button onClick={()=>setMode('sale')} className={'rounded-xl px-4 py-2 '+(mode==='sale'?'bg-teal-600 text-white':'bg-white border')}>للبيع</button><button onClick={()=>setMode('rent')} className={'rounded-xl px-4 py-2 '+(mode==='rent'?'bg-teal-600 text-white':'bg-white border')}>للإيجار</button><select value={country} onChange={e=>setCountry(e.target.value)} className="rounded-xl border bg-white px-4 py-2">{countries.map(x=><option key={x.key} value={x.key}>{x.name} · {x.city}</option>)}</select><button onClick={()=>setShow(true)} className="ms-auto inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2 font-bold text-white"><Plus className="h-4 w-4"/>أضف مكانك</button></div>
  {show&&<div className="mt-5 rounded-2xl bg-white border p-5 shadow-sm"><h2 className="text-xl font-extrabold">إضافة مكان للبيع أو الإيجار</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as any})} className="rounded-xl border p-3"><option value="sale">للبيع</option><option value="rent">للإيجار</option></select><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="اسم المكان" className="rounded-xl border p-3"/><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="المدينة" className="rounded-xl border p-3"/><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="العنوان" className="rounded-xl border p-3"/><input value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="السعر" className="rounded-xl border p-3"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="شرح المكان والخدمات والاستخدامات" className="rounded-xl border p-3 md:col-span-2 min-h-28"/><label className="rounded-xl border border-dashed p-4 cursor-pointer"><ImageIcon className="h-5 w-5"/><span className="text-sm">رفع صور المكان</span><input type="file" accept="image/*" multiple className="hidden" onChange={e=>{Array.from(e.target.files||[]).forEach(f=>read(f,v=>setImages(a=>[...a,v])))}}/></label><label className="rounded-xl border border-dashed p-4 cursor-pointer"><Video className="h-5 w-5"/><span className="text-sm">رفع فيديو للمكان</span><input type="file" accept="video/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)read(f,setVideo)}}/></label></div><div className="mt-4 flex gap-2"><button onClick={save} className="rounded-xl bg-teal-700 px-5 py-2 font-bold text-white">حفظ الإعلان</button><button onClick={()=>setShow(false)} className="rounded-xl border px-5 py-2">إلغاء</button></div></div>}
  <div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map((x:any)=><article key={x.id} className="overflow-hidden rounded-2xl bg-white border shadow-sm"><div className="h-48 bg-gray-100">{x.images?.[0]?<img src={x.images[0]} className="h-full w-full object-cover" alt={x.name}/>:<div className="h-full grid place-items-center text-gray-400"><Building2 className="h-10 w-10"/></div>}</div><div className="p-5"><div className="flex justify-between gap-2"><h3 className="font-extrabold">{x.name}</h3><span className="rounded-lg bg-teal-50 px-2 py-1 text-xs font-bold text-teal-700">{x.mode==='sale'?'للبيع':'للإيجار'}</span></div><p className="mt-2 text-sm text-gray-600">{x.description}</p><p className="mt-2 text-sm text-gray-500"><MapPin className="inline h-4 w-4"/> {x.city} · {x.address}</p>{x.price&&<p className="mt-2 font-bold">{x.price}</p>}{x.video&&<video controls className="mt-3 w-full rounded-xl" src={x.video}/>}</div></article>)}</div>
 </div></div>;
}