import { useMemo,useEffect,useState } from 'react';
import { ArrowRight,MessageCircle,Eye,User,ThumbsUp } from 'lucide-react';
import { useRouter } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import { virtualQuestionsForSpecialty,virtualAnswersForQuestion } from '@/lib/catalog';
import { DemoAccountMark } from '@/components/DemoTransparencyNotice';
import { demoQuestions } from '@/lib/demoData';
const UI:any={ar:{missing:'السؤال غير موجود في هذه اللغة.',back:'العودة للأسئلة',answers:'إجابات'},en:{missing:'Question not found in this language.',back:'Back to questions',answers:'answers'},de:{missing:'Frage in dieser Sprache nicht gefunden.',back:'Zurück zu Fragen',answers:'Antworten'},ru:{missing:'Вопрос на этом языке не найден.',back:'Назад к вопросам',answers:'ответов'},uk:{missing:'Запитання цією мовою не знайдено.',back:'Назад до запитань',answers:'відповідей'},uz:{missing:'Bu tildagi savol topilmadi.',back:'Savollarga qaytish',answers:'javob'},hy:{missing:'Այս լեզվով հարցը չի գտնվել։',back:'Վերադառնալ հարցերին',answers:'պատասխան'},tg:{missing:'Савол бо ин забон ёфт нашуд.',back:'Бозгашт ба саволҳо',answers:'ҷавоб'},az:{missing:'Bu dildə sual tapılmadı.',back:'Suallara qayıt',answers:'cavab'},am:{missing:'በዚህ ቋንቋ ጥያቄ አልተገኘም።',back:'ወደ ጥያቄዎች',answers:'መልሶች'},ka:{missing:'ამ ენაზე კითხვა ვერ მოიძებნა.',back:'კითხვებზე დაბრუნება',answers:'პასუხი'}};
export default function QuestionDetailPage({id}:{id:string}){const {navigate}=useRouter();const {lang,dir}=useI18n();const ui=UI[lang]||UI.en;const [localQuestion,setLocalQuestion]=useState<any>(null);useEffect(()=>{try{const all=JSON.parse(localStorage.getItem('sb1_demo_questions')||'[]');setLocalQuestion(all.find((x:any)=>x.id===id)||null)}catch{}},[id]);const match=id.match(/^catalog-q-([^-]+)-(.+)-(\d+)$/);const slug=match?.[2]||comprehensiveSpecialties[0].slug;const question=virtualQuestionsForSpecialty(slug,lang,50).find(q=>q.id===id)||localQuestion||demoQuestions.find(q=>q.id===id)||null;const answers=useMemo(()=>question?virtualAnswersForQuestion(question,lang,12):[],[question,lang]);if(!question)return <div className="min-h-screen pt-28 text-center" dir={dir}><p className="text-gray-500">{ui.missing}</p><button onClick={()=>navigate('/questions')} className="mt-4 rounded-xl bg-teal-600 text-white px-5 py-3">{ui.back}</button></div>;return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir={dir}><div className="mx-auto max-w-3xl px-4"><button onClick={()=>navigate('/questions')} className="mb-5 flex items-center gap-2 text-sm text-gray-500"><ArrowRight className="h-4 w-4"/>{ui.back}</button><div className="rounded-2xl bg-white border p-7"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">{question.specialty?.name}</span><h1 className="mt-4 text-2xl font-extrabold text-gray-900">{question.title}</h1><p className="mt-4 leading-8 text-gray-600">{question.body}</p><div className="mt-5 flex gap-4 text-xs text-gray-400"><span>{question.author_name}</span><span><Eye className="inline h-4 w-4"/> {question.views}</span></div></div><h2 className="mt-8 mb-4 text-xl font-extrabold flex items-center gap-2"><MessageCircle className="text-teal-600"/> {answers.length} {ui.answers}</h2><div className="space-y-4">{answers.map(a=><div key={a.id} className="rounded-2xl bg-white border p-6"><div className="flex items-start gap-3"><div className="relative h-11 w-11 rounded-full bg-teal-50 flex items-center justify-center"><User className="text-teal-600"/><DemoAccountMark className="absolute -end-1 -top-1 h-3.5 w-3.5"/></div><div><b>{a.doctor?.name}</b><p className="mt-3 leading-7 text-gray-600">{a.body}</p><span className="mt-3 inline-flex items-center gap-1 text-xs text-gray-400"><ThumbsUp className="h-3.5 w-3.5"/>{a.helpful_count}</span></div></div></div>)}</div></div></div>}