import { useMemo } from 'react';
import { ArrowRight,MessageCircle,Eye,User,ThumbsUp,Languages,SpellCheck,Send } from 'lucide-react';
import { useRouter } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import { virtualQuestionsForSpecialty,virtualAnswersForQuestion } from '@/lib/catalog';
import { supabase } from '@/lib/supabase';
import { useEffect,useState } from 'react';
import { correctText,translateText } from '@/lib/translator';
import { moderateAndLog, calculateAnswerEarnings } from '@/lib/questionEconomy';
export default function QuestionDetailPage({id}:{id:string}){
 const {navigate}=useRouter();const {lang,dir}=useI18n(); const labels:any={ar:{back:'العودة للأسئلة',answers:'إجابات تجريبية',notfound:'السؤال غير موجود في هذه اللغة.'},ru:{back:'Назад к вопросам',answers:'демонстрационных ответов',notfound:'Вопрос не найден на этом языке.'},en:{back:'Back to questions',answers:'demo answers',notfound:'Question not found in this language.'},de:{back:'Zurück zu den Fragen',answers:'Demo-Antworten',notfound:'Frage in dieser Sprache nicht gefunden.'}}[lang as any]||{back:'Back to questions',answers:'demo answers',notfound:'Question not found.'};
 const match=id.match(/^catalog-q-([^-]+)-(.+)-(\d+)$/);const slug=match?.[2]||comprehensiveSpecialties[0].slug;
 const questions=virtualQuestionsForSpecialty(slug,lang,50);const [dbQuestion,setDbQuestion]=useState<any>(null);const [dbAnswers,setDbAnswers]=useState<any[]>([]);const [followups,setFollowups]=useState<any[]>([]);const [followup,setFollowup]=useState('');const [sendingFollowup,setSendingFollowup]=useState(false);useEffect(()=>{supabase.from('questions').select('*, specialty(*), answers(*, doctor(*))').eq('id',id).maybeSingle().then(({data})=>{if(data){const tr=data.translations?.[lang]||{};setDbQuestion({...data,title:tr.title||data.title,body:tr.body||data.body});setDbAnswers(data.answers||[])}}).catch(()=>{});supabase.from('question_followups').select('*').eq('question_id',id).order('created_at').then(({data})=>setFollowups(data||[])).catch(()=>{})},[id,lang]);const localQuestions=(JSON.parse(localStorage.getItem('sb1_demo_questions')||'[]') as any[]);const question=questions.find(q=>q.id===id)||localQuestions.find(q=>q.id===id&&(!q.language||q.language===lang))||dbQuestion||null;
 const answers=useMemo(()=>dbAnswers.length?dbAnswers:(question?virtualAnswersForQuestion(question,lang,20):[]),[question,lang,dbAnswers]);
 const [selectedAnswers,setSelectedAnswers]=useState<Record<string,boolean>>(()=>JSON.parse(localStorage.getItem('sb1_selected_answers_'+id)||'{}')); const [ratings,setRatings]=useState<Record<string,number>>(()=>JSON.parse(localStorage.getItem('sb1_answer_ratings_'+id)||'{}')); const [comments,setComments]=useState<any[]>(()=>JSON.parse(localStorage.getItem('sb1_question_comments_'+id)||'[]')); const [commentText,setCommentText]=useState(''); const [answerMode,setAnswerMode]=useState(false); const [answerText,setAnswerText]=useState(''); const [answerLang,setAnswerLang]=useState(lang); const [targetLang,setTargetLang]=useState(lang); const [translatedAnswer,setTranslatedAnswer]=useState(''); const [busyTranslate,setBusyTranslate]=useState(false); const [sentAnswer,setSentAnswer]=useState<any[]>([]);
 const selectedCount=Object.values(selectedAnswers).filter(Boolean).length;
 const toggleAnswer=async(answer:any)=>{if(!answer?.id)return;if(selectedAnswers[answer.id]){const next={...selectedAnswers};delete next[answer.id];setSelectedAnswers(next);localStorage.setItem('sb1_selected_answers_'+id,JSON.stringify(next));return;}if(selectedCount>=3)return;const next={...selectedAnswers,[answer.id]:true};setSelectedAnswers(next);localStorage.setItem('sb1_selected_answers_'+id,JSON.stringify(next));try{await supabase.from('question_answer_selections').insert({question_id:id,answer_id:answer.id,doctor_id:answer.doctor_id||answer.doctor?.id,selected_by:'customer',created_at:new Date().toISOString()});await supabase.from('sb1_notifications').insert({recipient_id:answer.doctor_id||answer.doctor?.id,type:'answer_selected',title:'تم اختيار إجابتك',body:'تم اختيار إجابتك ضمن أفضل 3 إجابات للسؤال.',question_id:id,created_at:new Date().toISOString()});}catch{}};
 const rateAnswer=async(answer:any,stars:number)=>{const next={...ratings,[answer.id]:stars};setRatings(next);localStorage.setItem('sb1_answer_ratings_'+id,JSON.stringify(next));try{await supabase.from('question_answer_ratings').insert({question_id:id,answer_id:answer.id,stars,created_at:new Date().toISOString()});}catch{}};
 const addQuestionComment=async()=>{const body=commentText.trim();if(!body)return;const mod=await moderateAndLog('question_comment',id,body,localStorage.getItem('chat_name')||'مستخدم');if(!mod.allowed){alert(lang==='ar'?'التعليق يخالف سياسة SB1':'Comment violates SB1 policy');return;}const item={id:'comment-'+Date.now(),question_id:id,author_name:localStorage.getItem('chat_name')||'مستخدم',body,role:'customer_or_specialist',created_at:new Date().toISOString()};const next=[...comments,item];setComments(next);localStorage.setItem('sb1_question_comments_'+id,JSON.stringify(next));try{await supabase.from('question_comments').insert(item);}catch{}setCommentText('');};
 const runCorrection=()=>setAnswerText(correctText(answerText,answerLang));
 const runTranslation=async()=>{setBusyTranslate(true);setTranslatedAnswer(await translateText(answerText,answerLang,targetLang));setBusyTranslate(false)};
 const publishAnswer=async()=>{const body=translatedAnswer||correctText(answerText,answerLang);if(!body.trim())return;const demo={id:'local-answer-'+Date.now(),body,helpful_count:0,doctor:{name:'أخصائي SB1',photo_url:null},language:targetLang};try{await supabase.from('answers').insert({question_id:id,body,language_code:targetLang,status:'published'});}catch{}setSentAnswer(x=>[demo,...x]);setAnswerText('');setTranslatedAnswer('');};
 const submitFollowup=async()=>{if(!followup.trim()||sendingFollowup)return;setSendingFollowup(true);const item={question_id:id,sender_type:'patient',body:followup.trim(),created_at:new Date().toISOString()};try{const {data}=await supabase.from('question_followups').insert(item).select().single();setFollowups(x=>[...x,data||item]);}catch{setFollowups(x=>[...x,item]);}setFollowup('');setSendingFollowup(false)}; if(!question)return <div className="min-h-screen pt-28 text-center" dir={dir}><p className="text-gray-500">السؤال غير موجود في هذه اللغة.</p><button onClick={()=>navigate('/questions')} className="mt-4 rounded-xl bg-teal-600 text-white px-5 py-3">العودة للأسئلة</button></div>;
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir={dir}><div className="mx-auto max-w-3xl px-4">
  <button onClick={()=>navigate('/questions')} className="mb-5 flex items-center gap-2 text-sm text-gray-500"><ArrowRight className="h-4 w-4"/>العودة للأسئلة</button>
  <div className="rounded-2xl bg-white border p-7"><div className="flex items-center gap-3 mb-4"><img src={(question as any).author_avatar || `https://api.dicebear.com/9.x/personas/svg?seed=${encodeURIComponent(question.author_name)}`} className="h-12 w-12 rounded-full border object-cover"/><div><b>{question.author_name}</b><p className="text-xs text-gray-400">{question.language || lang}</p></div></div><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">{question.specialty?.name}</span><h1 className="mt-4 text-2xl font-extrabold text-gray-900">{question.title}</h1><p className="mt-4 leading-8 text-gray-600">{question.body}</p><div className="mt-5 flex gap-4 text-xs text-gray-400"><span>{question.author_name}</span><span><Eye className="inline h-4 w-4"/> {question.views}</span></div></div>
  <h2 className="mt-8 mb-4 text-xl font-extrabold flex items-center gap-2"><MessageCircle className="text-teal-600"/> {answers.length} إجابات تجريبية</h2>
  <div className="mb-4 rounded-2xl border border-teal-100 bg-teal-50 p-4 text-sm text-teal-800">اختر 3 إجابات أعجبتك. بعد الاختيار تصبح الإجابات المختارة ظاهرة للجميع ويتم إشعار الأخصائي، ثم قيّم كل إجابة من 1 إلى 5 نجوم.</div>
  <div className="space-y-4">{[...sentAnswer,...answers].map(a=><div key={a.id} className={"rounded-2xl bg-white border p-6 "+(selectedAnswers[a.id]?'border-teal-500 ring-1 ring-teal-200':'')}><div className="flex items-start gap-3"><img src={a.doctor?.photo_url || `https://api.dicebear.com/9.x/personas/svg?seed=${encodeURIComponent(a.doctor?.name||'specialist')}`} className="h-11 w-11 rounded-xl object-cover border"/><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><b>{a.doctor?.name}</b>{selectedAnswers[a.id]&&<span className="rounded-full bg-teal-100 px-3 py-1 text-xs font-bold text-teal-700">إجابة مختارة</span>}</div><p className="mt-3 leading-7 text-gray-600">{a.body}</p><div className="mt-4 flex flex-wrap items-center gap-2"><button onClick={()=>toggleAnswer(a)} disabled={!selectedAnswers[a.id]&&selectedCount>=3} className={"rounded-xl px-3 py-2 text-xs font-bold "+(selectedAnswers[a.id]?'bg-teal-600 text-white':'bg-gray-100 text-gray-700 disabled:opacity-40')}>{selectedAnswers[a.id]?'إلغاء الاختيار':`اختيار الإجابة (${selectedCount}/3)`}</button><span className="text-xs text-gray-400">تقييم العميل:</span>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>rateAnswer(a,n)} className={"text-xl "+((ratings[a.id]||0)>=n?'text-amber-400':'text-gray-300')}>★</button>)}</div><span className="mt-3 inline-flex items-center gap-1 text-xs text-gray-400"><ThumbsUp className="h-3.5 w-3.5"/>{a.helpful_count||0}</span></div></div></div>)}</div>
  <div className="mt-6 rounded-2xl bg-white border p-6"><h3 className="font-extrabold">تعليقات على السؤال</h3><p className="mt-1 text-xs text-gray-500">التعليقات ليست إجابات ولا تدخل في حساب مستحقات الأخصائي.</p><div className="mt-4 space-y-2">{comments.map(x=><div key={x.id} className="rounded-xl bg-gray-50 p-3"><b className="text-sm">{x.author_name}</b><p className="mt-1 text-sm text-gray-700">{x.body}</p></div>)}</div><textarea value={commentText} onChange={e=>setCommentText(e.target.value)} className="input-field mt-4 min-h-24" placeholder="اكتب تعليقاً..."/><button onClick={addQuestionComment} className="btn-primary mt-2">إضافة تعليق</button></div>
 </div>  <div className="mt-8 rounded-2xl bg-white border p-6"><h2 className="text-lg font-extrabold text-gray-900">الرد على الأخصائي / سؤال متابعة</h2><p className="mt-1 text-sm text-gray-500">يمكنك الرد على الإجابة وطرح سؤال جديد متعلق بنفس الطلب.</p><div className="mt-4 space-y-3">{followups.map((f:any)=><div key={f.id||f.created_at} className="rounded-xl bg-gray-50 p-4"><div className="text-xs font-bold text-teal-700">{f.sender_type==='specialist'?'الأخصائي':'أنت'}</div><p className="mt-1 text-sm leading-7 text-gray-700">{f.body}</p></div>)}</div><textarea value={followup} onChange={e=>setFollowup(e.target.value)} className="input-field mt-4 min-h-28" placeholder="اكتب ردك أو سؤال المتابعة..." /><button onClick={submitFollowup} disabled={sendingFollowup||!followup.trim()} className="btn-primary mt-3 disabled:opacity-50">{sendingFollowup?'جارٍ الإرسال...':'إرسال الرد / سؤال المتابعة'}</button></div></div>;
}