import {useEffect,useMemo,useState} from 'react';
import {BarChart3,ShieldCheck,Share2,Bell,Download} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {calculateAnswerEarnings} from '@/lib/questionEconomy';

export default function QuestionAccountingPage(){
 const [ratings,setRatings]=useState<any[]>([]);const [selectedSupervisor,setSelectedSupervisor]=useState('');const [shared,setShared]=useState<any[]>([]);
 useEffect(()=>{Promise.all([supabase.from('question_answer_ratings').select('*'),supabase.from('question_report_shares').select('*')]).then(([a,s])=>{setRatings(a.data||[]);setShared(s.data||[])})},[]);
 const report=useMemo(()=>{const byQuestion:any={};ratings.forEach(r=>(byQuestion[r.question_id]??=[]).push(r));let gross=0,specialist=0;const rows=Object.entries(byQuestion).map(([question_id,rs]:any)=>{const totalPaid=Number(localStorage.getItem('sb1_question_paid_'+question_id)||'0')||10;const calc=calculateAnswerEarnings(totalPaid,rs.map((x:any)=>Number(x.stars)));const sp=calc.reduce((n,x)=>n+x.specialistAmount,0);gross+=totalPaid;specialist+=sp;return {question_id,totalPaid,site:totalPaid*.5,specialist:sp,ratings:rs.length,avg:rs.reduce((n:any,x:any)=>n+Number(x.stars),0)/rs.length};});return {rows,gross,site:gross*.5,specialist};},[ratings]);
 const share=async()=>{if(!selectedSupervisor)return;const item={id:'share-'+Date.now(),report_type:'question-accounting',supervisor_id:selectedSupervisor,shared_by:'owner',created_at:new Date().toISOString()};setShared(x=>[item,...x]);try{await supabase.from('question_report_shares').insert(item);await supabase.from('sb1_notifications').insert({recipient_id:selectedSupervisor,type:'report_shared',title:'تمت مشاركة تقرير الحسابات',body:'شارك المالك تقرير حسابات الأسئلة معك.',created_at:new Date().toISOString()});}catch{}};
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4"><div className="rounded-3xl bg-slate-900 p-8 text-white"><div className="flex items-center gap-3"><BarChart3/><div><h1 className="text-3xl font-black">حسابات الأسئلة المدفوعة</h1><p className="mt-2 text-white/70">50% للموقع و50% لصندوق الأخصائيين، وتوزيع صندوق الأخصائيين حسب تقييم العميل.</p></div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white border p-6"><span className="text-gray-500">إجمالي المدفوع</span><b className="mt-2 block text-3xl">{report.gross.toFixed(2)} USD</b></div><div className="rounded-2xl bg-white border p-6"><span className="text-gray-500">حصة الموقع 50%</span><b className="mt-2 block text-3xl text-teal-700">{report.site.toFixed(2)} USD</b></div><div className="rounded-2xl bg-white border p-6"><span className="text-gray-500">مستحقات الأخصائيين</span><b className="mt-2 block text-3xl text-indigo-700">{report.specialist.toFixed(2)} USD</b></div></div><section className="mt-6 rounded-2xl bg-white border p-6"><h2 className="text-xl font-extrabold">التقرير التفصيلي</h2><div className="overflow-x-auto mt-4"><table className="min-w-full text-sm"><thead><tr className="border-b text-start"><th className="p-3">السؤال</th><th>المدفوع</th><th>الموقع</th><th>الأخصائيون</th><th>متوسط التقييم</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.question_id} className="border-b"><td className="p-3">{r.question_id}</td><td>{r.totalPaid.toFixed(2)}</td><td>{r.site.toFixed(2)}</td><td>{r.specialist.toFixed(2)}</td><td>{r.avg.toFixed(1)} / 5</td></tr>)}</tbody></table></div></section><section className="mt-6 rounded-2xl bg-white border p-6"><div className="flex items-center gap-2"><ShieldCheck className="text-teal-600"/><h2 className="text-xl font-extrabold">مشاركة التقرير مع المشرفين</h2></div><div className="mt-4 flex flex-wrap gap-3"><select value={selectedSupervisor} onChange={e=>setSelectedSupervisor(e.target.value)} className="input-field max-w-sm"><option value="">اختر المشرف</option><option value="supervisor-1">مشرف SB1</option><option value="supervisor-2">المشرف المالي</option></select><button onClick={share} className="rounded-xl bg-teal-600 px-5 py-3 text-white font-bold"><Share2 className="inline h-4 w-4 me-1"/>مشاركة</button></div><div className="mt-4 space-y-2">{shared.map(x=><div key={x.id} className="rounded-xl bg-gray-50 p-3 text-sm">تمت مشاركة التقرير مع {x.supervisor_id} في {new Date(x.created_at).toLocaleString()}</div>)}</div></section></div></div>
}