import { useEffect,useMemo,useState } from 'react';
import { MessageCircle,ChevronLeft,Stethoscope } from 'lucide-react';
import { useRouter,parseQuery } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import QuestionCard from '@/components/QuestionCard';
import { specialtyCatalog,virtualQuestionsForSpecialty,virtualDoctorsForSpecialty } from '@/lib/catalog';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import { supabase } from '@/lib/supabase';
export default function QuestionsPage(){
 const {path,navigate}=useRouter();const {lang,dir}=useI18n();const q=parseQuery(path);const [selected,setSelected]=useState(q.specialty||'');const [page,setPage]=useState(0);const [dbQuestions,setDbQuestions]=useState<any[]>([]);const specs=specialtyCatalog(lang);
 const c:any={ar:{title:'الأسئلة والأجوبة',sub:'أسئلة وأجوبة تجريبية كاملة لكل تخصص، مع إجابات متعددة من الأخصائيين.',all:'كل التخصصات',choose:'اختار التخصص',ask:'اكتب سؤالك',prev:'السابق',next:'التالي',page:'صفحة',hint:'اضغط على السؤال لقراءة جميع الإجابات.'},en:{title:'Questions & Answers',sub:'Full demo questions and multiple specialist answers for every specialty.',all:'All specialties',choose:'Choose specialty',ask:'Ask a question',prev:'Previous',next:'Next',page:'Page',hint:'Open a question to read all answers.'},ru:{title:'Вопросы и ответы',sub:'Демонстрационные вопросы и несколько ответов специалистов по каждой специальности.',all:'Все специальности',choose:'Выберите специальность',ask:'Задать вопрос',prev:'Назад',next:'Далее',page:'Страница',hint:'Откройте вопрос, чтобы прочитать все ответы.'}}[lang as any]||{title:'Questions & Answers',sub:'Demo questions and specialist answers.',all:'All specialties',choose:'Choose specialty',ask:'Ask a question',prev:'Previous',next:'Next',page:'Page',hint:'Open a question for all answers.'};
 useEffect(()=>{setSelected(q.specialty||'');setPage(0)},[q.specialty]);
 useEffect(()=>{supabase.auth.getUser().then(({data}:any)=>setSpecialistView(data?.user?.user_metadata?.role==='specialist')).catch(()=>setSpecialistView(false))},[]);
 useEffect(()=>{supabase.from('questions').select('*, specialty(*), answers(*,doctor(*))').order('created_at',{ascending:false}).limit(500).then(({data})=>setDbQuestions(data||[])).catch(()=>setDbQuestions([]))},[]);
 const questions=useMemo(()=>{const generated=selected?virtualQuestionsForSpecialty(selected,lang,50):comprehensiveSpecialties.flatMap(s=>virtualQuestionsForSpecialty(s.slug,lang,50));const real=dbQuestions.filter(x=>(!x.language||x.language===lang)&&(!selected||x.specialty?.slug===selected)).map(x=>({...x,title:x.translations?.[lang]?.title||x.title,body:x.translations?.[lang]?.body||x.body}));return [...real,...generated]},[selected,lang,dbQuestions]);
 const priced=questions.map((x:any,i:number)=>{const status=x.status==='closed'||x.status==='cancelled'?'closed':(x.id.includes('catalog-q-')?(Number(x.id.split('-').pop())%5===0?'free':'available'):(x.status==='free'?'free':'available'));const price=status==='free'?0:10+(i%5)*5;return {...x,market_status:status,question_price:price};}); const filteredQuestions=specialistView&&questionFilter!=='all'?priced.filter((x:any)=>x.market_status===questionFilter):priced; const shown=filteredQuestions.slice(page*24,page*24+24); const marketCounts={available:priced.filter((x:any)=>x.market_status==='available').length,free:priced.filter((x:any)=>x.market_status==='free').length,closed:priced.filter((x:any)=>x.market_status==='closed').length};const sideDoctors=virtualDoctorsForSpecialty(selected||specs[0]?.slug||'',lang,8);
 return <div className="min-h-screen pt-24 pb-16 bg-gray-50" dir={dir}><div className="mx-auto max-w-7xl px-4"><div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-7 text-white"><div className="flex items-center gap-3"><MessageCircle className="h-9 w-9"/><div><h1 className="text-3xl font-extrabold">{c.title}</h1><p className="mt-2">{c.sub}</p></div></div></div><div className="mt-5 rounded-2xl bg-white border p-5 flex flex-wrap gap-3"><select value={selected} onChange={e=>{setSelected(e.target.value);setPage(0);navigate('/questions'+(e.target.value?'?specialty='+encodeURIComponent(e.target.value):''))}} className="flex-1 min-w-[280px] rounded-xl border px-4 py-3"><option value="">{c.all}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><button onClick={()=>navigate('/ask'+(selected?'?specialty='+selected:''))} className="rounded-xl bg-teal-600 text-white px-5 py-3 font-bold">{c.ask}</button></div><div className="mt-6 grid lg:grid-cols-[270px_1fr] gap-6"><aside className="rounded-2xl bg-white border p-4 h-fit sticky top-24"><div className="flex items-center gap-2 font-extrabold"><Stethoscope className="h-5 w-5 text-teal-600"/>{lang==='ar'?'أخصائيو التخصص':'Specialists'}</div><div className="mt-4 space-y-3">{sideDoctors.map(d=><button key={d.id} onClick={()=>navigate('/doctors/'+d.id)} className="w-full flex items-center gap-3 rounded-xl p-2 hover:bg-teal-50 text-start"><img src={d.photo_url} className="h-11 w-11 rounded-full object-cover border"/><span className="min-w-0"><b className="block truncate text-sm">{d.name}</b><small className="text-teal-600">{d.specialty?.name}</small></span></button>)}</div></aside><main className="space-y-4">{shown.map(q=><QuestionCard key={q.id} question={q}/>)}<div className="flex items-center justify-center gap-3 py-5"><button disabled={page===0} onClick={()=>setPage(p=>p-1)} className="rounded-xl bg-white border px-4 py-2 disabled:opacity-40">{c.prev}</button><span className="text-sm text-gray-500">{c.page} {page+1}</span><button disabled={(page+1)*24>=filteredQuestions.length} onClick={()=>setPage(p=>p+1)} className="rounded-xl bg-white border px-4 py-2">{c.next}</button></div><div className="rounded-2xl bg-white border p-5 text-sm text-gray-500 flex gap-2"><ChevronLeft className="h-4 w-4 text-teal-600"/>{c.hint}</div></main></div></div></div>;
}