import { useEffect,useMemo,useState } from 'react';
import { MessageCircle,ChevronLeft } from 'lucide-react';
import { useRouter,parseQuery } from '@/lib/router';
import { useI18n } from '@/lib/i18n';
import { comprehensiveSpecialties } from '@/lib/comprehensiveSpecialties';
import QuestionCard from '@/components/QuestionCard';
import { specialtyCatalog,virtualQuestionsForSpecialty } from '@/lib/catalog';
import { supabase } from '@/lib/supabase';
export default function QuestionsPage(){
 const {path,navigate}=useRouter();const {lang,dir}=useI18n();
 const c:any={ar:{title:'الأسئلة والأجوبة',sub:'50 سؤالاً تجريبياً لكل تخصص، مع 5 إلى 20 إجابة افتراضية لكل سؤال.',all:'كل التخصصات',choose:'اختار التخصص',ask:'اكتب سؤالك',prev:'السابق',next:'التالي',page:'صفحة',hint:'اضغط على أي سؤال لقراءة السؤال كاملاً وجميع الإجابات.'},en:{title:'Questions & Answers',sub:'50 demo questions per specialty, with 5–20 virtual answers per question.',all:'All specialties',choose:'Choose specialty',ask:'Ask a question',prev:'Previous',next:'Next',page:'Page',hint:'Open any question to read the full question and all answers.'},ru:{title:'Вопросы и ответы',sub:'50 демонстрационных вопросов по каждой специальности и 5–20 виртуальных ответов.',all:'Все специальности',choose:'Выберите специальность',ask:'Задать вопрос',prev:'Назад',next:'Далее',page:'Страница',hint:'Откройте вопрос, чтобы прочитать его полностью и все ответы.'},de:{title:'Fragen & Antworten',sub:'50 Demo-Fragen pro Fachgebiet mit 5–20 virtuellen Antworten.',all:'Alle Fachgebiete',choose:'Fachgebiet wählen',ask:'Frage stellen',prev:'Zurück',next:'Weiter',page:'Seite',hint:'Öffnen Sie eine Frage für alle Antworten.'}}[lang]||{title:'Questions & Answers',sub:'50 demo questions per specialty.',all:'All specialties',choose:'Choose specialty',ask:'Ask a question',prev:'Previous',next:'Next',page:'Page',hint:'Open a question for all answers.'};
 const q=parseQuery(path);const [selected,setSelected]=useState(q.specialty||'');const [page,setPage]=useState(0);const [dbQuestions,setDbQuestions]=useState<any[]>([]);const specs=specialtyCatalog(lang);
 useEffect(()=>{setSelected(q.specialty||'');setPage(0)},[q.specialty]);
 useEffect(()=>{supabase.from('questions').select('*, specialty(*), answers(*)').order('created_at',{ascending:false}).limit(500).then(({data})=>setDbQuestions(data||[])).catch(()=>setDbQuestions([]))},[lang]);
 const questions=useMemo(()=>{const generated=selected?virtualQuestionsForSpecialty(selected,lang,50):comprehensiveSpecialties.flatMap(s=>virtualQuestionsForSpecialty(s.slug,lang,50));const local=(JSON.parse(localStorage.getItem('sb1_demo_questions')||'[]') as any[]).filter(q=>(q.language||'ar')===lang&&(!selected||q.specialty?.slug===selected||q.specialty_id===selected));const real=dbQuestions.filter(q=>{const tr=q.translations||{};return !!tr[lang]&&(!selected||q.specialty?.slug===selected||q.specialty_id===selected)}).map(q=>({...q,title:q.translations[lang]?.title||q.title,body:q.translations[lang]?.body||q.body}));return [...real,...local,...generated];},[selected,lang,dbQuestions]);
 const shown=questions.slice(page*30,page*30+30);
 return <div className="min-h-screen pt-24 pb-16 bg-gray-50" dir={dir}><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-7 text-white text-center"><MessageCircle className="mx-auto mb-3 h-9 w-9"/><h1 className="text-3xl font-extrabold">{c.title}</h1><p className="mt-2">{c.sub}</p></div><div className="mt-5 rounded-2xl bg-white border p-5"><div className="flex flex-wrap gap-3 items-center"><select value={selected} onChange={e=>{setSelected(e.target.value);setPage(0)}} className="flex-1 min-w-[260px] rounded-xl border px-4 py-3"><option value="">{c.all}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><button onClick={()=>navigate('/ask'+(selected?'?specialty='+selected:''))} className="rounded-xl bg-teal-600 text-white px-5 py-3 font-bold">{c.ask}</button></div></div><div className="mt-6 mx-auto max-w-4xl space-y-4">{shown.map(q=><QuestionCard key={q.id} question={q}/>)}</div><div className="mt-8 flex items-center justify-center gap-3"><button disabled={page===0} onClick={()=>setPage(p=>p-1)} className="rounded-xl bg-white border px-4 py-2 disabled:opacity-40">{c.prev}</button><span className="text-sm text-gray-500">{c.page} {page+1}</span><button disabled={(page+1)*30>=questions.length} onClick={()=>setPage(p=>p+1)} className="rounded-xl bg-white border px-4 py-2">{c.next}</button></div><div className="mt-8 rounded-2xl bg-white border p-5 text-sm text-gray-500 flex gap-2"><ChevronLeft className="h-4 w-4 text-teal-600"/> {c.hint}</div></div></div>;
}