import { useEffect,useMemo,useState } from 'react';
import { Copy, Users, Wallet, Star, ChevronDown, ChevronUp, Share2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useI18n } from '@/lib/i18n';

type Member={id:string;name:string;email?:string;member_type:string;referral_code:string;parent_id?:string|null;level:number;country_code?:string;language_code:string;points:number;wallet_balance:number;total_sales:number;status:string};

const demo:Member[]=[
{id:'me',name:'حسابي',email:'owner@sb1.demo',member_type:'client',referral_code:'SB1-ME',parent_id:null,level:0,country_code:'SY',language_code:'ar',points:1240,wallet_balance:186.5,total_sales:2450,status:'active'},
{id:'a',name:'محمد أحمد',referral_code:'SB1-A',parent_id:'me',level:1,language_code:'ar',points:410,wallet_balance:54,total_sales:900,status:'active',member_type:'client'},
{id:'b',name:'د. سارة خالد',referral_code:'SB1-B',parent_id:'me',level:1,language_code:'ar',points:720,wallet_balance:93,total_sales:1450,status:'active',member_type:'specialist'},
{id:'c',name:'علي يوسف',referral_code:'SB1-C',parent_id:'a',level:2,language_code:'ar',points:180,wallet_balance:21,total_sales:420,status:'active',member_type:'client'},
{id:'d',name:'أ.مريم حسن',referral_code:'SB1-D',parent_id:'a',level:2,language_code:'ar',points:260,wallet_balance:31,total_sales:620,status:'active',member_type:'specialist'},
{id:'e',name:'جورج ك',referral_code:'SB1-E',parent_id:'b',level:2,language_code:'en',points:330,wallet_balance:42,total_sales:780,status:'active',member_type:'client'},
{id:'f',name:'د. أرمين م',referral_code:'SB1-F',parent_id:'e',level:3,language_code:'hy',points:140,wallet_balance:18,total_sales:300,status:'active',member_type:'specialist'}
];

export default function ReferralTreePage(){
 const {dir}=useI18n(); const [members,setMembers]=useState<Member[]>([]); const [expanded,setExpanded]=useState<Record<string,boolean>>({me:true,a:true,b:true,e:true}); const [copied,setCopied]=useState(false);
 useEffect(()=>{supabase.from('affiliate_members').select('*').order('level').then(r=>setMembers((r.data&&r.data.length?r.data:demo) as Member[])).catch(()=>setMembers(demo))},[]);
 const root=members.find(x=>!x.parent_id)||demo[0]; const byParent=useMemo(()=>members.reduce((m,x)=>{const k=x.parent_id||'root';(m[k] ||= []).push(x);return m},{} as Record<string,Member[]>),[members]);
 const copy=async()=>{await navigator.clipboard?.writeText(window.location.origin+'/register?ref='+(root?.referral_code||'SB1-ME'));setCopied(true);setTimeout(()=>setCopied(false),1800)};
 const descendants=(id:string)=>{const direct=byParent[id]||[];return direct.length+direct.reduce((n,x)=>n+descendants(x.id),0)};
 const renderNode=(m:Member)=>{const kids=byParent[m.id]||[];const open=expanded[m.id];return <div className="ms-5 mt-3 border-s-2 border-teal-100 ps-4"><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-extrabold">{m.name}</div><div className="text-xs text-gray-500">{m.member_type==='specialist'?'أخصائي':'عميل'} · المستوى {m.level}</div></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-700">★ {m.points} نقطة</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">{Number(m.wallet_balance).toFixed(2)} USD</span></div><button onClick={()=>setExpanded(s=>({...s,[m.id]:!open}))} className="rounded-xl bg-gray-50 p-2">{open?<ChevronUp/>:<ChevronDown/>}</button></div>{open&&<><div className="mt-3 grid gap-2 sm:grid-cols-3 text-sm"><div>المبيعات: <b>{m.total_sales} USD</b></div><div>الإحالات تحتك: <b>{descendants(m.id)}</b></div><div>اللغة: <b>{m.language_code}</b></div></div>{kids.map(renderNode)}</>}</div></div>};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-8 text-white"><div className="flex flex-wrap items-center justify-between gap-5"><div><h1 className="text-3xl font-extrabold">شجرة الإحالات والمكافآت</h1><p className="mt-2 text-white/85">الشجرة الحية، المستويات، النقاط والمبيعات والمستحقات.</p></div><button onClick={copy} className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 font-bold text-teal-700"><Copy className="h-4 w-4"/>{copied?'تم النسخ':'نسخ رابط الإحالة'}</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-4"><div className="rounded-2xl bg-white border p-5"><Users/><b className="mt-3 block text-2xl">{Math.max(0,members.length-1)}</b><span className="text-sm text-gray-500">الأعضاء</span></div><div className="rounded-2xl bg-white border p-5"><Star/><b className="mt-3 block text-2xl">{root.points}</b><span className="text-sm text-gray-500">النقاط</span></div><div className="rounded-2xl bg-white border p-5"><Wallet/><b className="mt-3 block text-2xl">{Number(root.wallet_balance).toFixed(2)}</b><span className="text-sm text-gray-500">الرصيد المستحق USD</span></div><div className="rounded-2xl bg-white border p-5"><Share2/><b className="mt-3 block text-2xl">{descendants(root.id)}</b><span className="text-sm text-gray-500">إجمالي الشجرة</span></div></div><div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-extrabold">الشجرة</h2><div className="mt-4">{root&&renderNode(root)}</div><p className="mt-5 text-xs text-gray-500">العمولات المالية تُحتسب من المبيعات/الخدمات المؤهلة فقط؛ التسجيل وحده لا ينشئ عمولة.</p></div></div></div>
}