import {useEffect,useMemo,useState} from 'react';
import {Clock,Users,ShieldCheck,Lock,Globe2,Video,MessageSquare,CalendarDays,Send} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {useApp} from '@/i18n/AppContext';
import {useRouter} from '@/lib/router';
import {specialtyCatalog,virtualDoctorsForSpecialty} from '@/lib/catalog';

const feeBase:any={EGP:20,RUB:100,SAR:5,AED:5,JOD:1,USD:1,EUR:1,GBP:1,TRY:35,UAH:40,UZS:12000,AMD:400,AZN:1.7,GEL:3,TJS:10,ETB:20,CAD:1.4,CHF:1};
const durationFactor:any={3:1,5:1.35,7:1.75};
const targetFactor:any={5:1,10:1.5,15:2,20:2.5};
const feeFor=(c:string,d:number,t:number)=>Math.round((feeBase[c]||1)*durationFactor[d]*targetFactor[t]*100)/100;
const load=()=>{try{return JSON.parse(localStorage.getItem('sb1_open_requests')||'[]')}catch{return []}};
const save=(x:any[])=>localStorage.setItem('sb1_open_requests',JSON.stringify(x));

export default function RequestMarketplacePage(){
 const {lang,dir}=useI18n();const {country}=useApp();const {navigate}=useRouter();
 const specs=useMemo(()=>specialtyCatalog(lang),[lang]);
 const [tab,setTab]=useState<'create'|'open'|'mine'>('create');
 const [specialty,setSpecialty]=useState('');const [problem,setProblem]=useState('');const [requirements,setRequirements]=useState('');
 const [targetPrice,setTargetPrice]=useState('');const [availableTime,setAvailableTime]=useState('');
 const [days,setDays]=useState(3);const [target,setTarget]=useState(5);const [visibility,setVisibility]=useState<'open'|'hidden'>('open');
 const [message,setMessage]=useState('');const [requests,setRequests]=useState<any[]>(load);const [selected,setSelected]=useState<any>(null);
 const currency=country.currency;const fee=feeFor(currency,days,target);
 useEffect(()=>{const now=Date.now();const next=load().map((r:any)=>{if(r.status==='open'&&r.createdAt&&now-new Date(r.createdAt).getTime()>=r.days*86400000&&(r.offers||0)<r.target){const discounts=JSON.parse(localStorage.getItem('sb1_request_discounts')||'[]');if(!discounts.some((d:any)=>d.requestId===r.id)){discounts.push({id:'discount-'+r.id,requestId:r.id,percent:50,reason:(r.offers||0)===0?'no_response':'target_not_reached',status:'available',createdAt:new Date().toISOString()});localStorage.setItem('sb1_request_discounts',JSON.stringify(discounts))}return {...r,status:'expired',guaranteeDiscount:50} }return r});save(next);setRequests(next)},[]);
 const create=()=>{if(!specialty||problem.trim().length<20){setMessage(lang==='ar'?'اختر التخصص واكتب تفاصيل المشكلة بشكل كافٍ.':'Choose a specialty and describe the problem in enough detail.');return}
  const reference='req-'+Date.now();const draft={id:reference,specialty,problem,requirements,targetPrice,availableTime,days,target,visibility,country:country.name,countryCode:country.code,currency,fee,createdAt:new Date().toISOString(),offers:0,status:'pending',offersList:[]};
  localStorage.setItem('sb1_pending_request_'+reference,JSON.stringify(draft));navigate('/payments?type=request&reference='+encodeURIComponent(reference)+'&amount='+fee+'&currency='+encodeURIComponent(currency));
 };
 const addOffer=(r:any)=>{const docs=virtualDoctorsForSpecialty(r.specialty,lang,Math.min(r.target,20));const d=docs[(r.offers||0)%Math.max(1,docs.length)];const offer={id:'offer-'+Date.now(),doctorName:d?.name||'Specialist demo',comment:lang==='ar'?'أستطيع مراجعة التفاصيل في جلسة فيديو ومناقشة الخطوات المناسبة. هذا عرض تجريبي.':'I can review the details in a video session and discuss appropriate next steps. Demo offer.',price:Number(r.targetPrice)||30,durationMinutes:60,createdAt:new Date().toISOString()};const next=load().map((x:any)=>x.id===r.id?{...x,offers:(x.offers||0)+1,offersList:[...(x.offersList||[]),offer]}:x);save(next);setRequests(next);};
 const all=[...requests];const open=all.filter(r=>r.visibility==='open');
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-24"><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-indigo-700 via-teal-700 to-cyan-700 p-7 text-white"><div className="flex flex-wrap justify-between gap-4 items-center"><div><p className="text-sm opacity-80">SB1 · المناقصات والطلبات</p><h1 className="text-3xl font-black">{lang==='ar'?'حجز جلسة فيديو بطريقتين':'Video booking in two ways'}</h1><p className="mt-2 opacity-90">{lang==='ar'?'حجز مباشر من جدول الأخصائي أو طلب عروض من عدة أخصائيين':'Book directly or request offers from multiple specialists'}</p></div><button onClick={()=>navigate('/choose-doctor')} className="rounded-xl bg-white/15 px-4 py-3 font-bold"><Video className="inline h-5 w-5"/> {lang==='ar'?'الحجز المباشر':'Direct booking'}</button></div></div>
  <div className="mt-5 grid grid-cols-3 gap-1 rounded-2xl bg-white p-1 shadow-sm"><button onClick={()=>setTab('create')} className={'rounded-xl p-3 font-bold '+(tab==='create'?'bg-teal-600 text-white':'')}>{lang==='ar'?'إنشاء طلب':'Create request'}</button><button onClick={()=>setTab('open')} className={'rounded-xl p-3 font-bold '+(tab==='open'?'bg-teal-600 text-white':'')}>{lang==='ar'?'الطلبات المفتوحة':'Open requests'}</button><button onClick={()=>setTab('mine')} className={'rounded-xl p-3 font-bold '+(tab==='mine'?'bg-teal-600 text-white':'')}>{lang==='ar'?'طلباتي':'My requests'}</button></div>
  {tab==='create'&&<div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{lang==='ar'?'تفاصيل الطلب':'Request details'}</h2><label className="mt-5 block font-bold">{lang==='ar'?'التخصص':'Specialty'}<select value={specialty} onChange={e=>setSpecialty(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">{lang==='ar'?'اختار التخصص':'Choose specialty'}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label><label className="mt-4 block font-bold">{lang==='ar'?'المشكلة الصحية':'Health problem'}<textarea value={problem} onChange={e=>setProblem(e.target.value)} rows={7} className="mt-2 w-full rounded-xl border p-3" placeholder={lang==='ar'?'اشرح الأعراض والتاريخ والمتطلبات بالتفصيل':'Describe symptoms, history and requirements'}/></label><label className="mt-4 block font-bold">{lang==='ar'?'متطلباتك من الأخصائي':'Requirements'}<textarea value={requirements} onChange={e=>setRequirements(e.target.value)} rows={4} className="mt-2 w-full rounded-xl border p-3"/></label><div className="grid gap-4 md:grid-cols-2 mt-4"><label className="rounded-xl border p-4 font-bold">{lang==='ar'?'السعر المستهدف':'Target price'}<input value={targetPrice} onChange={e=>setTargetPrice(e.target.value)} className="mt-2 w-full rounded-lg border p-2" placeholder={currency}/></label><label className="rounded-xl border p-4 font-bold">{lang==='ar'?'الوقت المتاح':'Available time'}<input value={availableTime} onChange={e=>setAvailableTime(e.target.value)} className="mt-2 w-full rounded-lg border p-2"/></label></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>setVisibility('open')} className={'rounded-xl border p-4 text-start '+(visibility==='open'?'border-teal-500 bg-teal-50':'')}><Globe2 className="inline"/> <b>{lang==='ar'?'مفتوح':'Open'}</b><p className="text-xs text-slate-500">{lang==='ar'?'للأخصائيين المطابقين':'Matching specialists'}</p></button><button onClick={()=>setVisibility('hidden')} className={'rounded-xl border p-4 text-start '+(visibility==='hidden'?'border-indigo-500 bg-indigo-50':'')}><Lock className="inline"/> <b>{lang==='ar'?'مخفي':'Hidden'}</b><p className="text-xs text-slate-500">{lang==='ar'?'للمستهدفين فقط':'Targeted specialists only'}</p></button></div><button onClick={create} className="mt-5 rounded-xl bg-teal-600 px-6 py-3 font-bold text-white"><Send className="inline h-4 w-4"/> {lang==='ar'?'دفع وإنشاء الطلب':'Pay & create request'}</button>{message&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}</div>
   <aside className="rounded-2xl border bg-white p-6 h-fit"><h3 className="font-black">{lang==='ar'?'قيمة الطلب':'Request fee'}</h3><label className="mt-4 block">{lang==='ar'?'مدة العرض':'Listing duration'}<select value={days} onChange={e=>setDays(+e.target.value)} className="mt-2 w-full rounded-lg border p-2">{[3,5,7].map(x=><option key={x} value={x}>{x} {lang==='ar'?'أيام':'days'}</option>)}</select></label><label className="mt-4 block">{lang==='ar'?'عدد الأخصائيين':'Target specialists'}<select value={target} onChange={e=>setTarget(+e.target.value)} className="mt-2 w-full rounded-lg border p-2">{[5,10,15,20].map(x=><option key={x} value={x}>{x}</option>)}</select></label><div className="mt-5 rounded-2xl bg-teal-50 p-5 text-center"><p className="text-sm">{country.name} · {currency}</p><p className="text-4xl font-black text-teal-800">{fee} {country.currencySymbol}</p></div><div className="mt-4 rounded-xl bg-amber-50 p-4 text-xs leading-6 text-amber-900"><ShieldCheck className="inline h-4 w-4"/> {lang==='ar'?'تنبيه الضمان: دفع قيمة الطلب يحجز مساحة عرض ومجهوداً للأطباء. إذا لم يستجب أي طبيب أو لم يصل الطلب للعدد المطلوب، تحصل تلقائياً على خصم 50% على طلبك القادم. وإذا وصلت عروض ولم يناسبك أي منها وقدمت شكوى مبررة، تحصل على خصم 50% بعد مراجعة الإدارة.':'Guarantee: the fee reserves listing space and specialist effort. If no specialist responds or the target count is not reached, you automatically receive 50% off the next request. If offers arrive but none is suitable and your justified complaint is approved, you receive 50% off after admin review.'}</div></aside></div>}
  {tab!=='create'&&<div className="mt-5 space-y-4">{(tab==='open'?open:all).map(r=><div key={r.id} className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{r.visibility==='hidden'?'مخفي':'مفتوح'}</span><h3 className="mt-3 text-xl font-black">{specs.find(s=>s.slug===r.specialty)?.name||r.specialty}</h3><p className="mt-2 text-slate-600">{r.problem}</p></div><div className="text-end"><b>{r.fee} {r.currency}</b><p className="text-xs text-slate-500">{r.days} أيام · {r.offers||0}/{r.target}</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-4 text-sm"><span><Clock className="inline h-4 w-4"/> {r.days} {lang==='ar'?'أيام':'days'}</span><span><Users className="inline h-4 w-4"/> {r.offers||0}/{r.target}</span><span><CalendarDays className="inline h-4 w-4"/> {new Date(r.createdAt).toLocaleDateString()}</span><span>{r.country}</span></div>{tab==='open'&&<button onClick={()=>addOffer(r)} disabled={(r.offers||0)>=r.target} className="mt-4 rounded-xl bg-indigo-600 px-5 py-2 font-bold text-white disabled:opacity-40"><MessageSquare className="inline h-4 w-4"/> {lang==='ar'?'إرسال عرض تجريبي':'Submit demo offer'}</button>}{tab==='mine'&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>{lang==='ar'?'العروض':'Offers'}:</b> {(r.offersList||[]).length||r.offers||0} · <button onClick={()=>setSelected(r)} className="rounded-lg bg-white px-3 py-1 border">{lang==='ar'?'عرض واختيار عرض':'View offers'}</button></div>}</div>)}</div>}
  {selected&&<div className="fixed inset-0 z-50 overflow-auto bg-black/40 p-4" onClick={()=>setSelected(null)}><div className="mx-auto mt-16 max-w-3xl rounded-3xl bg-white p-7" onClick={e=>e.stopPropagation()}><h2 className="text-2xl font-black">{lang==='ar'?'عروض الأخصائيين':'Specialist offers'}</h2><div className="mt-5 space-y-3">{(selected.offersList||[]).map((o:any)=><div key={o.id} className="rounded-2xl border p-4"><b>{o.doctorName}</b><p className="mt-2 text-sm text-slate-600">{o.comment}</p><div className="mt-3 flex justify-between"><span>{o.price} {selected.currency} · {o.durationMinutes} min</span><button onClick={()=>{setMessage(lang==='ar'?'تم اختيار العرض.':'Offer selected.');setSelected(null)}} className="rounded-xl bg-teal-600 px-4 py-2 text-white font-bold">{lang==='ar'?'اختيار':'Choose'}</button></div></div>)}{!(selected.offersList||[]).length&&<p className="text-slate-500">{lang==='ar'?'لا توجد عروض بعد.':'No offers yet.'}</p>}</div><div className="mt-5 rounded-xl bg-blue-50 p-4 text-sm"><ShieldCheck className="inline h-4 w-4"/> {lang==='ar'?'إذا انتهت مدة الطلب ولم يتحقق الحد المطلوب، يتم تجهيز خصم 50% للطلب التالي.':'If the target is not reached before expiry, a 50% next-request discount is prepared.'}</div></div></div>}
 </div></div>
}