import {CreditCard,ShieldCheck,CheckCircle2} from 'lucide-react';
import {useRouter,parseQuery} from '@/lib/router';
import {useI18n} from '@/lib/i18n';

export default function RequestPaymentPage(){
 const {path,navigate}=useRouter();const q=parseQuery(path);const {lang,dir}=useI18n();const amount=Number(q.amount||0);const currency=q.currency||'USD';
 const complete=()=>{const raw=q.reference?localStorage.getItem('sb1_pending_request_'+q.reference):null;if(!raw)return;const row=JSON.parse(raw);row.status='open';localStorage.setItem('sb1_open_requests',JSON.stringify([row,...JSON.parse(localStorage.getItem('sb1_open_requests')||'[]')]));localStorage.removeItem('sb1_pending_request_'+q.reference);navigate('/requests?paid=1');};
 const live=async()=>{try{const r=await fetch('/api/create-checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,currency:currency.toLowerCase(),description:'SB1 video request listing',reference_id:q.reference})});const d=await r.json();if(!r.ok||!d.url)throw new Error('checkout');window.location.href=d.url}catch{alert(lang==='ar'?'بوابة الدفع الحية غير مفعلة على هذا النشر. استخدم زر الدفع التجريبي الآن.':'Live checkout is not configured on this deployment. Use sandbox checkout.')}};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-20"><div className="mx-auto max-w-2xl px-4"><div className="rounded-3xl border bg-white p-8 shadow-sm text-center"><CreditCard className="mx-auto h-14 w-14 text-teal-600"/><h1 className="mt-4 text-3xl font-black">{lang==='ar'?'دفع نشر الطلب':'Request listing checkout'}</h1><p className="mt-2 text-slate-500">{lang==='ar'?'لا يتم نشر الطلب حتى يتم تأكيد الدفع.':'The request is published only after payment confirmation.'}</p><div className="my-7 rounded-2xl bg-teal-50 p-6"><p className="text-sm text-teal-700">{lang==='ar'?'قيمة الطلب':'Request fee'}</p><p className="text-4xl font-black text-teal-800">{amount} {currency}</p></div><button onClick={live} className="w-full rounded-xl bg-teal-600 py-3 font-bold text-white">{lang==='ar'?'فتح بوابة الدفع الآمن':'Open secure checkout'}</button><button onClick={complete} className="mt-3 w-full rounded-xl border py-3 font-bold text-slate-700">{lang==='ar'?'تأكيد الدفع التجريبي':'Confirm sandbox payment'}</button><div className="mt-5 rounded-xl bg-amber-50 p-4 text-start text-sm text-amber-900"><ShieldCheck className="inline h-4 w-4"/> {lang==='ar'?'الضمان المالي: إذا لم يستجب أي أخصائي أو لم يتحقق العدد المطلوب، يضاف خصم 50% للطلب القادم وفق سياسة SB1. وإذا كانت هناك عروض غير مناسبة، يمكن تقديم شكوى مبررة للمراجعة الإدارية.':'Guarantee: if no specialist responds or the target is not reached, a 50% discount is added to the next request under SB1 policy. If offers are unsuitable, a justified complaint can be submitted for admin review.'}</div><div className="mt-5 text-xs text-slate-400"><CheckCircle2 className="inline h-4 w-4"/> Sandbox does not charge real money.</div></div></div></div>
}