import {useState} from 'react';
import {ShieldAlert,Clock,Upload,Send,Bell,FileWarning,Undo2,PauseCircle,Trash2,CheckCircle} from 'lucide-react';
import {registerViolation,ownerAlerts,markAlertRead,getSanction,submitSafetyAppeal,localAppeals,reviewSafetyAppeal} from '@/lib/safetyModeration';
import {useI18n} from '@/lib/i18n';

export default function SafetyCenterPage(){
 const {lang,dir}=useI18n();
 const user=localStorage.getItem('sb1_account_user_id')||localStorage.getItem('chat_email')||'demo-user';
 const [reason,setReason]=useState(''); const [appeal,setAppeal]=useState(''); const [image,setImage]=useState(''); const [notice,setNotice]=useState('');
 const [alerts,setAlerts]=useState(ownerAlerts()); const [appeals,setAppeals]=useState(localAppeals()); const [refresh,setRefresh]=useState(0);
 const sanction=getSanction(user); const isAdmin=!!localStorage.getItem('admin_auth');
 const readImage=(f:File)=>{const r=new FileReader();r.onload=()=>setImage(String(r.result||''));r.readAsDataURL(f)};
 const report=()=>{if(!reason.trim())return;const s=registerViolation(user,reason,image);setNotice('تم تسجيل المخالفة رقم '+s.strike+'، العقوبة: '+s.level+'، وتم إرسال تنبيه للمالك والمشرفين.');setAlerts(ownerAlerts());setReason('');setImage('');};
 const sendAppeal=async()=>{if(!appeal.trim())return;await submitSafetyAppeal(user,appeal,image);setNotice('تم إرسال الشكوى للمراجعة من المالك والمشرفين.');setAppeal('');setImage('');setAppeals(localAppeals());};
 const act=async(id:string,d:'restore'|'suspend'|'delete')=>{await reviewSafetyAppeal(id,d,d==='restore'?'إرجاع الحساب بعد المراجعة':d==='suspend'?'إيقاف الحساب بعد المراجعة':'حذف الحساب بعد المراجعة');setAppeals(localAppeals());setRefresh(x=>x+1);};
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-red-700 to-slate-900 p-8 text-white"><ShieldAlert className="h-10 w-10"/><h1 className="mt-3 text-3xl font-extrabold">مركز الأمان والإشراف</h1><p className="mt-2 text-white/80">نظام المخالفات، الإيقاف المتدرج، التنبيهات والشكاوى.</p></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2">
 <section className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">إبلاغ عن مخالفة</h2><textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-4 w-full rounded-2xl border p-4 min-h-28" placeholder="اكتب تفاصيل المخالفة..."/><label className="mt-3 flex items-center gap-3 rounded-2xl border border-dashed p-4 cursor-pointer"><Upload className="h-5 w-5 text-red-600"/><span>إرفاق صورة/دليل</span><input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&readImage(e.target.files[0])}/></label>{image&&<img src={image} className="mt-3 max-h-40 rounded-xl border" alt="evidence"/>}<button onClick={report} className="mt-4 rounded-xl bg-red-700 px-5 py-3 text-white font-bold"><Send className="inline h-4 w-4 me-2"/>تنفيذ المخالفة والتنبيه</button>{notice&&<div className="mt-4 rounded-xl bg-green-50 p-4 text-green-800">{notice}</div>}</section>
 <section className="rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">الإيقاف الآلي</h2>{sanction?<div className="mt-4 rounded-2xl bg-red-50 border border-red-200 p-5"><Clock className="h-6 w-6 text-red-700"/><p className="mt-2 font-bold">المخالفة رقم {sanction.strike}</p><p>العقوبة: <b>{sanction.level}</b></p><p className="text-sm mt-1">السبب: {sanction.reason}</p>{sanction.until&&<p className="text-sm mt-1">تنتهي: {new Date(sanction.until).toLocaleString()}</p>}</div>:<div className="mt-4 rounded-2xl bg-green-50 p-5 text-green-800">لا يوجد إيقاف فعال.</div>}<div className="mt-5 rounded-2xl bg-gray-50 p-5"><ol className="list-decimal ps-5 space-y-1"><li>الأولى: ساعة.</li><li>الثانية: 24 ساعة.</li><li>الثالثة: 7 أيام.</li><li>الرابعة: إيقاف دائم للمراجعة.</li></ol></div></section></div>
 <section className="mt-5 rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">شكوى صاحب الحساب</h2><p className="text-sm text-gray-500 mt-1">يمكن شرح المشكلة وإرفاق دليل، وتصل الشكوى للمالك والمشرفين للمراجعة.</p><textarea value={appeal} onChange={e=>setAppeal(e.target.value)} className="mt-4 w-full rounded-2xl border p-4 min-h-28" placeholder="اشرح لماذا تعتقد أن العقوبة غير صحيحة..."/><button onClick={sendAppeal} className="mt-3 rounded-xl bg-indigo-700 px-5 py-3 text-white font-bold">إرسال الشكوى</button></section>
 <section className="mt-5 rounded-3xl bg-white border p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold"><Bell className="inline h-5 w-5 me-2"/>تنبيهات المالك والمشرفين</h2><span className="text-xs text-gray-400">{alerts.length}</span></div><div className="mt-4 space-y-3">{alerts.slice(0,20).map((a:any)=><div key={a.id} className={'rounded-2xl border p-4 '+(a.read?'bg-gray-50':'bg-red-50')}><div className="flex gap-2 items-center"><FileWarning className="h-4 w-4 text-red-700"/><b>{a.type==='safety_appeal'?'شكوى':'مخالفة رقم '+a.strike}</b></div><p className="text-sm mt-1">{a.reason} · {a.level}</p><button onClick={()=>{markAlertRead(a.id);setAlerts(ownerAlerts())}} className="mt-2 text-xs font-bold text-indigo-700">تمييز كمقروء</button></div>)}</div></section>
 {isAdmin&&<section className="mt-5 rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">مراجعة شكاوى الحسابات</h2><div className="mt-4 space-y-3">{appeals.map((a:any)=><div key={a.id} className="rounded-2xl border p-4"><div className="font-bold">حساب: {a.userKey}</div><p className="mt-2 text-sm">{a.complaint}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>act(a.id,'restore')} className="rounded-xl bg-green-600 text-white px-4 py-2"><CheckCircle className="inline h-4 w-4 me-1"/>إرجاع الحساب</button><button onClick={()=>act(a.id,'suspend')} className="rounded-xl bg-amber-600 text-white px-4 py-2"><PauseCircle className="inline h-4 w-4 me-1"/>إيقاف</button><button onClick={()=>act(a.id,'delete')} className="rounded-xl bg-red-700 text-white px-4 py-2"><Trash2 className="inline h-4 w-4 me-1"/>حذف</button></div></div>)}{!appeals.length&&<p className="text-gray-500">لا توجد شكاوى محلية معلقة.</p>}</div></section>}
 </div></div>
}