import {useMemo,useState} from 'react';
import {Search,MapPin,Star,Clock,CalendarDays,Stethoscope,Building2,Pill,BookOpen,PlayCircle} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {virtualDoctorsForSpecialty,virtualFacilities,virtualArticlesForSpecialty,virtualVideosForSpecialty,specialtyCatalog,countriesForLanguage} from '@/lib/catalog';
import {useRouter} from '@/lib/router';

export default function SearchPage(){
 const {lang,dir}=useI18n(); const {navigate}=useRouter(); const countries=countriesForLanguage(lang);
 const [q,setQ]=useState(''); const [country,setCountry]=useState(countries[0]?.key||''); const [kind,setKind]=useState('all'); const [sort,setSort]=useState('rating');
 const specialties=specialtyCatalog(lang).slice(0,35);
 const results=useMemo(()=>{
  const term=q.trim().toLowerCase(); const out:any[]=[];
  specialties.forEach(s=>virtualDoctorsForSpecialty(s.slug,lang,3,country).forEach((d:any)=>out.push({id:d.id,kind:'doctor',title:d.name,subtitle:d.specialty?.name||s.name,location:d.city||'',rating:d.rating||4.7,fastest:d.experience_years||10,available:true,href:'/doctors/'+d.id})));
  virtualFacilities(lang,country).forEach((f:any)=>out.push({id:f.id,kind:f.facility_type==='pharmacy'?'pharmacy':'facility',title:f.name,subtitle:f.services,location:f.city,rating:f.rating||4.6,fastest:15,available:true,href:'/facilities/'+f.id}));
  specialties.slice(0,12).forEach(s=>virtualArticlesForSpecialty(s.slug,lang,2).forEach((a:any)=>out.push({id:a.id,kind:'article',title:a.title,subtitle:a.description,location:'',rating:4.8,fastest:0,available:true,href:'/articles/'+a.id})));
  specialties.slice(0,8).forEach(s=>virtualVideosForSpecialty(s.slug,lang,1).forEach((v:any)=>out.push({id:v.id,kind:'video',title:v.title,subtitle:v.description,location:'',rating:4.8,fastest:0,available:true,href:'/videos'})));
  let filtered=out.filter(x=>(kind==='all'||x.kind===kind)&&(!term||[x.title,x.subtitle,x.location].join(' ').toLowerCase().includes(term)));
  if(sort==='name')filtered.sort((a,b)=>a.title.localeCompare(b.title)); else if(sort==='nearest')filtered.sort((a,b)=>String(a.location).localeCompare(String(b.location))); else if(sort==='fastest')filtered.sort((a,b)=>a.fastest-b.fastest); else if(sort==='available')filtered.sort((a,b)=>Number(b.available)-Number(a.available)); else filtered.sort((a,b)=>b.rating-a.rating);
  return filtered.slice(0,80);
 },[q,country,kind,sort,lang]);
 const label=lang==='ar'?{title:'البحث المتطور',sub:'ابحث بالاسم أو المكان أو الخدمة أو الدواء أو التخصص، ثم فرز حسب التقييم أو الأقرب أو الأسرع أو المواعيد.',search:'اكتب اسم الطبيب أو المؤسسة أو الخدمة أو الدواء...',country:'البلد',all:'الكل',doctor:'الأخصائيون والأطباء',facility:'المرافق',pharmacy:'الصيدليات',article:'المقالات',video:'الفيديو',rating:'الأعلى تقييماً',name:'الاسم',nearest:'الأقرب',fastest:'الأسرع',available:'المواعيد المتاحة'}:{title:'Advanced Search',sub:'Search by name, place, service, medicine or specialty and sort by rating, distance, speed or availability.',search:'Doctor, facility, service or medicine...',country:'Country',all:'All',doctor:'Specialists & Doctors',facility:'Facilities',pharmacy:'Pharmacies',article:'Articles',video:'Videos',rating:'Highest rated',name:'Name',nearest:'Nearest',fastest:'Fastest',available:'Available appointments'};
 const icon=(k:string)=>k==='doctor'?Stethoscope:k==='pharmacy'?Pill:k==='article'?BookOpen:k==='video'?PlayCircle:Building2;
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-slate-900 to-teal-700 p-8 text-white"><h1 className="text-3xl font-extrabold">{label.title}</h1><p className="mt-2 max-w-3xl text-white/80">{label.sub}</p><div className="mt-6 relative"><Search className="absolute start-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={label.search} className="w-full rounded-2xl bg-white text-gray-900 py-4 ps-12 pe-4 outline-none"/></div></div>
  <div className="mt-5 flex flex-wrap gap-2"><select value={country} onChange={e=>setCountry(e.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="">{label.country}</option>{countries.map(c=><option key={c.key} value={c.key}>{c.name} · {c.city}</option>)}</select>{[['all',label.all],['doctor',label.doctor],['facility',label.facility],['pharmacy',label.pharmacy],['article',label.article],['video',label.video]].map(([v,l])=><button key={v} onClick={()=>setKind(v)} className={'rounded-xl px-4 py-3 font-bold '+(kind===v?'bg-teal-600 text-white':'bg-white border text-gray-700')}>{l}</button>)}<select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border bg-white px-4 py-3 ms-auto"><option value="rating">{label.rating}</option><option value="name">{label.name}</option><option value="nearest">{label.nearest}</option><option value="fastest">{label.fastest}</option><option value="available">{label.available}</option></select></div>
  <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.map(x=>{const I=icon(x.kind);return <button key={x.id} onClick={()=>navigate(x.href)} className="text-start rounded-2xl bg-white border p-5 hover:shadow-md"><div className="flex items-start gap-3"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><I className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h3 className="font-extrabold truncate">{x.title}</h3><p className="mt-1 text-sm text-gray-500 line-clamp-2">{x.subtitle}</p>{x.location&&<p className="mt-2 text-xs text-gray-500"><MapPin className="inline h-3 w-3"/> {x.location}</p>}<div className="mt-3 flex gap-3 text-xs"><span className="text-amber-600"><Star className="inline h-3 w-3 fill-current"/> {Number(x.rating).toFixed(1)}</span>{x.kind==='doctor'&&<span className="text-teal-700"><CalendarDays className="inline h-3 w-3"/> {x.available?'مواعيد متاحة':'لا توجد مواعيد'}</span>}{x.fastest>0&&<span><Clock className="inline h-3 w-3"/> {x.fastest} دقيقة</span>}</div></div></div></button>})}</div>
 </div></div>;
}