import { useMemo,useState } from 'react';
import { Search,MessageCircle,Heart,Eye,Send,X } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { specialtyCatalog, allFreeSessions, freeSessionsForSpecialty } from '@/lib/catalog';
const tr=(lang:string,ar:string,en:string)=>lang==='ar'?ar:en;
function load(){try{return JSON.parse(localStorage.getItem('sb1_free_sessions_v2')||'{}')}catch{return {}}}
function store(x:any){localStorage.setItem('sb1_free_sessions_v2',JSON.stringify(x))}
export default function SessionsPage(){
 const {lang,dir}=useI18n(); const specs=useMemo(()=>specialtyCatalog(lang),[lang]); const [specialty,setSpecialty]=useState(''); const [query,setQuery]=useState(''); const [tab,setTab]=useState<'all'|'mine'|'create'>('all'); const [open,setOpen]=useState<any>(null); const [title,setTitle]=useState(''); const [problem,setProblem]=useState(''); const [age,setAge]=useState(''); const [accepted,setAccepted]=useState(false);
 const local=load(); const base=specialty?freeSessionsForSpecialty(specialty,lang,50):allFreeSessions(lang); const sessions=[...base,...(local.sessions||[])];
 const filtered=sessions.filter((s:any)=>!query||[s.title,s.problem,s.clientNickname,s.specialist?.name].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));
 const mine=(local.mine||[]).map((id:string)=>sessions.find((s:any)=>s.id===id)).filter(Boolean);
 const create=()=>{if(Number(age)<18||!specialty||!title||!problem||!accepted){alert(tr(lang,'أكمل العمر والتخصص والعنوان والمشكلة والموافقة.','Complete age, specialty, title, problem and acceptance.'));return}const id='free-'+Date.now();const item={id,title,problem,specialtySlug:specialty,clientNickname:'SB1 user',clientAvatar:'https://i.pravatar.cc/100?img=12',status:'open',messages:[],views:0,likes:0,comments:0,createdAt:new Date().toISOString()};const l=load();l.sessions=[...(l.sessions||[]),item];l.mine=[...(l.mine||[]),id];store(l);setTab('mine');setTitle('');setProblem('');setAccepted(false)};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4"><section className="rounded-3xl bg-gradient-to-br from-teal-800 to-cyan-700 p-7 text-white"><h1 className="text-3xl font-extrabold">{tr(lang,'الجلسات المجانية','Free Sessions')}</h1><p className="mt-2 opacity-90">{tr(lang,'جلسات نصية تجريبية مجانية حسب التخصص.','Free demo text sessions by specialty.')}</p></section>
 <div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>setTab('all')} className="rounded-xl bg-white border px-5 py-3">{tr(lang,'كل الجلسات','All sessions')}</button><button onClick={()=>setTab('mine')} className="rounded-xl bg-white border px-5 py-3">{tr(lang,'جلساتي','My sessions')}</button><button onClick={()=>setTab('create')} className="rounded-xl bg-teal-700 text-white px-5 py-3">{tr(lang,'ابدأ جلسة','Start session')}</button></div>
 {tab==='create'?<div className="mt-5 max-w-3xl rounded-3xl bg-white border p-6"><h2 className="text-xl font-extrabold">{tr(lang,'جلسة مجانية','Free session')}</h2><div className="grid gap-3 mt-4 md:grid-cols-2"><select value={specialty} onChange={e=>setSpecialty(e.target.value)} className="rounded-xl border p-3"><option value="">{tr(lang,'اختر التخصص','Choose specialty')}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><input type="number" min="18" value={age} onChange={e=>setAge(e.target.value)} placeholder="18+" className="rounded-xl border p-3"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={tr(lang,'عنوان السؤال','Question title')} className="rounded-xl border p-3 md:col-span-2"/><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder={tr(lang,'اكتب المشكلة','Describe the problem')} className="rounded-xl border p-3 min-h-32 md:col-span-2"/></div><label className="mt-4 flex gap-2"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{tr(lang,'أوافق على سياسة الجلسة العامة.','I accept the public session policy.')}</label><button onClick={create} className="mt-4 rounded-xl bg-teal-700 text-white px-5 py-3 font-bold">{tr(lang,'نشر الجلسة','Publish')}</button></div>:<><div className="mt-5 grid gap-3 md:grid-cols-[1fr_280px]"><div className="relative"><Search className="absolute start-3 top-3.5 h-5 w-5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr(lang,'ابحث...','Search...')} className="w-full rounded-xl border bg-white p-3 ps-10"/></div><select value={specialty} onChange={e=>setSpecialty(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">{tr(lang,'كل التخصصات','All specialties')}</option>{specs.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></div><div className="mt-5 space-y-4">{(tab==='mine'?mine:filtered).slice(0,60).map((s:any)=><article key={s.id} className="rounded-2xl bg-white border p-5"><div className="flex gap-3"><img src={s.clientAvatar} className="h-12 w-12 rounded-full object-cover"/><div><h3 className="font-extrabold">{s.title}</h3><p className="text-xs text-slate-500">{s.clientNickname}</p></div></div><p className="mt-4 text-sm line-clamp-3">{s.problem}</p><div className="mt-4 flex gap-4 text-xs text-slate-500"><span><Eye className="inline h-4 w-4"/> {s.views||0}</span><span><Heart className="inline h-4 w-4"/> {s.likes||0}</span><span><MessageCircle className="inline h-4 w-4"/> {s.messages?.length||0}</span></div><button onClick={()=>setOpen(s)} className="mt-4 w-full rounded-xl bg-teal-50 text-teal-700 py-2.5 font-bold">{tr(lang,'فتح السؤال والإجابات','Open')}</button></article>)}</div></>}
 {open&&<div className="fixed inset-0 z-50 bg-black/50 p-4 grid place-items-center" onClick={()=>setOpen(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{open.title}</h2><button onClick={()=>setOpen(null)}><X/></button></div><p className="mt-4 whitespace-pre-wrap">{open.problem}</p><div className="mt-5 rounded-2xl border bg-slate-50 p-4 space-y-3">{(open.messages||[]).map((m:any)=><div key={m.id} className={'flex '+(m.sender==='specialist'?'justify-start':'justify-end')}><div className={'max-w-[85%] flex gap-2 '+(m.sender==='specialist'?'flex-row':'flex-row-reverse')}><img src={m.sender==='specialist'?(open.specialist?.photo_url||'/jamal-james.jpg'):open.clientAvatar} className="h-9 w-9 rounded-full object-cover border"/><div><div className="flex items-center gap-2 text-xs text-slate-500 mb-1"><b>{m.senderName}</b><span>{m.createdAt?new Date(m.createdAt).toLocaleString():''}</span></div><div className={'rounded-2xl px-4 py-3 shadow-sm '+(m.sender==='specialist'?'bg-white border':'bg-teal-700 text-white')}>{m.body}</div><div className="mt-1 text-[10px] text-slate-400">{m.sender==='client'?'✓✓ تمت القراءة':'✓✓ تمت القراءة'}</div></div></div></div>)}</div><div className="mt-5 flex gap-2"><input id="session-reply" className="flex-1 rounded-xl border p-3" placeholder={tr(lang,'اكتب إجابة...','Write a reply...')}/><button onClick={()=>{const input=document.getElementById('session-reply') as HTMLInputElement;if(!input.value)return;const l=load();const f=(l.sessions||[]).find((x:any)=>x.id===open.id);if(f){f.messages=[...(f.messages||[]),{id:'m-'+Date.now(),body:input.value}];store(l);setOpen({...f})}}} className="rounded-xl bg-teal-700 text-white px-4"><Send/></button></div></div></div>}
 </div></div>
}