import { useMemo,useState } from 'react';
import { Heart,MessageCircle,Share2,Bookmark,Image as ImageIcon,Video,Mic,FileText,Search,Users,Globe2,Lock,Send,CalendarDays,Paperclip,Plus,Repeat2,EyeOff } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useRouter } from '@/lib/router';

type Post={id:string;author:string;role:string;specialty:string;body:string;kind:'post'|'reel'|'article'|'video'|'audio'|'book';media?:string;likes:number;comments:string[];privacy:'public'|'followers'|'selected';created:number;sharedFrom?:string};

const seed:Post[]=[
{id:'social-1',author:'دكتور جمال نادي',role:'أخصائي نفسي',specialty:'الصحة النفسية',body:'منشور تثقيفي تجريبي في SB1. يمكن للمتابعين التفاعل والتعليق والحفظ وإعادة النشر.',kind:'post',likes:24,comments:['معلومة مفيدة، شكراً.'],privacy:'public',created:Date.now()-3600000},
{id:'social-2',author:'دكتور جمال نادي',role:'أخصائي نفسي',specialty:'الصحة النفسية',body:'ريلز تجريبي — يمكن للأخصائي رفع فيديو قصير ليظهر هنا وفي تبويب الريلز.',kind:'reel',media:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',likes:42,comments:[],privacy:'followers',created:Date.now()-7200000},
{id:'social-3',author:'SB1 Specialist',role:'أخصائي',specialty:'الطب النفسي',body:'مقال تثقيفي تجريبي مع إمكانية مشاركته تلقائياً في قسم المقالات.',kind:'article',likes:11,comments:[],privacy:'public',created:Date.now()-86400000},
];

const tx=(lang:string,a:string,r:string,e:string)=>lang==='ar'?a:lang==='ru'?r:e;

export default function SocialNetworkPage(){
 const {lang,dir}=useI18n(); const {navigate}=useRouter();
 const [tab,setTab]=useState<'feed'|'favorites'|'rooms'>('feed'); const [query,setQuery]=useState('');
 const [composer,setComposer]=useState(''); const [kind,setKind]=useState<Post['kind']>('post'); const [privacy,setPrivacy]=useState<Post['privacy']>('public'); const [autoShare,setAutoShare]=useState(true);
 const [posts,setPosts]=useState<Post[]>(()=>{try{return JSON.parse(localStorage.getItem('sb1_social_posts')||'null')||seed}catch{return seed}});
 const [liked,setLiked]=useState<string[]>(()=>JSON.parse(localStorage.getItem('sb1_social_likes')||'[]')); const [saved,setSaved]=useState<string[]>(()=>JSON.parse(localStorage.getItem('sb1_social_saved')||'[]'));
 const [following,setFollowing]=useState<string[]>(()=>JSON.parse(localStorage.getItem('sb1_social_following')||'[]'));
 const savePosts=(p:Post[])=>{setPosts(p);localStorage.setItem('sb1_social_posts',JSON.stringify(p))};
 const toggle=(arr:string[],set:(v:string[])=>void,key:string,store:string)=>{const n=arr.includes(key)?arr.filter(x=>x!==key):[...arr,key];set(n);localStorage.setItem(store,JSON.stringify(n))};
 const publish=()=>{if(!composer.trim())return;const p:Post={id:'local-'+Date.now(),author:lang==='ar'?'أنت':'You',role:tx(lang,'مستخدم','Пользователь','User'),specialty:tx(lang,'عام','Общее','General'),body:composer.trim(),kind,likes:0,comments:[],privacy,created:Date.now()};savePosts([p,...posts]);setComposer('')};
 const filtered=useMemo(()=>posts.filter(p=>!query||[p.author,p.body,p.specialty].join(' ').toLowerCase().includes(query.toLowerCase())),[posts,query]);
 const tabs=[['feed',tx(lang,'الصفحة الرئيسية','Лента','Feed')],['favorites',tx(lang,'مكتبتي المفضلة','Избранное','Favorites')],['rooms',tx(lang,'الدردشات والغرف','Чаты и комнаты','Chats & Rooms')]] as const;
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4">
  <div className="rounded-3xl bg-gradient-to-br from-teal-700 to-cyan-600 p-7 text-white mb-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-3xl font-extrabold">{tx(lang,'SB1 الاجتماعي','Социальная сеть SB1','SB1 Social')}</h1><p className="mt-2 text-white/85">{tx(lang,'مزيج من فيسبوك وإنستجرام للمحتوى الطبي','Социальная лента для медицинского контента','A medical Facebook/Instagram-style feed')}</p></div><button onClick={()=>navigate('/doctors')} className="rounded-xl bg-white text-teal-700 px-5 py-3 font-bold">{tx(lang,'اكتشف الأخصائيين','Найти специалистов','Discover specialists')}</button></div></div>
  <div className="flex gap-2 overflow-x-auto mb-5">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={'rounded-xl px-5 py-3 font-semibold whitespace-nowrap '+(tab===k?'bg-teal-600 text-white':'bg-white border text-gray-600')}>{l}</button>)}</div>
  {tab==='feed'&&<><div className="bg-white border rounded-2xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><div className="h-11 w-11 rounded-full bg-teal-100 grid place-items-center font-bold text-teal-700">SB</div><textarea value={composer} onChange={e=>setComposer(e.target.value)} rows={3} className="flex-1 rounded-xl border p-3 outline-none focus:border-teal-500" placeholder={tx(lang,'اكتب منشوراً، مقالاً، فكرة أو سؤالاً...','Напишите публикацию, статью, идею или вопрос...','Write a post, article, idea or question...')}/></div>
   <div className="flex flex-wrap gap-2 items-center"><select value={kind} onChange={e=>setKind(e.target.value as Post['kind'])} className="rounded-xl border px-3 py-2 text-sm"><option value="post">Post</option><option value="article">Article</option><option value="reel">Reel</option><option value="video">Video</option><option value="audio">Audio</option><option value="book">Book</option></select><select value={privacy} onChange={e=>setPrivacy(e.target.value as Post['privacy'])} className="rounded-xl border px-3 py-2 text-sm"><option value="public">{tx(lang,'عام','Публично','Public')}</option><option value="followers">{tx(lang,'المتابعون فقط','Только подписчики','Followers only')}</option><option value="selected">{tx(lang,'أشخاص محددون','Выбранные люди','Selected people')}</option></select><label className="flex items-center gap-2 text-sm text-gray-600"><input type="checkbox" checked={autoShare} onChange={e=>setAutoShare(e.target.checked)}/>{tx(lang,'مشاركة تلقائية في قسم المحتوى','Автопубликация в разделе контента','Auto-share to content section')}</label><button onClick={publish} disabled={!composer.trim()} className="ms-auto rounded-xl bg-teal-600 text-white px-5 py-2.5 disabled:opacity-40">{tx(lang,'نشر','Опубликовать','Publish')}</button></div>
   <div className="mt-3 flex flex-wrap gap-2 text-xs text-gray-500"><button className="rounded-lg bg-gray-50 px-3 py-2"><ImageIcon className="inline h-4 w-4"/> {tx(lang,'صورة','Фото','Photo')}</button><button className="rounded-lg bg-gray-50 px-3 py-2"><Video className="inline h-4 w-4"/> Reel/Video</button><button className="rounded-lg bg-gray-50 px-3 py-2"><Mic className="inline h-4 w-4"/> Audio</button><button className="rounded-lg bg-gray-50 px-3 py-2"><FileText className="inline h-4 w-4"/> Article/Book</button><span className="flex items-center gap-1 ms-auto"><EyeOff className="h-4 w-4"/> {tx(lang,'يمكن تقييد الجمهور','Можно ограничить аудиторию','Audience can be restricted')}</span></div>
  </div>
  <div className="bg-white border rounded-2xl p-3 mb-5 flex gap-2"><Search className="h-5 w-5 text-gray-400 mt-2"/><input value={query} onChange={e=>setQuery(e.target.value)} className="flex-1 outline-none p-2" placeholder={tx(lang,'ابحث في المنشورات...','Поиск по публикациям...','Search posts...')}/></div>
  <div className="space-y-5">{filtered.map(p=><article key={p.id} className="bg-white border rounded-2xl p-5"><div className="flex items-start gap-3"><div className="h-11 w-11 rounded-full bg-cyan-50 grid place-items-center font-bold text-cyan-700">{p.author.slice(0,1)}</div><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><b>{p.author}</b><span className="text-xs text-teal-600">{p.specialty}</span><span className="text-xs text-gray-400">{new Date(p.created).toLocaleString()}</span></div><p className="mt-3 leading-7 text-gray-700">{p.body}</p>{p.media&&<video src={p.media} controls className="mt-3 w-full max-h-[520px] rounded-xl object-cover"/>}<div className="mt-4 flex flex-wrap gap-2 border-t pt-3"><button onClick={()=>toggle(liked,setLiked,p.id,'sb1_social_likes')} className="rounded-xl px-3 py-2 hover:bg-rose-50"><Heart className={'inline h-4 w-4 '+(liked.includes(p.id)?'fill-rose-500 text-rose-500':'')}/> {p.likes+(liked.includes(p.id)?1:0)}</button><button className="rounded-xl px-3 py-2 hover:bg-gray-50"><MessageCircle className="inline h-4 w-4"/> {p.comments.length}</button><button onClick={()=>toggle(saved,setSaved,p.id,'sb1_social_saved')} className="rounded-xl px-3 py-2 hover:bg-amber-50"><Bookmark className={'inline h-4 w-4 '+(saved.includes(p.id)?'fill-amber-400':'')}/></button><button onClick={()=>navigator.clipboard?.writeText(location.origin+'/social?post='+p.id)} className="rounded-xl px-3 py-2 hover:bg-gray-50"><Share2 className="inline h-4 w-4"/> {tx(lang,'رابط SB1','Ссылка SB1','SB1 link')}</button><button onClick={()=>savePosts([{...p,id:'repost-'+Date.now(),sharedFrom:p.author,body:tx(lang,'إعادة نشر: ','Репост: ','Repost: ')+p.body},...posts])} className="rounded-xl px-3 py-2 hover:bg-gray-50"><Repeat2 className="inline h-4 w-4"/> {tx(lang,'إعادة نشر','Репост','Repost')}</button></div></div></div></article>)}</div></>}
  {tab==='favorites'&&<Favorites saved={saved} posts={posts} lang={lang}/>}
  {tab==='rooms'&&<Rooms lang={lang} navigate={navigate}/>}
  <div className="mt-8 rounded-2xl bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900">{tx(lang,'تنبيه: يمنع تحميل أو نسخ محتوى الغير ونشره باسمك، كما يمنع نسخ إجابة طبيب آخر ولصقها باعتبارها إجابتك. استخدم إعادة النشر مع إظهار صاحب المحتوى.','Запрещено скачивать или копировать чужой контент и публиковать его от своего имени. Ответы других врачей нельзя выдавать за свои.','Do not download or copy others’ content and publish it as your own. Do not copy another doctor’s answer and present it as yours. Use repost with attribution.')}</div>
 </div></div>
}

function Favorites({saved,posts,lang}:{saved:string[];posts:Post[];lang:string}){const cats=[['all','الكل'],['reel','ريلز'],['video','فيديو'],['article','مقال'],['audio','صوت'],['book','كتاب'],['post','منشور']];const [cat,setCat]=useState('all');const list=posts.filter(p=>saved.includes(p.id)&&(cat==='all'||p.kind===cat));return <div><div className="flex flex-wrap gap-2 mb-5">{cats.map(([k,l])=><button key={k} onClick={()=>setCat(k)} className={'rounded-full px-4 py-2 text-sm '+(cat===k?'bg-amber-500 text-white':'bg-white border')}>{lang==='ar'?l:k}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{list.map(p=><div key={p.id} className="bg-white border rounded-2xl p-5"><b>{p.author}</b><p className="mt-2 text-gray-600">{p.body}</p></div>)}{!list.length&&<div className="bg-white border rounded-2xl p-10 text-center text-gray-400">لا يوجد محتوى محفوظ بعد</div>}</div></div>}

function Rooms({lang,navigate}:{lang:string;navigate:(p:string)=>void}){const rooms=[['عام','General'],['الصحة النفسية','Mental Health'],['الأطفال','Pediatrics'],['القلب','Cardiology'],['جلسة اليوم','Today’s scheduled room']];return <div className="grid gap-4 md:grid-cols-2">{rooms.map(([a,e],i)=><div key={a} className="bg-white border rounded-2xl p-5"><div className="flex items-center justify-between"><h3 className="font-bold">{lang==='ar'?a:e}</h3><Users className="h-5 w-5 text-teal-600"/></div><p className="text-sm text-gray-500 mt-2">موضوع دردشة يمكن تحديد موعده ويظهر كمنشور عام قبل بدايته.</p><div className="flex gap-2 mt-4"><button onClick={()=>navigate('/chat')} className="rounded-xl bg-teal-600 text-white px-4 py-2">دخول الغرفة</button><button className="rounded-xl border px-4 py-2"><CalendarDays className="inline h-4 w-4"/> موعد</button></div></div>)}</div>}
