import { useEffect,useMemo,useState } from 'react';
import { ShoppingCart,Plus,Minus,Trash2,CreditCard,ShieldCheck,Package,BookOpen,Stethoscope,TestTube2,GraduationCap,X } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useApp } from '@/i18n/AppContext';
import { useRouter,parseQuery } from '@/lib/router';
import { supabase } from '@/lib/supabase';
import { defaultStoreProducts,getStoredRole,getCart,saveCart,type StoreProduct } from '@/lib/storeCatalog';

const iconFor=(type:string)=>type==='course'?GraduationCap:type==='book'?BookOpen:type==='consultation'?Stethoscope:type==='test'?TestTube2:Package;
export default function StorePage(){
 const {lang,dir}=useI18n(); const {formatPrice}=useApp(); const {path,navigate}=useRouter(); const q=parseQuery(path);
 const [products,setProducts]=useState<StoreProduct[]>([]); const [cart,setCart]=useState(getCart()); const [role]=useState(getStoredRole()); const [category,setCategory]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [checkout,setCheckout]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{try{const {data,error}=await supabase.from('store_products').select('*').eq('active',true).order('sort_order',{ascending:true});const rows=(data&&data.length?data:defaultStoreProducts).filter((p:any)=>p.active!==false&&(p.language==='all'||p.language===lang)&&(p.audience==='all'||(p.audience==='specialist'&&role==='specialist')));setProducts(rows)}catch{setProducts(defaultStoreProducts.filter(p=>p.audience==='all'||role==='specialist'))}finally{setLoading(false)}})()},[lang,role]);
 useEffect(()=>{saveCart(cart)},[cart]);
 useEffect(()=>{if(q.paid==='1'&&q.reference){setCart([]);setMessage(lang==='ar'?'تم تأكيد الدفع وتفريغ السلة بنجاح.':'Payment confirmed and cart cleared.')}},[q.paid,q.reference,lang]);
 const categories=[['all','الكل'],['question_package','باقات الأسئلة'],['course','الدورات'],['book','الكتب'],['consultation','الخدمات والاستشارات'],['test','الاختبارات'],['specialist_service','خدمات الأخصائيين']];
 const visible=useMemo(()=>products.filter(p=>category==='all'||p.product_type===category),[products,category]);
 const total=cart.reduce((s,x)=>s+x.product.price*x.quantity,0);
 const add=(p:StoreProduct)=>setCart(c=>{const f=c.find(x=>x.product.id===p.id);return f?c.map(x=>x.product.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{product:p,quantity:1}]});
 const change=(id:string,d:number)=>setCart(c=>c.map(x=>x.product.id===id?{...x,quantity:Math.max(0,x.quantity+d)}:x).filter(x=>x.quantity>0));
 const placeOrder=async(sandbox=false)=>{if(!cart.length)return;setCheckout(true);setError('');const reference='store-'+Date.now();const order={id:reference,reference_id:reference,items:cart.map(x=>({product_id:x.product.id,name:x.product.name,quantity:x.quantity,price:x.product.price})),amount:total,currency:'USD',status:'pending',created_at:new Date().toISOString(),role};localStorage.setItem('sb1_store_order_'+reference,JSON.stringify(order));await supabase.from('store_orders').insert(order);if(sandbox){await supabase.from('store_orders').update({status:'paid',paid_at:new Date().toISOString()}).eq('id',reference);setCart([]);setMessage(lang==='ar'?'تم تنفيذ شراء تجريبي بنجاح.':'Demo purchase completed.');setCheckout(false);return;}try{const res=await fetch('/api/create-checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:total,currency:'usd',description:'SB1 Store Order',reference_id:reference,success_url:location.origin+'/store?paid=1&reference='+encodeURIComponent(reference),cancel_url:location.origin+'/store?cancelled=1&reference='+encodeURIComponent(reference)})});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'checkout unavailable');location.href=data.url}catch(e){setError(lang==='ar'?'الدفع الإلكتروني غير مفعّل على النشر الحالي. يمكنك تنفيذ عملية اختبار الآن.':'Live payment is not configured on this deployment. You can use sandbox checkout.');}finally{setCheckout(false)}};
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-20"><div className="mx-auto max-w-7xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-indigo-700 via-teal-700 to-cyan-600 p-7 md:p-10 text-white"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-sm font-bold opacity-80">SB1</p><h1 className="text-3xl md:text-4xl font-extrabold mt-1">{lang==='ar'?'المتجر':lang==='ru'?'Магазин':lang==='de'?'Shop':'Store'}</h1><p className="mt-2 text-white/85">{lang==='ar'?'منتجات وخدمات رقمية للعميل والأخصائي، مع خدمات خاصة بالأخصائيين فقط.':'Digital products and services for clients and specialists, plus specialist-only services.'}</p></div><button onClick={()=>document.getElementById('cart')?.scrollIntoView({behavior:'smooth'})} className="rounded-2xl bg-white/15 px-5 py-3 font-bold backdrop-blur"><ShoppingCart className="inline h-5 w-5 me-2"/>{cart.reduce((s,x)=>s+x.quantity,0)} · {formatPrice(total)}</button></div></div>
 <div className="mt-5 grid gap-4 md:grid-cols-3">
  <div className="rounded-2xl bg-white border p-5"><b>حساب المتجر</b><p className="mt-2 text-sm text-gray-500">الدور الحالي: {role==='specialist'?'أخصائي':'عميل'} · تسجيل الدخول والحساب مرتبطان بالمنصة.</p><a href="/profile" className="mt-3 inline-block text-teal-700 font-bold">إدارة الحساب</a></div>
  <div className="rounded-2xl bg-white border p-5"><b>الإشعارات</b><p className="mt-2 text-sm text-gray-500">إشعارات الطلب والدفع والتنفيذ والاسترداد تظهر في مركز الإشعارات.</p><a href="/notifications" className="mt-3 inline-block text-teal-700 font-bold">فتح الإشعارات</a></div>
  <div className="rounded-2xl bg-white border p-5"><b>الشكاوى والمراجعات</b><p className="mt-2 text-sm text-gray-500">يمكن إرسال شكوى أو بلاغ أو مراجعة أو إعجاب من مركز الخدمة.</p><a href="/support" className="mt-3 inline-block text-teal-700 font-bold">مركز الخدمة</a></div>
 </div>
 <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{categories.map(([id,label])=><button key={id} onClick={()=>setCategory(id)} className={'whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold '+(category===id?'bg-teal-600 text-white':'bg-white text-gray-600 border')}>{label}</button>)}</div>
 {message&&<div className="mt-4 rounded-2xl bg-green-50 border border-green-200 p-4 text-green-800">{message}</div>}{error&&<div className="mt-4 rounded-2xl bg-amber-50 border border-amber-200 p-4 text-amber-900">{error}</div>}
 {loading?<div className="py-16 text-center text-gray-500">جاري تحميل المتجر...</div>:<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(p=>{const Icon=iconFor(p.product_type);return <div key={p.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><img src={p.image_url} alt="" className="h-44 w-full object-cover"/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold text-gray-900">{p.name}</h3><p className="mt-2 text-sm text-gray-500">{p.description}</p></div><Icon className="h-6 w-6 shrink-0 text-teal-600"/></div>{p.audience==='specialist'&&<span className="mt-3 inline-block rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">للأخصائيين فقط</span>}<div className="mt-5 flex items-center justify-between"><b className="text-lg">{formatPrice(p.price)}</b><button onClick={()=>add(p)} className="rounded-xl bg-teal-600 px-4 py-2 font-bold text-white"><Plus className="inline h-4 w-4 me-1"/>إضافة للسلة</button></div></div></div>})}</div>}
 <section id="cart" className="mt-10 rounded-3xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-extrabold"><ShoppingCart className="inline h-6 w-6 me-2 text-teal-600"/>سلة المشتريات</h2><b>{formatPrice(total)}</b></div>{!cart.length?<p className="py-8 text-center text-gray-500">السلة فارغة</p>:<><div className="mt-5 space-y-3">{cart.map(x=><div key={x.product.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-gray-50 p-4"><div><b>{x.product.name}</b><p className="text-sm text-gray-500">{formatPrice(x.product.price)} × {x.quantity}</p></div><div className="flex items-center gap-2"><button onClick={()=>change(x.product.id,-1)} className="rounded-lg bg-white border p-2"><Minus className="h-4 w-4"/></button><span className="w-6 text-center font-bold">{x.quantity}</span><button onClick={()=>change(x.product.id,1)} className="rounded-lg bg-white border p-2"><Plus className="h-4 w-4"/></button><button onClick={()=>setCart(c=>c.filter(y=>y.product.id!==x.product.id))} className="rounded-lg bg-red-50 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div></div>)}</div><div className="mt-6 flex flex-wrap gap-3"><button disabled={checkout} onClick={()=>placeOrder(false)} className="rounded-xl bg-indigo-700 px-6 py-3 font-bold text-white disabled:opacity-50"><CreditCard className="inline h-5 w-5 me-2"/>الدفع الإلكتروني</button><button disabled={checkout} onClick={()=>placeOrder(true)} className="rounded-xl bg-gray-100 px-6 py-3 font-bold text-gray-700 disabled:opacity-50">شراء تجريبي</button></div><p className="mt-3 text-xs text-gray-500"><ShieldCheck className="inline h-4 w-4 me-1"/>الدفع الحقيقي يستخدم بوابة الدفع المربوطة بالموقع عند توفر مفاتيحها.</p></>}
 </section></div></div>
}