import {useEffect,useMemo,useState} from 'react';
import {BadgeDollarSign,Plus,Trash2,Percent,Clock,Users,CheckCircle2} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
type Package={id:string;title:string;sessions:number;regular:number;price:number;discount:number;duration:number;description:string};
type Quote={id:string;client:string;packageId:string;price:number;note:string;status:string};
const pkey='sb1_long_session_packages',qkey='sb1_custom_package_quotes';
const read=(k:string,f:any)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
export default function SpecialistPackagesPage(){
 const {lang,dir}=useI18n();const [packages,setPackages]=useState<Package[]>(()=>read(pkey,[]));const [quotes,setQuotes]=useState<Quote[]>(()=>read(qkey,[]));
 const [title,setTitle]=useState('');const [sessions,setSessions]=useState('6');const [regular,setRegular]=useState('300');const [price,setPrice]=useState('240');const [duration,setDuration]=useState('60');const [description,setDescription]=useState('');
 const discount=useMemo(()=>{const r=Number(regular),p=Number(price);return r>0?Math.max(0,Math.round((1-p/r)*100)):0},[regular,price]);
 const add=()=>{if(!title.trim()||Number(sessions)<2)return;const x={id:'pkg-'+Date.now(),title,sessions:Number(sessions),regular:Number(regular),price:Number(price),discount,duration:Number(duration),description};const n=[x,...packages];setPackages(n);localStorage.setItem(pkey,JSON.stringify(n));setTitle('');setDescription('')};
 const remove=(id:string)=>{const n=packages.filter(x=>x.id!==id);setPackages(n);localStorage.setItem(pkey,JSON.stringify(n))};
 const addQuote=(pkg:Package)=>{const x={id:'quote-'+Date.now(),client:lang==='ar'?'عميل تجريبي':'Demo client',packageId:pkg.id,price:pkg.price,note:lang==='ar'?'عرض مخصص قابل للتعديل':'Custom quote',status:'pending'};const n=[x,...quotes];setQuotes(n);localStorage.setItem(qkey,JSON.stringify(n))};
 return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-teal-800 to-cyan-700 p-7 text-white"><div className="flex items-center gap-3"><BadgeDollarSign/><div><h1 className="text-3xl font-black">{lang==='ar'?'باقات المتابعة طويلة المدى':'Long-term Follow-up Packages'}</h1><p className="mt-1 text-white/75">{lang==='ar'?'أنشئ باقات بعدة جلسات مع خصومات وعروض أسعار مخصصة':'Create multi-session packages with discounts and custom quotes'}</p></div></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-5"><section className="lg:col-span-2 rounded-2xl bg-white border p-6"><h2 className="text-xl font-extrabold flex items-center gap-2"><Plus/>إنشاء باقة</h2><div className="mt-4 space-y-3">
 {[[title,setTitle,'اسم الباقة','text'],[sessions,setSessions,'عدد الجلسات','number'],[regular,setRegular,'السعر قبل الخصم USD','number'],[price,setPrice,'سعر الباقة USD','number'],[duration,setDuration,'مدة الباقة بالأيام','number']].map((x:any)=><label key={x[2]} className="block text-sm font-semibold text-slate-600">{x[2]}<input value={x[0]} onChange={e=>x[1](e.target.value)} type={x[3]} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>)}
 <textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="وصف الباقة وشروط المتابعة" className="w-full rounded-xl border p-3 min-h-24"/>
 <div className="rounded-xl bg-teal-50 p-3 text-teal-800"><Percent className="inline h-4 w-4"/> الخصم المحسوب: <b>{discount}%</b></div><button onClick={add} className="w-full rounded-xl bg-teal-700 py-3 text-white font-bold">حفظ الباقة</button></div></section>
 <section className="lg:col-span-3 space-y-4">{packages.length===0?<div className="rounded-2xl bg-white border p-10 text-center text-slate-400">لا توجد باقات بعد.</div>:packages.map(p=><div key={p.id} className="rounded-2xl bg-white border p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-extrabold">{p.title}</h3><div className="mt-2 flex flex-wrap gap-3 text-sm text-slate-500"><span><Users className="inline h-4 w-4"/> {p.sessions} جلسات</span><span><Clock className="inline h-4 w-4"/> {p.duration} يوم</span><span className="text-emerald-700 font-bold">{p.discount}% خصم</span></div></div><button onClick={()=>remove(p.id)} className="text-rose-500"><Trash2/></button></div><p className="mt-3 text-slate-600">{p.description}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><span className="line-through text-slate-400">{p.regular} USD</span><b className="ms-3 text-2xl">{p.price} USD</b></div><button onClick={()=>addQuote(p)} className="rounded-xl bg-indigo-600 px-4 py-2 text-white font-bold">إنشاء عرض سعر مخصص</button></div></div>)}</section></div>
 <section className="mt-6 rounded-2xl bg-white border p-6"><h2 className="text-xl font-extrabold">عروض الأسعار المخصصة</h2><div className="mt-4 space-y-2">{quotes.length?quotes.map(q=><div key={q.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><span>{q.client}</span><b>{q.price} USD</b><span className="text-amber-700">{q.status}</span><CheckCircle2 className="text-teal-600"/></div>):<p className="text-slate-400">لا توجد عروض مخصصة بعد.</p>}</div></section>
 </div></div>
}