import {useState} from 'react';import {Wallet,Coins,Bell,Settings,Video,BookOpen,GraduationCap,MessageCircle,Briefcase,Smile,ShieldCheck,Plus,Send} from 'lucide-react';import {useI18n} from '@/lib/i18n';
const badges=[['🩺','طب عام'],['❤️','قلب'],['🧠','نفسي'],['🧒','أطفال'],['🦷','أسنان'],['👁️','عيون'],['🦴','عظام'],['🧬','وراثة'],['🧪','تحاليل'],['🩻','أشعة'],['🌿','تأهيل'],['🧑‍⚕️','أخصائي موثق']];
export default function SpecialistStudioPage(){const {lang,dir}=useI18n();const [tab,setTab]=useState('content');const [wallet]=useState(()=>JSON.parse(localStorage.getItem('sb1_specialist_wallet')||'{"balance":1250,"points":340,"due":180}'));const tabs=[['content','المحتوى',Video],['articles','مقالاتي',BookOpen],['courses','الدورات',GraduationCap],['questions','الاستشارات والأسئلة',MessageCircle],['portfolio','المحفظة والحسابات',Briefcase],['control','الإشعارات والتحكم',Settings]];return <div dir={dir} className="min-h-screen bg-slate-50 pt-24 pb-16"><div className="mx-auto max-w-7xl px-4">
 <div className="rounded-3xl bg-gradient-to-br from-indigo-900 via-teal-800 to-cyan-700 p-7 text-white"><h1 className="text-3xl font-black">استوديو الأخصائي</h1><p className="mt-2 text-white/75">إدارة الصفحة، المحتوى، الجلسات، الدورات والحسابات من مكان واحد.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><Wallet className="inline h-5 w-5"/><span className="ms-2 text-sm">رصيد الأموال</span><b className="block text-2xl mt-1">{wallet.balance} USD</b></div><div className="rounded-2xl bg-white/10 p-4"><Coins className="inline h-5 w-5"/><span className="ms-2 text-sm">رصيد النقاط</span><b className="block text-2xl mt-1">{wallet.points}</b></div><div className="rounded-2xl bg-white/10 p-4"><Briefcase className="inline h-5 w-5"/><span className="ms-2 text-sm">المستحقات</span><b className="block text-2xl mt-1">{wallet.due} USD</b></div></div></div>
 <div className="mt-5 flex gap-2 overflow-x-auto">{tabs.map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={'whitespace-nowrap rounded-xl px-4 py-3 font-bold '+(tab===k?'bg-teal-700 text-white':'bg-white border text-slate-600')}><I className="inline h-4 w-4 me-1"/>{l}</button>)}</div>
 <div className="mt-5 rounded-2xl bg-white border p-6">{tab==='content'&&<div className="grid md:grid-cols-3 gap-4"><button className="rounded-2xl border p-6 text-start hover:border-teal-500"><Video className="text-teal-600"/><b className="block mt-3">نشر فيديو / ريلز</b><span className="text-sm text-slate-500">رفع فيديو وتحديد اللغة والجمهور.</span></button><button className="rounded-2xl border p-6 text-start"><Plus className="text-indigo-600"/><b className="block mt-3">نشر قصة يومية</b><span className="text-sm text-slate-500">قصة مؤقتة لمدة 24 ساعة.</span></button><button className="rounded-2xl border p-6 text-start"><Smile className="text-amber-500"/><b className="block mt-3">الإيموجي والبادجات</b><span className="text-sm text-slate-500">اختر شارات طبية ونفسية.</span></button></div>}
 {tab==='articles'&&<div><h2 className="text-xl font-extrabold">مقالاتي</h2><p className="text-slate-500 mt-2">إنشاء المقال وتحديد اللغة قبل النشر.</p><a href="/specialist/content" className="mt-4 inline-block rounded-xl bg-teal-700 text-white px-4 py-2 font-bold">فتح إدارة المحتوى</a></div>}
 {tab==='courses'&&<div><h2 className="text-xl font-extrabold">الدورات والكورسات</h2><p className="text-slate-500 mt-2">إنشاء دورة، تحديد السعر واللغة وربط غرفة الاجتماعات والدردشة.</p><a href="/courses" className="mt-4 inline-block rounded-xl bg-teal-700 text-white px-4 py-2 font-bold">فتح الدورات</a></div>}
 {tab==='questions'&&<div><h2 className="text-xl font-extrabold">الاستشارات والأسئلة السابقة</h2><p className="text-slate-500 mt-2">متابعة الأسئلة والإجابات والاستشارات.</p><a href="/questions" className="mt-4 inline-block rounded-xl bg-teal-700 text-white px-4 py-2 font-bold">فتح الأسئلة</a></div>}
 {tab==='portfolio'&&<div><h2 className="text-xl font-extrabold">المحفظة والحسابات</h2><div className="mt-4 grid md:grid-cols-3 gap-3"><div className="rounded-xl bg-slate-50 p-4">الرصيد<br/><b>{wallet.balance} USD</b></div><div className="rounded-xl bg-slate-50 p-4">النقاط<br/><b>{wallet.points}</b></div><div className="rounded-xl bg-slate-50 p-4">المستحقات<br/><b>{wallet.due} USD</b></div></div><a href="/specialist/packages" className="mt-4 inline-block rounded-xl bg-indigo-600 text-white px-4 py-2 font-bold">باقات المتابعة طويلة المدى</a></div>}
 {tab==='control'&&<div><h2 className="text-xl font-extrabold">الإشعارات والتحكم</h2><div className="mt-4 space-y-3"><label className="flex items-center justify-between rounded-xl bg-slate-50 p-4">إشعارات الأسئلة الجديدة <input type="checkbox" defaultChecked/></label><label className="flex items-center justify-between rounded-xl bg-slate-50 p-4">إشعارات الحجوزات <input type="checkbox" defaultChecked/></label><a href="/notifications/private" className="block rounded-xl border p-4 font-bold"><Bell className="inline h-5 w-5 me-2"/>الإشعارات الخاصة</a></div></div>}</div>
 <div className="mt-5 rounded-2xl bg-white border p-6"><div className="flex items-center gap-2"><ShieldCheck className="text-teal-600"/><h2 className="text-xl font-extrabold">بنك البادجات الطبية والنفسية</h2></div><div className="mt-4 flex flex-wrap gap-2">{badges.map(([e,n])=><button key={n} className="rounded-full border bg-slate-50 px-4 py-2 hover:border-teal-500">{e} {n}</button>)}</div></div>
 </div></div>}