import { useEffect,useState } from 'react';
import { CheckCircle2, XCircle, Send } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
type Msg={sender:'patient'|'doctor';body:string;time:string};type S={id:string;patient:string;doctor:any;status:string;messages:Msg[];messageCount:number;maxMessages:number;specialty:string;changeReason?:string;closeReason?:string};
const get=()=>{try{return JSON.parse(localStorage.getItem('sb1_free_sessions')||'[]')}catch{return []}};const set=(x:any)=>{localStorage.setItem('sb1_free_sessions',JSON.stringify(x));window.dispatchEvent(new Event('sb1-session-change'))};
export default function SpecialistFreeSessionsPage(){const {dir}=useI18n();const [items,setItems]=useState<S[]>([]);const [reason,setReason]=useState('');const [reply,setReply]=useState('');const [selected,setSelected]=useState<S|null>(null);useEffect(()=>{const f=()=>setItems(get());f();window.addEventListener('sb1-session-change',f);return()=>window.removeEventListener('sb1-session-change',f)},[]);
const update=(s:S)=>{const all=items.map(x=>x.id===s.id?s:x);set(all);setItems(all);setSelected(s)};
const accept=(s:S)=>{const next={...s,status:'active'};update(next)};
const reject=(s:S)=>{const next={...s,status:'rejected',closeReason:reason||'رفض الطلب من الأخصائي'};update(next);setReason('')};
const close=(s:S)=>{if(!reason.trim())return alert('اكتب سبب الإغلاق');const next={...s,status:'closed',closeReason:reason.trim()};update(next);setReason('')};
const send=()=>{if(!selected||!reply.trim()||selected.messageCount>=20)return;const m={sender:'doctor',body:reply.trim(),time:new Date().toLocaleTimeString()};update({...selected,messages:[...selected.messages,m],messageCount:selected.messageCount+1});setReply('')};
return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4"><div className="rounded-3xl bg-white border p-6"><h1 className="text-2xl font-extrabold">طلبات الجلسات المجانية للأخصائي</h1><p className="text-gray-500 mt-2">لا يمكن للمريض فتح الجلسة قبل قبول الطلب من هنا.</p></div><div className="grid lg:grid-cols-[360px_1fr] gap-5 mt-5"><div className="space-y-3">{items.map(s=><button key={s.id} onClick={()=>setSelected(s)} className="w-full text-right rounded-2xl bg-white border p-4"><b>{s.patient}</b><p className="text-sm text-gray-500">{s.specialty} · {s.messageCount}/20 · {s.status}</p></button>)}</div><div className="rounded-2xl bg-white border p-5">{!selected?<div className="p-12 text-center text-gray-500">اختر طلباً</div>:<><h2 className="font-extrabold text-xl">{selected.patient}</h2><p className="text-gray-500">{selected.specialty}</p>{selected.status==='pending'&&<div className="flex gap-2 mt-5"><button onClick={()=>accept(selected)} className="rounded-xl bg-teal-600 text-white px-4 py-2"><CheckCircle2 className="inline h-4 w-4"/> قبول</button><button onClick={()=>reject(selected)} className="rounded-xl bg-red-50 text-red-700 px-4 py-2"><XCircle className="inline h-4 w-4"/> رفض</button></div>}<div className="mt-5 space-y-2 max-h-80 overflow-auto">{selected.messages.map((m,i)=><div key={i} className="rounded-xl bg-gray-50 p-3"><b>{m.sender==='doctor'?'الأخصائي':'المريض'}</b><p>{m.body}</p></div>)}</div>{selected.status==='active'&&<><div className="mt-4 flex gap-2"><input value={reply} onChange={e=>setReply(e.target.value)} className="input-field flex-1" placeholder="اكتب ردك"/><button onClick={send} className="btn-primary"><Send/></button></div><textarea value={reason} onChange={e=>setReason(e.target.value)} className="input-field w-full mt-3" placeholder="سبب الإغلاق إذا أردت إغلاق الجلسة"/><button onClick={()=>close(selected)} className="mt-2 rounded-xl bg-red-50 text-red-700 px-4 py-2">إغلاق الجلسة</button></>}</>}</div></div></div></div>}