import {useEffect,useState} from 'react';
import {Plus,Save,Trash2,ShoppingBag,PackageCheck,RefreshCcw,ArrowRight} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {defaultStoreProducts,type StoreProduct,StoreAudience,StoreProductType} from '@/lib/storeCatalog';
import {useRouter} from '@/lib/router';
export default function StoreAdminPage(){
 const {navigate}=useRouter(); const [authed,setAuthed]=useState(false); const [products,setProducts]=useState<StoreProduct[]>([]); const [orders,setOrders]=useState<any[]>([]); const [editing,setEditing]=useState<StoreProduct|null>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'products'|'orders'>('products'); const [msg,setMsg]=useState('');
 useEffect(()=>{setAuthed(!!localStorage.getItem('admin_auth'))},[]);
 const load=async()=>{setLoading(true);const [p,o]=await Promise.all([supabase.from('store_products').select('*').order('sort_order',{ascending:true}),supabase.from('store_orders').select('*').order('created_at',{ascending:false})]);setProducts(p.data&&p.data.length?p.data:defaultStoreProducts);setOrders(o.data||[]);setLoading(false)};useEffect(()=>{if(authed)load()},[authed]);
 const blank=():StoreProduct=>({id:'store-'+Date.now(),name:'منتج جديد',description:'',image_url:'',price:0,currency:'USD',product_type:'other',audience:'all',language:'all',active:true,stock:null,sort_order:99,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});
 const save=async()=>{if(!editing)return;const payload={...editing,updated_at:new Date().toISOString()};const exists=products.some(p=>p.id===editing.id);if(exists)await supabase.from('store_products').update(payload).eq('id',editing.id);else await supabase.from('store_products').insert(payload);setMsg('تم حفظ المنتج');setEditing(null);load()};
 const remove=async(id:string)=>{if(!confirm('حذف المنتج؟'))return;await supabase.from('store_products').delete().eq('id',id);setProducts(p=>p.filter(x=>x.id!==id));};
 const updateOrder=async(id:string,status:string)=>{await supabase.from('store_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);load()};
 if(!authed)return <div className="min-h-screen pt-28 text-center"><p>يجب تسجيل الدخول إلى لوحة التحكم أولاً.</p><button onClick={()=>navigate('/admin')} className="mt-4 rounded-xl bg-teal-600 text-white px-5 py-2">لوحة التحكم</button></div>;
 return <div className="min-h-screen bg-gray-50 pt-24 pb-16" dir="rtl"><div className="mx-auto max-w-7xl px-4">
 <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><h1 className="text-3xl font-extrabold">إدارة المتجر</h1><p className="text-gray-500 mt-1">تحكم كامل في الاسم والصورة والسعر والوصف واللغة والفئة والجمهور وحالة المنتج والطلبات.</p></div><button onClick={()=>navigate('/admin')} className="rounded-xl border bg-white px-4 py-2"><ArrowRight className="inline h-4 w-4 me-1"/>لوحة التحكم</button></div>
 <div className="flex gap-2 mb-5"><button onClick={()=>setTab('products')} className={'rounded-xl px-4 py-2 font-bold '+(tab==='products'?'bg-teal-600 text-white':'bg-white border')}>المنتجات</button><button onClick={()=>setTab('orders')} className={'rounded-xl px-4 py-2 font-bold '+(tab==='orders'?'bg-teal-600 text-white':'bg-white border')}>الطلبات</button><button onClick={load} className="rounded-xl bg-white border px-4 py-2"><RefreshCcw className="inline h-4 w-4"/></button></div>
 {msg&&<div className="mb-4 rounded-xl bg-green-50 p-3 text-green-700">{msg}</div>}
 {loading?<div className="py-16 text-center">جاري التحميل...</div>:tab==='products'?<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{products.map(p=><div key={p.id} className="rounded-2xl bg-white border p-4 flex flex-wrap items-center gap-4"><img src={p.image_url||'https://placehold.co/120x80'} className="h-20 w-28 rounded-xl object-cover"/><div className="flex-1 min-w-[220px]"><b>{p.name}</b><p className="text-sm text-gray-500">{p.description}</p><div className="mt-2 flex gap-2 text-xs"><span className="bg-gray-100 rounded-full px-2 py-1">{p.price} {p.currency}</span><span className="bg-indigo-50 text-indigo-700 rounded-full px-2 py-1">{p.audience==='specialist'?'أخصائيون فقط':'الجميع'}</span><span className="bg-teal-50 text-teal-700 rounded-full px-2 py-1">{p.active?'نشط':'مخفي'}</span></div></div><button onClick={()=>setEditing({...p})} className="rounded-xl bg-blue-50 text-blue-700 px-4 py-2">تعديل</button><button onClick={()=>remove(p.id)} className="rounded-xl bg-red-50 text-red-600 p-2"><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="rounded-2xl bg-white border p-5 h-fit sticky top-24"><div className="flex justify-between items-center mb-4"><h2 className="font-extrabold">{editing?'تعديل المنتج':'إضافة منتج'}</h2><button onClick={()=>setEditing(blank())} className="rounded-xl bg-teal-600 text-white px-3 py-2"><Plus className="inline h-4 w-4"/> جديد</button></div>{editing&&<div className="space-y-3">{[['name','اسم المنتج'],['description','الوصف'],['image_url','رابط الصورة'],['price','السعر'],['currency','العملة'],['language','لغة المحتوى']].map(([k,l])=><input key={k} value={String((editing as any)[k]??'')} onChange={e=>setEditing({...editing,[k]:k==='price'?Number(e.target.value):e.target.value})} placeholder={l} className="input-field"/>)}
 <select value={editing.product_type} onChange={e=>setEditing({...editing,product_type:e.target.value as StoreProductType})} className="input-field"><option value="question_package">باقة أسئلة</option><option value="course">دورة</option><option value="book">كتاب</option><option value="subscription">اشتراك</option><option value="consultation">استشارة</option><option value="test">اختبار</option><option value="app">تطبيق</option><option value="specialist_service">خدمة أخصائي</option><option value="other">أخرى</option></select>
 <select value={editing.audience} onChange={e=>setEditing({...editing,audience:e.target.value as StoreAudience})} className="input-field"><option value="all">العميل والأخصائي</option><option value="specialist">الأخصائيون فقط</option></select>
 <input type="number" value={editing.sort_order} onChange={e=>setEditing({...editing,sort_order:Number(e.target.value)})} placeholder="ترتيب العرض" className="input-field"/>
 <label className="flex items-center gap-2"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> المنتج ظاهر في المتجر</label>
 <button onClick={save} className="w-full rounded-xl bg-teal-600 text-white py-3 font-bold"><Save className="inline h-5 w-5 me-2"/>حفظ كل التفاصيل</button></div>}</div></div>:<div className="space-y-3">{orders.length===0?<div className="rounded-2xl bg-white p-8 text-center text-gray-500">لا توجد طلبات بعد.</div>:orders.map(o=><div key={o.id} className="rounded-2xl bg-white border p-5 flex flex-wrap items-center justify-between gap-4"><div><b>{o.reference_id||o.id}</b><p className="text-sm text-gray-500">{Number(o.amount||0).toFixed(2)} {o.currency||'USD'} · {new Date(o.created_at).toLocaleString()}</p></div><div className="flex gap-2"><select value={o.status||'pending'} onChange={e=>updateOrder(o.id,e.target.value)} className="input-field w-auto"><option value="pending">معلق</option><option value="paid">مدفوع</option><option value="fulfilled">تم التنفيذ</option><option value="cancelled">ملغي</option><option value="refunded">مسترد</option></select><PackageCheck className="h-7 w-7 text-teal-600"/></div></div>)}</div>}
 </div></div>
}