import {useEffect,useState} from 'react';
import {CheckCircle2,XCircle,Calendar,Video,Clock,Save,Settings2} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import {getAppointments,acceptAppointment,rejectAppointment,rescheduleAppointment,canReschedule,type Appointment,formatRemaining,scheduleAppointmentReminders} from '@/lib/appointments';
import {getDoctorSessionConfig,saveDoctorSessionConfig,formatDuration,type SessionOption} from '@/lib/appointmentConfig';
import {virtualDoctorsForSpecialty} from '@/lib/catalog';

export default function VideoAppointmentDoctorPage(){
 const{dir,lang}=useI18n();const[items,setItems]=useState<Appointment[]>([]);const[selected,setSelected]=useState<Appointment|null>(null);const[time,setTime]=useState('');const[reason,setReason]=useState('');const[now,setNow]=useState(Date.now());const[doctorId,setDoctorId]=useState('virtual-doctor-settings');const[options,setOptions]=useState<SessionOption[]>(getDoctorSessionConfig('virtual-doctor-settings').options);const[message,setMessage]=useState('');
 const refresh=()=>{const all=getAppointments();all.filter(a=>a.status==='accepted').forEach(scheduleAppointmentReminders);setItems(all);setNow(Date.now())};
 useEffect(()=>{refresh();const id=setInterval(refresh,1000);window.addEventListener('sb1-appointments-change',refresh);return()=>{clearInterval(id);window.removeEventListener('sb1-appointments-change',refresh)}},[]);
 const saveConfig=()=>{saveDoctorSessionConfig({doctorId,options,updatedAt:new Date().toISOString()});setMessage('تم حفظ مدد وأسعار الجلسات');};
 const addOption=()=>setOptions(x=>x.length>=6?x:[...x,{durationMinutes:90,price:60,enabled:true}]);
 const update=(i:number,k:keyof SessionOption,v:any)=>setOptions(x=>x.map((o,n)=>n===i?{...o,[k]:v}:o));
 return <div dir={dir} className="min-h-screen bg-gray-50 pt-24 pb-24"><div className="mx-auto max-w-6xl px-4">
 <div className="rounded-3xl bg-white border p-7"><h1 className="text-3xl font-extrabold">إدارة جلسات الفيديو للأخصائي</h1><p className="mt-2 text-gray-500">طلبات العملاء والجلسات المقبولة والأسعار والمواعيد. هذه الصفحة لا تظهر في القائمة الأفقية.</p></div>
 <div className="mt-5 rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold flex items-center gap-2"><Settings2 className="h-5 w-5"/>مدد وأسعار الجلسات</h2><p className="text-sm text-gray-500 mt-1">يمكن للأخصائي اختيار سعر واحد أو أكثر، والمدة من 15 دقيقة حتى 3 ساعات.</p></div><button onClick={saveConfig} className="rounded-xl bg-teal-600 px-4 py-2 font-bold text-white"><Save className="inline h-4 w-4"/> حفظ</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{options.map((o,i)=><div key={i} className="rounded-xl border p-4"><input type="number" min="15" max="180" step="15" value={o.durationMinutes} onChange={e=>update(i,'durationMinutes',Math.min(180,Math.max(15,+e.target.value)))} className="w-full rounded-lg border p-2"/><div className="mt-2 text-xs text-gray-500">{formatDuration(o.durationMinutes,lang)}</div><input type="number" min="0" value={o.price} onChange={e=>update(i,'price',Math.max(0,+e.target.value))} className="mt-2 w-full rounded-lg border p-2" placeholder="السعر USD"/><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={o.enabled} onChange={e=>update(i,'enabled',e.target.checked)}/> متاح للحجز</label></div>)}</div><button onClick={addOption} className="mt-3 rounded-xl border px-4 py-2">+ إضافة مدة/سعر</button>{message&&<p className="mt-3 text-sm text-teal-700">{message}</p>}</div>
 <div className="mt-5 rounded-2xl border bg-blue-50 p-5 text-sm text-blue-900"><b>قواعد تغيير الموعد:</b> التغيير قبل 3 ساعات على الأقل. المرة الأولى مجانية، الثانية مجانية فقط قبل 12 ساعة، الثالثة برسوم 50%، والرابعة مرفوضة. تغيير الطبيب للعميل متاح قبل 24 ساعة، مرة أولى مجانية، الثانية برسوم 50%، والثالثة مرفوضة.</div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><div className="space-y-3">{items.map(a=><button key={a.id} onClick={()=>{setSelected(a);setTime(a.scheduledAt?.slice(0,16)||'')}} className="w-full rounded-2xl border bg-white p-4 text-start hover:border-teal-300"><b>{a.patientName}</b><p className="text-sm text-gray-500">{a.doctorName}</p><p className="text-xs text-gray-400">{a.durationMinutes} دقيقة · {a.price} {a.currency}</p><span className="mt-2 inline-block rounded-full bg-amber-50 px-2 py-1 text-xs">{a.status==='pending'?'بانتظار القبول':a.status}</span></button>)}</div>
 <div className="rounded-2xl border bg-white p-6">{!selected?<div className="py-16 text-center text-gray-500">اختر جلسة</div>:<><h2 className="text-2xl font-extrabold">{selected.patientName}</h2><p className="text-gray-500">{selected.doctorName} · {selected.specialty}</p><div className="mt-5 rounded-2xl bg-gray-50 p-4"><Calendar className="inline h-4 w-4"/> {selected.scheduledAt?new Date(selected.scheduledAt).toLocaleString():'غير محدد'} · {selected.durationMinutes} دقيقة · {selected.price} {selected.currency}</div>{selected.status==='pending'&&<><label className="mt-4 block font-bold">الموعد الذي ستقبله</label><input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/><div className="mt-4 flex gap-2"><button onClick={()=>{if(!time)return;acceptAppointment(selected.id,new Date(time).toISOString());refresh();setSelected(null)}} className="rounded-xl bg-teal-600 px-5 py-3 font-bold text-white"><CheckCircle2 className="inline h-4 w-4"/> قبول</button><button onClick={()=>{if(!reason.trim())return alert('اكتب سبب الرفض');rejectAppointment(selected.id,reason);refresh();setSelected(null);setReason('')}} className="rounded-xl bg-red-50 px-5 py-3 font-bold text-red-700"><XCircle className="inline h-4 w-4"/> رفض</button></div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="سبب الرفض" className="mt-4 w-full rounded-xl border p-3"/></>}{selected.status==='accepted'&&selected.scheduledAt&&<><div className="mt-5 rounded-2xl bg-teal-50 p-5"><p className="font-bold text-teal-800"><Video className="inline h-4 w-4"/> الجلسة المقبولة</p><p className="mt-2 text-2xl font-extrabold text-teal-700">{formatRemaining(new Date(selected.scheduledAt).getTime()-now,lang)}</p><a href={selected.meetingUrl||('https://meet.jit.si/SB1-'+selected.id)} target="_blank" rel="noreferrer" className="mt-3 inline-block rounded-xl bg-teal-600 px-5 py-2 text-white">فتح الفيديو</a></div><div className="mt-4 rounded-2xl border p-4"><b>تغيير الموعد</b><p className="mt-1 text-xs text-gray-500">{canReschedule(selected,'doctor').reason||'مسموح حسب القواعد'}</p><input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} className="mt-3 w-full rounded-xl border p-3"/><button onClick={()=>{const rule=canReschedule(selected,'doctor');if(!rule.ok)return alert(rule.reason);const paid=rule.fee?rule.fee:0;if(rule.fee&&!confirm('يلزم دفع 50% من قيمة الجلسة: '+rule.fee+' '+selected.currency+'. تأكيد الدفع التجريبي؟'))return;rescheduleAppointment(selected.id,new Date(time).toISOString(),'doctor',paid);refresh();setSelected({...selected,scheduledAt:new Date(time).toISOString(),rescheduleCount:selected.rescheduleCount+1})}} className="mt-3 rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">تغيير الموعد</button></div></>}</>}</div></div>
 </div></div>
}
