import {useEffect,useMemo,useRef,useState} from 'react';
import {X,Upload,Search,Play,Pause,Volume2,VolumeX,Image as ImageIcon,Music2,Smile,Sticker,Film,SlidersHorizontal,CalendarClock,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import {supabase} from '@/lib/supabase';

type Mode='post'|'image'|'video'|'reel'|'story';
type Asset={id:string;name:string;url:string;thumbnail?:string;kind:'image'|'video'|'audio'|'gif'|'sticker';source?:string;duration?:number;embedUrl?:string};
type Payload={mode:Mode;media?:Asset[];title:string;text:string;description:string;muted:boolean;audio?:Asset;audioStart:number;audioEnd:number;filter:string;textColor:string;textSize:number;font:string;background:string;emoji:string[];gifs:Asset[];stickers:Asset[];scheduledAt?:string};

const filters=[['none','أصلي'],['brightness(1.08) saturate(1.08)','مضيء'],['contrast(1.15) saturate(1.25)','حيوي'],['saturate(.65)','هادئ'],['sepia(.35) saturate(1.15)','دافئ'],['grayscale(1)','أبيض وأسود'],['contrast(1.25) brightness(.96) saturate(1.15)','سينمائي']];
const emojiSeed=['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😍','🥰','😘','😎','🤩','🥳','😢','😭','😡','🤯','😱','🤔','🤗','😴','🤍','❤️','🧡','💛','💚','💙','💜','🖤','💕','💖','✨','⭐','🔥','🎉','🎁','🎂','🍕','☕','⚽','🏆','🎮','🎵','🎤','🎧','📸','🎬','📚','🩺','💊','🏥','💡','✅','❌','❗','❓','🔔','🌈','☀️','🌙','🌸','🌹','🌻','🌊','🌍','🚀','💎','🎯','🛍️','💰','📱','💻','✈️','🕊️','👍','👎','👏','🙌','🙏','💪','🫶','🤝'];
const emojis=Array.from({length:2000},(_,i)=>emojiSeed[i%emojiSeed.length]+(i<emojiSeed.length?'':String.fromCodePoint(0x1F3FB+(i%5))));

async function durationOf(url:string){return new Promise<number>(resolve=>{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>resolve(Number.isFinite(v.duration)?v.duration:0);v.onerror=()=>resolve(0);v.src=url})}
async function uploadAsset(file:File,pageId:string):Promise<Asset>{let url='';try{const path=pageId+'/'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await supabase.storage.from('specialist-content').upload(path,file,{upsert:false,contentType:file.type});if(!u.error)url=supabase.storage.from('specialist-content').getPublicUrl(path).data.publicUrl}catch{}if(!url)url=URL.createObjectURL(file);const kind=file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':file.type==='image/gif'?'gif':'image';return{id:'upload-'+Date.now(),name:file.name,url,kind,source:'الجهاز',duration:kind==='video'?await durationOf(url):0}}

export default function MediaPublishWizard({open,onClose,onPublish,initialMedia,pageId='current'}:{open:boolean;onClose:()=>void;onPublish:(p:Payload)=>void;initialMedia?:Asset;pageId?:string}){
 const [step,setStep]=useState(1),[mode,setMode]=useState<Mode>(initialMedia?.kind==='video'?'video':initialMedia?.kind==='image'?'image':'post');
 const titleRef=useRef<HTMLInputElement|null>(null);
 const [media,setMedia]=useState<Asset[]>(initialMedia?[initialMedia]:[]),[title,setTitle]=useState(''),[text,setText]=useState(''),[description,setDescription]=useState('');
 const [transitions,setTransitions]=useState<string[]>([]);
 const [muted,setMuted]=useState(false),[audio,setAudio]=useState<Asset|null>(null),[audioStart,setAudioStart]=useState(0),[audioEnd,setAudioEnd]=useState(0),[audioPlaying,setAudioPlaying]=useState(false),audioEl=useRef<HTMLAudioElement|null>(null);
 const [library,setLibrary]=useState<Asset[]>([]),[libraryKind,setLibraryKind]=useState<'image'|'gif'|'sticker'|'audio'|'emoji'|null>(null),[libraryQuery,setLibraryQuery]=useState(''),[libraryLoading,setLibraryLoading]=useState(false),[librarySource,setLibrarySource]=useState<'openverse'|'pixabay'>('openverse');
 const [emoji,setEmoji]=useState<string[]>([]),[filter,setFilter]=useState('none'),[textColor,setTextColor]=useState('#ffffff'),[textSize,setTextSize]=useState(24),[font,setFont]=useState('Arial'),[background,setBackground]=useState('#111827');
 const [scheduleMode,setScheduleMode]=useState<'now'|'later'>('now'),[scheduleAt,setScheduleAt]=useState(''),[notice,setNotice]=useState('');
 const current=media[0];const video=current?.kind==='video';const videoDuration=current?.duration||0;const imageCount=media.filter(x=>x.kind==='image').length;const audioLimit=mode==='story'?20:mode==='reel'?180:(videoDuration||Infinity);

 useEffect(()=>{if(open){setStep(1);setNotice('');if(initialMedia){setMedia([initialMedia]);setMode(initialMedia.kind==='video'?'video':initialMedia.kind==='image'?'image':'post')}}},[open,initialMedia]);
 useEffect(()=>{if(video&&mode!=='video')setMode('video')},[video,mode]);

 const loadLibrary=async(kind:'image'|'gif'|'sticker'|'audio'|'emoji',q='')=>{
   setLibraryKind(kind);setLibraryQuery(q);setLibraryLoading(true);
   if(kind==='emoji'){setLibrary([]);setLibraryLoading(false);return}
   try{
     const term=q.trim()||(kind==='image'?'nature':kind==='audio'?'music':kind);
     const provider=kind==='image'?(librarySource==='pixabay'?'pixabay_images':'google_images'):kind;
     const r=await fetch('/api/social-search?provider='+provider+'&q='+encodeURIComponent(term));
     const x=await r.json();
     if(!r.ok)throw new Error(x.error||'تعذر البحث');
     setLibrary((x.items||[]).map((i:any)=>({
       id:String(i.id),name:i.title||i.name||'محتوى',url:i.image||i.url,thumbnail:i.thumbnail||i.image||i.url,
       kind:kind==='audio'?'audio':kind,source:i.source||provider,duration:Number(i.duration||0),embedUrl:i.embedUrl
     })));
   }catch{setLibrary([]);setNotice('تعذر تحميل المكتبة. حاول البحث بكلمة أخرى أو تحقق من مصدر المحتوى.')}
   finally{setLibraryLoading(false)}
 };
 const choose=(a:Asset)=>{if(a.kind==='audio'){setAudio(a);setAudioStart(0);setAudioEnd(a.duration||0)}else if(a.kind==='image'){setMedia(v=>[...v,a].slice(0,12));}else setMedia(v=>[a,...v.filter(x=>x.kind!==a.kind)].slice(0,12));setLibraryKind(null)};
 const chooseFile=async(e:any)=>{const files=Array.from(e.target.files||[]) as File[];if(!files.length)return;const assets=await Promise.all(files.slice(0,12).map(f=>uploadAsset(f,pageId)));const aud=assets.find(a=>a.kind==='audio');if(aud)setAudio(aud);const vids=assets.filter(a=>a.kind==='video');if(vids.length){setMedia([vids[0]]);setMode('video');}else setMedia(v=>[...v,...assets.filter(a=>a.kind==='image')].slice(0,12));e.target.value=''};
 const toggleAudio=()=>{if(!audio)return;if(audioPlaying){audioEl.current?.pause();setAudioPlaying(false)}else{audioEl.current?.play().catch(()=>{});setAudioPlaying(true)}};
 const validate=()=>{if(mode==='post'&&!text.trim()&&!media.length)return'اكتب نص المنشور أو اختر وسائط.';if(mode!=='post'&&!media.length)return'اختر صورة أو فيديو من المكتبة أو الجهاز.';if(video&&mode!=='video')return'الفيديو المختار يُنشر كفيديو فقط. لا يمكن تحويله إلى منشور أو صورة أو قصة أو Reel.';if(!video&&(mode==='story'||mode==='reel')&&!audio)return'لتحويل الصور إلى قصة أو Reel يجب إضافة مقطع صوتي أولاً.';if(mode==='story'&&audio&&audioEnd-audioStart>20)return'القصة حدها الأقصى 20 ثانية.';if(mode==='reel'&&audio&&audioEnd-audioStart>180)return'Reel حده الأقصى 3 دقائق.';if(scheduleMode==='later'&&(!scheduleAt||new Date(scheduleAt).getTime()<=Date.now()))return'اختر تاريخاً ووقتاً مستقبلياً صحيحاً.';return''};
 const publish=()=>{const err=validate();if(err){setNotice(err);return}const finalMode=video?(videoDuration>180?'video':mode):mode;onPublish({mode:finalMode,media,title,text,description,muted,audio:audio||undefined,audioStart,audioEnd:audioEnd||Math.min(audioLimit===Infinity?180:audioLimit,180),filter,textColor,textSize,font,background,emoji,gifs:media.filter(x=>x.kind==='gif'),stickers:media.filter(x=>x.kind==='sticker'),scheduledAt:scheduleMode==='later'?scheduleAt:''});onClose()};
 const next=()=>{const err=validate();if(step===1&&err){setNotice(err);return}if(step===3&&audio&&audioLimit!==Infinity&&audioEnd>audioLimit){setNotice('المقطع الصوتي أطول من المدة المسموحة.');return}setStep(s=>Math.min(6,s+1))};
 const preview=useMemo(()=>{if(video)return <video key={current?.url} src={current?.url} controls playsInline autoPlay muted={muted} className="max-h-[52vh] w-full object-contain" style={{filter}}/>;if(media.length>1)return <div className="grid grid-cols-2 gap-1">{media.filter(x=>x.kind==='image').map((x,i)=><img key={x.id+i} src={x.url} alt="" className="max-h-64 w-full object-cover" style={{filter}}/>)}</div>;return current?<img src={current.url} alt="" className="max-h-[52vh] w-full object-contain" style={{filter}}/>:null},[current,muted,filter,media,video]);
 if(!open)return null;
 const stages=[['المحتوى','اختر الوسائط'],['التصميم','النص والعناصر'],['الصوت','الموسيقى والقص'],['التأثيرات','الفلاتر'],['المعاينة','راجع النتيجة'],['النشر','الوقت والنشر']];
 return <div className="fixed inset-0 z-[300] bg-slate-950/80 p-2 sm:p-6" dir="rtl"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-[28px] bg-[#f7f8fa] shadow-2xl">
  <header className="flex items-center justify-between border-b bg-white px-5 py-4"><div><div className="text-xl font-black">غرفة إنشاء المنشور</div><div className="text-xs text-slate-500">كل مرحلة لها معاينة حية داخل الغرفة</div></div><button onClick={onClose} className="rounded-full p-2 hover:bg-slate-100"><X/></button></header>
  <div className="grid grid-cols-6 gap-1 border-b bg-white p-2">{stages.map((s,i)=><button key={s[0]} onClick={()=>{setStep(i+1);if(i+1>step)setTransitions(v=>[...v,s[0]].slice(-3))}} className={'relative overflow-hidden rounded-xl px-2 py-3 text-right transition-all duration-300 '+(step===i+1?'bg-teal-700 text-white scale-[1.02] shadow-lg':'bg-slate-50 hover:bg-teal-50')}>{i<step&&<span className="absolute inset-x-0 bottom-0 h-1 bg-emerald-400"/>}<b className="block text-xs">{i+1}. {s[0]}</b><span className="hidden text-[9px] opacity-80 sm:block">{s[1]}</span></button>)}</div>
  <main className="min-h-0 flex-1 overflow-y-auto p-4 lg:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_380px]"><section className="min-w-0 space-y-4">
   {step===1&&<div className="rounded-3xl bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><b className="text-lg">اختيار المحتوى</b><p className="text-xs text-slate-500">المكتبات تفتح كنافذة اختيار مستقلة، وليست صفوفاً تحت البحث.</p></div><select value={mode} onChange={e=>setMode(e.target.value as Mode)} disabled={video} className="rounded-xl border px-3 py-2 text-sm font-bold disabled:bg-slate-100"><option value="post">منشور</option><option value="image">صورة</option><option value="video">فيديو</option><option value="reel">Reel</option><option value="story" disabled={video&&videoDuration>180}>قصة</option></select></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[['image','مكتبة الصور',ImageIcon],['audio','مكتبة الصوت',Music2],['gif','مكتبة GIF',Film],['sticker','مكتبة Sticker',Sticker],['emoji','مكتبة Emoji',Smile]].map(([k,l,I]:any)=><button key={k} onClick={()=>loadLibrary(k)} className="rounded-2xl border bg-slate-50 p-4 text-center hover:border-teal-500 hover:bg-teal-50"><I className="mx-auto mb-2 h-7 w-7 text-teal-700"/><b className="text-xs">{l}</b></button>)}</div><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed p-5 font-bold"><Upload/> رفع صور أو فيديو من الجهاز<input type="file" multiple accept="image/*,video/*" className="hidden" onChange={chooseFile}/></label></div>}
   {step===2&&<div className="rounded-3xl bg-white p-5"><b>محتوى المنشور</b><input ref={titleRef} value={title} onChange={e=>setTitle(e.target.value)} onClick={()=>titleRef.current?.focus()} className="mt-3 w-full rounded-xl border p-3" placeholder="اكتب العنوان هنا"/><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-2 min-h-36 w-full rounded-xl border p-3" placeholder="اكتب المنشور..."/><textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3" placeholder="وصف إضافي"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>loadLibrary('emoji')} className="rounded-xl bg-slate-100 px-4 py-2 text-sm font-bold"><Smile className="inline h-4 w-4 ml-1"/>Emoji</button>{emoji.slice(-12).map((e,i)=><span key={i} className="text-2xl">{e}</span>)}</div><div className="mt-4 flex flex-wrap gap-2"><input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/><input type="color" value={background} onChange={e=>setBackground(e.target.value)}/><select value={font} onChange={e=>setFont(e.target.value)} className="rounded-lg border p-2"><option>Arial</option><option>Tahoma</option><option>Georgia</option></select><input type="range" min="16" max="64" value={textSize} onChange={e=>setTextSize(+e.target.value)}/></div></div>}
   {step===3&&<div className="rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><div><b>الموسيقى والصوت</b><p className="text-xs text-slate-500">استمع أولاً ثم اختر الجزء المطلوب.</p></div>{video&&<button onClick={()=>setMuted(v=>!v)} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold">{muted?<Volume2/>:<VolumeX/>}{muted?' تشغيل الصوت الأصلي':' كتم الصوت الأصلي'}</button>}</div>{audio&&<div className="mt-4 rounded-2xl border p-4"><div className="flex items-center gap-3"><button onClick={toggleAudio} className="grid h-11 w-11 place-items-center rounded-full bg-teal-700 text-white">{audioPlaying?<Pause/>:<Play/>}</button><div className="min-w-0 flex-1"><b className="block truncate">{audio.name}</b><span className="text-xs text-slate-500">{audio.source||'المكتبة'}</span></div></div><audio ref={audioEl} src={audio.url} controls className="mt-3 w-full" onLoadedMetadata={e=>{const d=Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:0;if(!audioEnd)setAudioEnd(d)}} onEnded={()=>setAudioPlaying(false)}/><div className="mt-4 space-y-2"><div className="flex justify-between text-[11px] text-slate-500"><span>البداية {audioStart.toFixed(1)}ث</span><span>النهاية {audioEnd.toFixed(1)}ث</span></div><input type="range" min="0" max={Math.max(audio.duration||audioEnd||180,1)} step=".1" value={audioStart} onChange={e=>setAudioStart(Math.min(+e.target.value,Math.max(audioEnd-.1,0)))} className="w-full"/><input type="range" min="0" max={Math.max(audio.duration||audioEnd||180,1)} step=".1" value={audioEnd} onChange={e=>setAudioEnd(Math.max(+e.target.value,audioStart+.1))} className="w-full"/></div></div>}<button onClick={()=>loadLibrary('audio')} className="mt-4 rounded-2xl bg-teal-50 px-5 py-3 font-bold text-teal-700"><Music2 className="inline ml-1"/> فتح مكتبة الموسيقى</button></div>}
   {step===4&&<div className="rounded-3xl bg-white p-5"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal/><b>الفلاتر — تظهر فوراً في المعاينة</b></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{filters.map(f=><button key={f[0]} onClick={()=>setFilter(f[0])} className={'overflow-hidden rounded-2xl border '+(filter===f[0]?'ring-2 ring-teal-600':'')}><div className="aspect-square bg-slate-100">{current?.url?<img src={current.url} className="h-full w-full object-cover" style={{filter:f[0]}}/>:<div className="grid h-full place-items-center text-3xl">SB1</div>}</div><span className="block p-2 text-xs font-bold">{f[1]}</span></button>)}</div></div>}
   {step===5&&<div className="rounded-3xl bg-white p-5"><b>المعاينة النهائية</b><div className="mt-4 overflow-hidden rounded-3xl bg-slate-950">{title&&<div className="bg-white p-4 text-xl font-black text-slate-900">{title}</div>}{preview||<div className="grid min-h-80 place-items-center text-slate-400">لا يوجد محتوى</div>}</div><div className="mt-3 rounded-2xl p-4" style={{background,color:textColor,fontFamily:font,fontSize:textSize}}>{title&&<div className="mb-2 font-black">{title}</div>}{text&&<div className="whitespace-pre-wrap">{text}</div>}{!title&&!text&&'منشور SB1'}</div></div>}
   {step===6&&<div className="rounded-3xl bg-white p-5"><div className="flex items-center gap-2"><CalendarClock/><b>النشر</b></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>setScheduleMode('now')} className={'rounded-2xl border p-4 '+(scheduleMode==='now'?'border-teal-600 bg-teal-50':'')}>نشر الآن</button><button onClick={()=>setScheduleMode('later')} className={'rounded-2xl border p-4 '+(scheduleMode==='later'?'border-teal-600 bg-teal-50':'')}>جدولة</button></div>{scheduleMode==='later'&&<input type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)} className="mt-4 w-full rounded-xl border p-3"/>}<button onClick={publish} className="mt-5 w-full rounded-2xl bg-teal-700 py-4 font-black text-white">{scheduleMode==='later'?'جدولة ونشر':'نشر الآن'}</button>{notice&&<div className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">{notice}</div>}</div>}
  </section><aside className="rounded-3xl bg-slate-950 p-4 text-white lg:sticky lg:top-0 lg:h-fit"><div className="mb-3 flex items-center justify-between"><b>المعاينة الحية</b><span className="rounded-full bg-white/10 px-2 py-1 text-[10px]">المرحلة {step}</span></div><div className="overflow-hidden rounded-2xl bg-black">{preview||<div className="grid min-h-80 place-items-center p-8 text-center text-slate-400">اختر محتوى لتظهر النتيجة هنا فوراً</div>}</div><div className="mt-3 whitespace-pre-wrap rounded-2xl p-4" style={{background,color:textColor,fontFamily:font,fontSize:Math.min(textSize,28),filter}}>{title||text||'اكتب نص المنشور هنا'}</div>{audio&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-white/10 p-3 text-xs"><Music2/> {audio.name}<button onClick={()=>setMuted(v=>!v)} className="mr-auto">{muted?<VolumeX/>:<Volume2/>}</button></div>}</aside></div></main>
  <footer className="flex items-center justify-between border-t bg-white px-4 py-3"><button disabled={step===1} onClick={()=>setStep(s=>s-1)} className="rounded-xl border px-4 py-2 disabled:opacity-30"><ChevronRight className="inline"/> السابق</button><div className="text-xs text-slate-500">{step} / 6</div>{step<6?<button onClick={next} className="rounded-xl bg-teal-700 px-5 py-2 font-bold text-white">التالي <ChevronLeft className="inline"/></button>:<button onClick={publish} className="rounded-xl bg-teal-700 px-5 py-2 font-bold text-white"><Check className="inline"/> نشر</button>}</footer>
 </div>
 {libraryKind&&<div className="fixed inset-0 z-[320] grid place-items-center bg-black/70 p-4" onClick={()=>setLibraryKind(null)}><div className="w-full max-w-5xl max-h-[90vh] overflow-hidden rounded-3xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b p-4"><b className="text-lg">{libraryKind==='image'?'مكتبة الصور':libraryKind==='audio'?'مكتبة الموسيقى':libraryKind==='gif'?'مكتبة GIF':libraryKind==='sticker'?'مكتبة Sticker':'مكتبة Emoji'}</b>{(libraryKind==='image'||libraryKind==='audio')&&<select value={librarySource} onChange={e=>setLibrarySource(e.target.value as any)} className="rounded-xl border p-2 text-sm"><option value="openverse">Openverse — مجاني مفتوح الترخيص</option><option value="pixabay" disabled={libraryKind==='audio'}>Pixabay — مجاني</option></select>}{libraryKind!=='emoji'&&<><input value={libraryQuery} onChange={e=>setLibraryQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loadLibrary(libraryKind,libraryQuery)} className="min-w-0 flex-1 rounded-xl border p-3" placeholder="ابحث داخل المكتبة..."/><button onClick={()=>loadLibrary(libraryKind,libraryQuery)} className="rounded-xl bg-teal-700 p-3 text-white"><Search/></button></>}<button onClick={()=>setLibraryKind(null)}><X/></button></div><div className="max-h-[75vh] overflow-y-auto p-4">{libraryKind==='emoji'?<div className="grid grid-cols-8 gap-2 sm:grid-cols-12 md:grid-cols-16">{emojis.map((e,i)=><button key={i} onClick={()=>setEmoji(v=>[...v,e].slice(-50))} className="rounded-xl p-2 text-2xl hover:bg-slate-100">{e}</button>)}</div>:libraryLoading?<div className="grid min-h-60 place-items-center">جاري تحميل المحتوى الحقيقي...</div>:<div className="grid grid-cols-2 gap-3 sm:grid-cols-4 md:grid-cols-6">{library.map(a=><div key={a.id} onClick={()=>choose(a)} className="cursor-pointer overflow-hidden rounded-2xl border bg-white text-right transition hover:-translate-y-1 hover:border-teal-500 hover:shadow-lg">{a.kind==='audio'?<div className="bg-slate-100 p-3"><div className="mb-2 grid aspect-[4/2] place-items-center"><Music2 className="h-10 w-10 text-teal-700"/></div><audio controls preload="none" src={a.url} className="w-full" onClick={e=>e.stopPropagation()}/></div>:<img src={a.thumbnail||a.url} alt={a.name} className="aspect-square w-full object-cover"/>}<div className="p-2"><b className="block truncate text-xs">{a.name}</b><span className="block truncate text-[10px] text-slate-400">{a.source||'SB1'}</span></div></div>)}</div>}</div></div></div>}
 </div>
}
