import { useState } from 'react';
import { Album, ExternalLink, Gift, Heart, Image, MessageCircle, Plus, Search, Share2, Smartphone, Video, Wand2 } from 'lucide-react';

export default function PageProfileTools(){
 const [post,setPost]=useState(''); const [posts,setPosts]=useState<string[]>([]);
 const [album,setAlbum]=useState<string[]>(['محتوى الصفحة']); const [url,setUrl]=useState('');
 const [note,setNote]=useState('');
 return <div className="mt-8 space-y-5">
  {note&&<div className="rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm font-semibold text-teal-800">{note}</div>}
  <div className="card p-6"><h2 className="text-xl font-extrabold"><Plus className="ml-2 inline h-5 w-5"/>منشور / فيديو / ريلز / صوت</h2><textarea value={post} onChange={e=>setPost(e.target.value)} className="mt-4 min-h-24 w-full rounded-2xl border p-4" placeholder="اكتب منشورك هنا..." /><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>{if(post.trim()){setPosts(v=>[post,...v]);setPost('')}}} className="btn-primary">نشر</button><button className="btn-secondary"><Video className="inline h-4 w-4"/> فيديو</button><button className="btn-secondary"><Image className="inline h-4 w-4"/> صورة</button></div>{posts.map((p,i)=><div key={i} className="mt-3 rounded-2xl border p-4"><div>{p}</div><div className="mt-3 flex gap-5 text-xs text-gray-500"><span><Heart className="inline h-4 w-4"/> إعجاب</span><span><MessageCircle className="inline h-4 w-4"/> تعليق</span></div></div>)}</div>
  <div className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold"><Album className="ml-2 inline h-5 w-5"/>ألبومات الصفحة</h2><button onClick={()=>setAlbum(v=>[...v,'ألبوم جديد'])} className="btn-secondary">إنشاء ألبوم</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{album.map((a,i)=><div key={i} className="rounded-2xl bg-gray-50 p-4"><b>{a}</b><p className="mt-1 text-xs text-gray-500">صور • فيديو • صوت • تسجيلات</p></div>)}</div></div>
  <div className="card p-6"><h2 className="text-xl font-extrabold"><ExternalLink className="ml-2 inline h-5 w-5"/>منصات التواصل داخل SB1</h2><p className="mt-1 text-sm text-gray-500">يمكن الاحتفاظ بالنافذة الحالية وفتح نافذة بحث أخرى، مع إبقاء المفضلة خاصة بالحساب.</p><div className="mt-4 flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} className="flex-1 rounded-xl border p-3" placeholder="رابط YouTube / VK / OK / Rutube..." /><button onClick={()=>setNote('تم حفظ الرابط في المفضلة الخاصة بالحساب فقط.')} className="btn-primary"><Search className="inline h-4 w-4"/> حفظ</button></div><div className="mt-3 rounded-2xl bg-gray-50 p-4 text-sm">لا تظهر بيانات صاحب الحساب الخارجي للعامة.</div></div>
  <div className="card p-6"><div className="flex flex-wrap gap-3"><button onClick={()=>setNote('تم تجهيز نسخة هيكلية: نوع الحساب فقط دون منشورات أو مفضلة أو دورات.')} className="btn-secondary"><Wand2 className="inline h-4 w-4"/> الاستنساخ</button><button onClick={()=>setNote('تم تجهيز رسالة هدية تحتوي الرابط والصلاحيات والمدة.')} className="btn-secondary"><Gift className="inline h-4 w-4"/> إرسال كهديّة</button><button onClick={()=>setNote('ربط الهاتف عبر QR مع إبقاء رقم الهاتف غير ظاهر للعامة.')} className="btn-secondary"><Smartphone className="inline h-4 w-4"/> ربط الهاتف / QR</button><button onClick={()=>setNote('المشاركة الطبية المجانية تجعل المحتوى متاحاً للعامة حسب إعدادات النشر.')} className="btn-secondary"><Share2 className="inline h-4 w-4"/> مشاركة المحتوى الطبي</button></div></div>
 </div>;
}