import {useState} from 'react';
import {Search,ExternalLink,Bookmark,Play,Image as ImageIcon,Loader2} from 'lucide-react';
type Provider='YouTube'|'Rutube'|'Pinterest'|'OK'|'Yandex';
const cfg:any={YouTube:{kind:'video'},Rutube:{kind:'video'},Pinterest:{kind:'image'},OK:{kind:'video'},Yandex:{kind:'web'}};
export default function ProfessionalSocialHub(){
 const [provider,setProvider]=useState<Provider>('YouTube');const [q,setQ]=useState('');const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [open,setOpen]=useState<any>(null);
 const search=async()=>{if(!q.trim())return;setLoading(true);setError('');setItems([]);try{const r=await fetch('/api/social-search?provider='+encodeURIComponent(provider)+'&q='+encodeURIComponent(q.trim()));const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تنفيذ البحث');setItems(d.items||[])}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ البحث')}finally{setLoading(false)}};
 return <section className="rounded-2xl border bg-white shadow-sm overflow-hidden">
  <div className="border-b bg-slate-950 p-4 text-white"><div className="flex items-center justify-between"><div><b className="text-lg">بحث المنصات داخل SB1</b><p className="mt-1 text-xs text-slate-300">نتائج حقيقية من واجهة المنصة، مع عرض بصري داخل صفحتك.</p></div><ExternalLink/></div>
   <div className="mt-4 grid gap-2 md:grid-cols-[160px_1fr_110px]"><select value={provider} onChange={e=>{setProvider(e.target.value as Provider);setItems([]);setError('')}} className="rounded-xl bg-white p-3 text-sm font-bold text-slate-900">{Object.keys(cfg).map(x=><option key={x}>{x}</option>)}</select><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} className="rounded-xl bg-white p-3 text-slate-900 outline-none" placeholder={'ابحث داخل '+provider+' كما لو كنت تستخدمها...'}/><button onClick={search} className="rounded-xl bg-teal-600 px-4 font-black"><Search className="mx-auto"/></button></div>
  </div>
  {loading&&<div className="grid place-items-center p-12"><Loader2 className="h-8 w-8 animate-spin text-teal-700"/></div>}
  {error&&<div className="m-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">{error}</div>}
  {!loading&&!error&&items.length>0&&<div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><article key={x.id||i} className="overflow-hidden rounded-2xl border bg-white shadow-sm hover:shadow-md"><button onClick={()=>setOpen(x)} className="block w-full text-right">{x.thumbnail||x.image?<img src={x.thumbnail||x.image} className="aspect-video w-full object-cover" alt=""/>:<div className="grid aspect-video place-items-center bg-slate-100">{cfg[provider].kind==='video'?<Play/>:<ImageIcon/>}</div>}<div className="p-3"><b className="line-clamp-2 text-sm">{x.title||'نتيجة بحث'}</b><p className="mt-1 line-clamp-2 text-xs text-slate-500">{x.description||''}</p><span className="mt-2 block text-[11px] text-slate-400">{x.author||x.channelTitle||''}</span></div></button><div className="flex border-t p-2"><button onClick={()=>{try{localStorage.setItem('sb1_external_saved_'+(x.id||i),JSON.stringify(x))}catch{} }} className="flex-1 rounded-lg py-2 text-xs font-bold hover:bg-slate-50"><Bookmark className="inline h-4 w-4 ml-1"/>حفظ</button><a href={x.url||'#'} target="_blank" rel="noreferrer" className="flex-1 rounded-lg py-2 text-center text-xs font-bold text-teal-700 hover:bg-teal-50">فتح المنصة</a></div></article>)}</div>}
  {!loading&&!error&&q&&items.length===0&&<div className="p-12 text-center text-sm text-slate-500">لا توجد نتائج أو أن API المنصة لم يُربط بعد.</div>}
  {open&&<div className="fixed inset-0 z-[250] grid place-items-center bg-black/70 p-4" onClick={()=>setOpen(null)}><div className="w-full max-w-4xl overflow-hidden rounded-2xl bg-white" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b p-4"><b>{open.title}</b><button onClick={()=>setOpen(null)}>×</button></div>{open.url&&provider==='YouTube'&&open.id?<iframe src={'https://www.youtube.com/embed/'+open.id} className="h-[65vh] w-full" allowFullScreen/>:open.image?<img src={open.image} className="max-h-[70vh] w-full object-contain bg-black" alt=""/>:<div className="p-8"><a className="text-teal-700 underline" href={open.url} target="_blank" rel="noreferrer">فتح المحتوى في المنصة</a></div>}</div></div>}
 </section>
}