-- SB1 course marketplace: private course chat, moderation terms, 50/50 revenue split, and free-seat allocation.
alter table if exists public.courses add column if not exists is_free boolean default false;
alter table if exists public.courses add column if not exists platform_share_percent numeric default 50;
alter table if exists public.courses add column if not exists specialist_share_percent numeric default 50;
alter table if exists public.courses add column if not exists moderation_required boolean default true;
alter table if exists public.courses add column if not exists specialist_connect_account_id text;
alter table if exists public.courses add column if not exists free_seats integer default 1;
alter table if exists public.courses add column if not exists terms_version text default 'course-v1';

create table if not exists public.course_enrollments (
 id uuid primary key default gen_random_uuid(),
 course_id uuid references public.courses(id) on delete cascade,
 user_id uuid null,
 student_name text,
 student_email text,
 payment_status text not null default 'pending',
 stripe_session_id text,
 amount numeric default 0,
 currency text default 'USD',
 created_at timestamptz not null default now(),
 unique(course_id,student_email)
);
alter table public.course_enrollments enable row level security;

create table if not exists public.course_chat_messages (
 id uuid primary key default gen_random_uuid(),
 course_id uuid references public.courses(id) on delete cascade,
 sender_id uuid null,
 sender_name text not null,
 body text not null,
 is_flagged boolean default false,
 created_at timestamptz not null default now()
);
alter table public.course_chat_messages enable row level security;

create table if not exists public.course_moderation_rules (
 id bigint generated by default as identity primary key,
 rule_key text unique not null,
 rule_text text not null,
 active boolean default true,
 created_at timestamptz not null default now()
);
insert into public.course_moderation_rules(rule_key,rule_text) values
('no_religion','يمنع التحدث في الدين داخل الدورة أو دردشتها'),
('no_politics','يمنع المحتوى السياسي'),
('no_adult','يمنع المحتوى الإباحي'),
('no_profanity','تمنع الألفاظ البذيئة'),
('no_external_links','تمنع الروابط الخارجية'),
('no_contact_exchange','يمنع تبادل أرقام الهاتف أو حسابات التواصل الاجتماعي')
on conflict(rule_key) do nothing;

create or replace function public.sb1_course_free_seats(p_enrolled integer,p_lessons integer)
returns integer language sql immutable as $$
 select case when coalesce(p_enrolled,0)>50 then greatest(1,ceil(coalesce(p_enrolled,0)*0.10)::integer)
 else least(3,greatest(1,ceil(coalesce(p_lessons,1)/10.0)::integer)) end;
$$;

update public.courses
set platform_share_percent=50,specialist_share_percent=50,moderation_required=true
where platform_share_percent is null or specialist_share_percent is null;
