import { resilientFetch } from '../src/lib/resilience.js';
const send=(res:any,b:any,s=200)=>{res.statusCode=s;res.setHeader('content-type','application/json');res.end(JSON.stringify(b));};
async function checkout(req:any,res:any){
 if(req.method!=='POST')return send(res,{error:'Method not allowed'},405); const secret=process.env.STRIPE_SECRET_KEY;
 if(!secret)return send(res,{error:'Stripe is not configured. Add STRIPE_SECRET_KEY in Vercel.'},503);
 try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});if(!b.amount||b.amount<=0)return send(res,{error:'Invalid amount'},400);
 const currency=(b.currency||'usd').toLowerCase(),origin=req.headers?.origin||process.env.SB1_PUBLIC_URL||'https://sb1.vercel.app';
 const params=new URLSearchParams();params.set('mode','payment');params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]',currency);params.set('line_items[0][price_data][unit_amount]',String(Math.round(b.amount*100)));params.set('line_items[0][price_data][product_data][name]',b.description||'SB1 Medical Service');params.set('success_url',b.success_url||origin+'/payments?success=1&reference='+encodeURIComponent(b.reference_id||''));params.set('cancel_url',b.cancel_url||origin+'/payments?cancelled=1&reference='+encodeURIComponent(b.reference_id||''));if(b.customer_email)params.set('customer_email',b.customer_email);
 const fee=Math.max(0,Math.min(100,Number(process.env.SB1_PLATFORM_FEE_PERCENT||20))),dest=process.env.STRIPE_CONNECT_ACCOUNT_ID;if(dest){params.set('payment_intent_data[application_fee_amount]',String(Math.round(b.amount*100*fee/100)));params.set('payment_intent_data[transfer_data][destination]',dest);}params.set('metadata[reference_id]',b.reference_id||'');params.set('metadata[platform]','SB1');
 const r=await resilientFetch({name:'stripe-checkout',url:'https://api.stripe.com/v1/checkout/sessions',enabled:true},{name:'payment-fallback',url:process.env.SB1_PAYMENT_FALLBACK_URL||'',enabled:!!process.env.SB1_PAYMENT_FALLBACK_URL},{method:'POST',headers:{Authorization:'Bearer '+secret,'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()},12000);const d=await r.json();if(!r.ok)return send(res,{error:d?.error?.message||'Stripe checkout failed'},r.status);return send(res,{url:d.url,id:d.id,platform_fee_percent:dest?fee:0});}catch(e){return send(res,{error:e instanceof Error?e.message:'Checkout failed'},500)}}
async function wallet(req:any,res:any,confirm:boolean){
 if(req.method!=='POST')return send(res,{error:'Method not allowed'},405);const secret=process.env.STRIPE_SECRET_KEY;if(!secret)return send(res,{error:'Stripe is not configured'},503);
 try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});
 if(confirm){const u=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)return send(res,{error:'Wallet server integration is not configured'},503);if(!b.session_id)return send(res,{error:'Missing session'},400);const sr=await fetch('https://api.stripe.com/v1/checkout/sessions/'+encodeURIComponent(b.session_id),{headers:{Authorization:'Bearer '+secret}}),s=await sr.json();if(!sr.ok||s.payment_status!=='paid'||s.metadata?.type!=='wallet_topup')return send(res,{error:'Payment not verified'},400);const amount=Number(s.amount_total||0)/100,key=String(s.metadata.account_key||'');if(!key||!amount)return send(res,{error:'Invalid payment metadata'},400);const headers={apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json','Prefer':'return=representation'};const rr=await fetch(u+'/rest/v1/rpc/sb1_wallet_credit',{method:'POST',headers,body:JSON.stringify({p_account_key:key,p_amount:amount,p_currency:String(s.currency||'usd').toUpperCase(),p_reference_type:'stripe_checkout',p_reference_id:s.id,p_description:'Wallet top up'})}),result=await rr.json();if(!rr.ok)return send(res,{error:result?.message||'Wallet update failed'},500);return send(res,{ok:true,balance:result?.balance||0,amount,session_id:s.id,duplicate:!!result?.duplicate});}
 const amount=Number(b.amount),accountKey=String(b.account_key||'').trim();if(!amount||amount<=0||!accountKey)return send(res,{error:'Invalid wallet top-up'},400);const origin=req.headers?.origin||process.env.SB1_PUBLIC_URL||'http://localhost:5173',ref='wallet-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);const p=new URLSearchParams();p.set('mode','payment');p.set('line_items[0][quantity]','1');p.set('line_items[0][price_data][currency]',String(b.currency||'usd').toLowerCase());p.set('line_items[0][price_data][unit_amount]',String(Math.round(amount*100)));p.set('line_items[0][price_data][product_data][name]','SB1 Wallet Top Up');p.set('success_url',origin+'/wallet?topup=success&session_id={CHECKOUT_SESSION_ID}');p.set('cancel_url',origin+'/wallet?topup=cancelled');p.set('metadata[reference_id]',ref);p.set('metadata[account_key]',accountKey);p.set('metadata[type]','wallet_topup');const sr=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+secret,'Content-Type':'application/x-www-form-urlencoded'},body:p.toString()}),d=await sr.json();if(!sr.ok)return send(res,{error:d?.error?.message||'Stripe checkout failed'},sr.status);return send(res,{url:d.url,id:d.id,reference_id:ref});}catch(e){return send(res,{error:e instanceof Error?e.message:'Wallet request failed'},500)}}
export default async function handler(req:any,res:any){const r=String(req.query?.route||'');if(r==='confirm')return wallet(req,res,true);if(r==='wallet')return wallet(req,res,false);return checkout(req,res);}